<script type="text/javascript">
$(function(){
	$("table")
		.tablesorter({theme: 'blue', widthFixed: true, widgets: ['zebra', 'filter']})
		.tablesorterPager({container: $(".pager"), 
							output: '{startRow} - {endRow} / {filteredRows} ({totalRows})', 
							fixedHeight: true, 
							removeRows: false, 
							cssGoto: '.gotoPage' });
});
</script>

<div class="content-header"></div>
<div class="UI_Header_Title">
	<h1><?=$this->avatar;?> Pilih <?=$this->tipe_pengguna3;?></h1>
	<div class="header_nav_links"><a href="/admin/acara/edit/id/<?=$this->id;?>">Back to Daftar Acara</a></div>
</div>
<div class="clear"></div>
<br>
<? if (count($this->rows) > 0) { ?>
	<form id="compose" name="compose" method="post" action="" enctype="multipart/form-data">
		<?=$this->pager;?>

		<table id="myTable" class="tablesorter" style="margin:auto;" width="100%">
			<thead>
				<tr>
					<td align="center">
						<script language="javascript">
						checked=false;
						function checkedAll(form) {
							if (checked == false){checked = true;}
							else{checked = false;}
							for (var i=0; i < form.elements.length; i++){
								var name = form.elements[i].name;
								if(name.indexOf("cbDelete",0) == 0)
									form.elements[i].checked = checked;
							}
						}
						</script> 

						<input type="checkbox" onclick="checkedAll(this.form);">
					</td>
					<th>No. Anggota</th>
					<th>Nama</th>
					<th>Jabatan</th>
					<th>Unit Kerja</th>
					<!--<th>Golongan</th>
					<th>Email</th>-->
				</tr>
			</thead>
			<tbody>
			<?php
				$indeks = 1;
				foreach($this->rows as $row) 
				{
					echo '<tr>';
					echo '<td align="center"><input type="checkbox" name="cbDelete[]" id="cbDelete' . $indeks . '" value="' . $row->id . '|' . $row->nomor . '|' . $row->nama . '|' . $row->email . '"></td>';
					echo '<td align="center">'.$row->nomor.'</td>';
					echo '<td>'.$row->nama.'</td>';
					echo '<td>'.$row->jabatan.'</td>';
					echo '<td>'.$row->unit_kerja.'</td>';
					//echo '<td align="center">'.$row->golongan.'</td>';
					//echo '<td align="center">'.$row->email.'</td>';
					echo '</tr>';

					$indeks++;
				}
			?>	
			</tbody>
		</table>
		<br>
		<div class="tabular">
			<p class="savecancel">
				<input type="hidden" id="id_tipe_pengguna" name="id_tipe_pengguna" value="<?=$this->id_tipe_pengguna;?>">
				<label class="UIbutton-small"><input type="submit" value="Simpan" class=""/></label>
				<a href="/admin/tim/edit/id/<?=$this->id;?>" class="UIbutton-small">Kembali</a>
			</p>
		</div>
	</form>
<? } else {
	echo 'Data tidak ditemukan.';
}
?>