<script src="https://tinymce.cachefly.net/4.1/tinymce.min.js"></script>
<script src="/vendor/FileSaver.js"></script>
<script src="/build/html-docx.js"></script>

<script type="text/javascript">
	$(document).ready(function() {
		$("#compose").validate();
		$("#tanggal_sk_pimpinan").datepicker({yearRange:"-10:+10",changeYear:"true",changeMonth:"true",dateFormat:"dd-mm-yy"});
		$("#tanggal_sk_presiden").datepicker({yearRange:"-10:+10",changeYear:"true",changeMonth:"true",dateFormat:"dd-mm-yy"});
		$("#tanggal_ttd").datepicker({yearRange:"-10:+10",changeYear:"true",changeMonth:"true",dateFormat:"dd-mm-yy"});
		$.validator.addMethod("time", function(value, element) {
			return this.optional(element) || /^(([0-1]?[0-9])|([2][0-3])):([0-5]?[0-9])$/i.test(value);
		}, "Format waktu salah.");
		$(".timepicker").mask("99:99");
		$("table")
			.tablesorter({theme: 'blue', widthFixed: true, widgets: ['zebra', 'filter']})
			.tablesorterPager({container: $(".pager"), 
								output: '{startRow} - {endRow} / {filteredRows} ({totalRows})', 
								fixedHeight: true, 
								removeRows: false, 
								cssGoto: '.gotoPage' });
	});

function selectFields(indeks, id, nomor, nama) 
{
	if(indeks==1){
		$('#no_ketua_rapat').val(nomor);
		$('#nama_ketua_rapat').val(nama);
		$('#id_ketua_rapat').val(id);
	}else if(indeks==2){
		$('#no_sekretaris_rapat').val(nomor);
		$('#nama_sekretaris_rapat').val(nama);
		$('#id_sekretaris_rapat').val(id);
	}
	
	$.facebox.close();
}

function ClearFields(id) 
{
	if(id==1){
		document.getElementById("no_ketua_rapat").value = "";
		document.getElementById("nama_ketua_rapat").value = "";
		document.getElementById("id_ketua_rapat").value = "";
	}else if(id==2){
		document.getElementById("no_sekretaris_rapat").value = "";
		document.getElementById("nama_sekretaris_rapat").value = "";
		document.getElementById("id_sekretaris_rapat").value = "";
	 }
}
</script>

<div class="content-header"></div>
<div class="UI_Header_Title">
	<h1><?=$this->avatar;?>  Edit Catatan Rapat</h1>
	<div class="header_nav_links"><a href="/admin/catatan-rapat">Back to Daftar Catatan Rapat</a></div>
</div>
<div class="clear"></div>
<form id="compose" name="compose" method="post" action="" enctype="multipart/form-data">
	<div class="tabular">
		<p><label>AKD</label><select class="required" id="id_akd" name="id_akd">
			<option value="">-- Pilih AKD --</option>
			<?
			foreach($this->AkdRows as $row)
			{
				$selected = ($this->row->id_akd == $row->id) ? ' selected' : '';
				echo '<option value="' . $row->id . '"' . $selected . '>' . $row->nama . '</option>';
			}
			?>
		</select> <font color="red">*</font></p>
		<p><label>Bidang</label>
		<select class="required" id="bidang" name="bidang">
			<option value="">-- Pilih Bidang --</option>
			<?
			$arrBidang = array(
				'Kerjasama Organisasi Internasional' => 'Kerjasama Organisasi Internasional',
				'Kerjasama Organisasi Regional' => 'Kerjasama Organisasi Regional',
				'Kerjasama Bilateral' => 'Kerjasama Bilateral'
			);
			foreach($arrBidang as $key => $value)
			{
				$selected = ($this->row->bidang == $key) ? ' selected' : '';
				echo '<option value="' . $value . '"' . $selected . '>' . $key . '</option>';
			}
			?>
		</select> <font color="red">*</font>
		<p><label>Tahun Sidang :</label><input type="text" class="required" id="tahun_sidang" autocomplete="disable" name="tahun_sidang" value="<?=$this->row->tahun_sidang;?>" /> <font color="red">*</font></p>
		<p><label>Masa Persidangan :</label><input type="text" class="required" id="masa_persidangan" autocomplete="disable" name="masa_persidangan" value="<?=$this->row->masa_persidangan;?>" /> <font color="red">*</font></p>
		<p><label>Rapat Ke :</label><input type="text" class="required" id="rapat_ke" autocomplete="disable" name="rapat_ke" value="<?=$this->row->rapat_ke;?>" /> <font color="red">*</font></p>		
		<p><label>Jenis Rapat</label>
		<select class="required" id="id_jenis_rapat" name="id_jenis_rapat">
			<option value="">-- Pilih Jenis Rapat --</option>
			<?
			foreach($this->JenisRapatRows as $row)
			{
				$selected = ($this->row->id_jenis_rapat == $row->id) ? ' selected' : '';
				echo '<option value="' . $row->id . '"' . $selected . '>' . $row->nama . '</option>';
			}
			?>
		</select> <font color="red">*</font>
		
		<p><label>Sifat Rapat</label>
		<select class="required" id="sifat_rapat" name="sifat_rapat">
			<option value="">-- Pilih Sifat Rapat --</option>
			<?
			$arrSifatRapat = array(
				'Terbuka' => 'Terbuka',
				'Tertutup' => 'Tertutup'
			);
			foreach($arrSifatRapat as $key => $value)
			{
				$selected = ($this->row->sifat_rapat == $key) ? ' selected' : '';
				echo '<option value="' . $value . '"' . $selected . '>' . $key . '</option>';
			}
			?>
		</select> <font color="red">*</font>
		<p><label>Tanggal</label><input readonly type="text" class="datepicker  required" id="tanggal" autocomplete="disable" name="tanggal" value="<?=$this->FormatDate($this->row->tanggal);?>" /> <font color="red">*</font></p>
		<p><label>Waktu</label><input placeholder="23:59" type="text" class="timepicker required" id="waktu" autocomplete="disable" name="waktu" value="<?=$this->row->waktu;?>" /> <font color="red">*</font></p>
		<p><label>Tempat</label><input type="text" class="required" id="tempat" autocomplete="disable" name="tempat" value="<?=$this->row->tempat;?>" /> <font color="red">*</font></p>
		<p><label>Acara</label><input type="text" class="required" id="acara" autocomplete="disable" name="acara" value="<?=$this->row->acara;?>" /> <font color="red">*</font></p>
		
		<?
		$struktur = array(
			'I' => 'I. PENDAHULUAN',
			'II' => 'II. KESIMPULAN / KEPUTUSAN',
			'III' => 'III. PENUTUP'
		);
		?>
		<p><label>Hadir</label><a href="/admin/catatan-rapat/add-data/id/<?=$this->row->id;?>/col/hadir" class="UIbutton-small" rel="facebox">Tambah Data</a>&nbsp;<a href="/admin/catatan-rapat/edit-data/id/<?=$this->row->id;?>/col/hadir" class="UIbutton-small" rel="facebox">Edit Data</a>&nbsp;<a href="/admin/catatan-rapat/view-data/id/<?=$this->row->id;?>/col/hadir" class="UIbutton-small" rel="facebox">View Data</a></p>
		<p><label><?=$struktur['I'];?></label><a href="/admin/catatan-rapat/add-data/id/<?=$this->row->id;?>/col/I" class="UIbutton-small" rel="facebox">Tambah Data</a>&nbsp;<a href="/admin/catatan-rapat/edit-data/id/<?=$this->row->id;?>/col/I" class="UIbutton-small" rel="facebox">Edit Data</a>&nbsp;<a href="/admin/catatan-rapat/view-data/id/<?=$this->row->id;?>/col/I" class="UIbutton-small" rel="facebox">View Data</a></p>
		<p><label><?=$struktur['II'];?></label><a href="/admin/catatan-rapat/add-data/id/<?=$this->row->id;?>/col/II" class="UIbutton-small" rel="facebox">Tambah Data</a>&nbsp;<a href="/admin/catatan-rapat/edit-data/id/<?=$this->row->id;?>/col/II" class="UIbutton-small" rel="facebox">Edit Data</a>&nbsp;<a href="/admin/catatan-rapat/view-data/id/<?=$this->row->id;?>/col/II" class="UIbutton-small" rel="facebox">View Data</a></p>
		<p><label><?=$struktur['III'];?></label><a href="/admin/catatan-rapat/add-data/id/<?=$this->row->id;?>/col/III" class="UIbutton-small" rel="facebox">Tambah Data</a>&nbsp;<a href="/admin/catatan-rapat/edit-data/id/<?=$this->row->id;?>/col/III" class="UIbutton-small" rel="facebox">Edit Data</a>&nbsp;<a href="/admin/catatan-rapat/view-data/id/<?=$this->row->id;?>/col/III" class="UIbutton-small" rel="facebox">View Data</a></p>

		<!--<p><label><?=$struktur['I'];?></label><textarea class="required" name="I" id="I" cols="100" rows="8" wrap="soft" class="event-message"><?=$this->row->I;?></textarea> <font color="red">*</font></p>
		<p><label><?=$struktur['II'];?></label><textarea class="required" name="II" id="II" cols="100" rows="8" wrap="soft" class="event-message"><?=$this->row->II;?></textarea> <font color="red">*</font></p>
		<p><label><?=$struktur['III'];?></label><textarea class="required" name="III" id="III" cols="100" rows="8" wrap="soft" class="event-message"><?=$this->row->III;?></textarea> <font color="red">*</font></p>-->

		<p><label>Nama Ketua Rapat</label><input readonly class="" type="text" id="nama_ketua_rapat" autocomplete="disable" name="nama_ketua_rapat" value="<?=$this->row->nama_ketua_rapat;?>"/><input readonly class="" type="hidden" id="no_ketua_rapat" autocomplete="disable" name="no_ketua_rapat" value="<?=$this->row->no_ketua_rapat;?>"/> <input class="required" type="hidden" id="id_ketua_rapat" autocomplete="disable" name="id_ketua_rapat" value="<?=$this->row->id_ketua_rapat;?>"/> <input type="button" value="..." id="btnKetuaRapat" onclick="jQuery.facebox({ ajax: '/admin/catatan-rapat/search-ketua-rapat'});"> <input type="button" onclick="ClearFields(1);" value="Clear"> <font color="red">*</font></p>

		<p><label>Nama Sekretaris Rapat</label><input readonly class="" type="text" id="nama_sekretaris_rapat" autocomplete="disable" name="nama_sekretaris_rapat" value="<?=$this->row->nama_sekretaris_rapat;?>"/> <input readonly class="" type="hidden" id="no_sekretaris_rapat" autocomplete="disable" name="no_sekretaris_rapat" value="<?=$this->row->no_sekretaris_rapat;?>"/><input class="required" type="hidden" id="id_sekretaris_rapat" autocomplete="disable" name="id_sekretaris_rapat" value="<?=$this->row->id_sekretaris_rapat;?>"/> <input type="button" value="..." id="btnSekretarisRapat" onclick="jQuery.facebox({ ajax: '/admin/catatan-rapat/search-sekretaris-rapat'});"> <input type="button" onclick="ClearFields(2);" value="Clear"> <font color="red">*</font></p>

		<p class="savecancel"><label class="UIbutton-small"><input type="submit" value="Simpan" class=""/></label><a href="/admin/catatan-rapat/print/id/<?=$this->row->id;?>" class="UIbutton-small">Cetak</a>&nbsp;<a href="/admin/catatan-rapat" class="UIbutton-small">Batal</a></p>
		
		<? if (count($this->rows) > 0) { ?>
			<?=$this->pager;?>

			<table cellspacing="1" cellpadding="6" width="100%" class="tablesorter">
				<thead>
					<tr>
						<th align="center">Judul</th>
						<th align="center">Urutan</th>
						<th align="center">Konten</th>
						<th>&nbsp;</th>
					</tr>
				</thead>
				<tbody>
					<?php
						foreach($this->rows as $row) 
						{
							echo '<tr>';
							echo '<td>' . $row->judul . '</td>';
							echo '<td>' . $row->urutan . '</td>';
							echo '<td>' . $row->konten . '</td>';
							echo '<td align="center"><a href="/admin/catatan-rapat/edit-data/id/'. $row->id .'/col/' . $row->judul . '">EDIT</a>';
							if ($this->getRole() == "admin" || $this->getRole() == "super") {
								echo '&nbsp;|&nbsp;<a href="/admin/catatan-rapat/delete-data/id/' . $row->id . '" onclick="return confirmDelete();">DELETE</a></td>';
							}
							echo '</tr>';
						}
					?>				
				</tbody>
			</table>
		<? } else {
			echo 'Data tidak ditemukan.';
		} ?>

	</div>
</form>
<div style="clear:both"></div>