<script type="text/javascript">
$(function(){
	$("table")
		.tablesorter({theme: 'blue', widthFixed: true, widgets: ['zebra', 'filter']})
		.tablesorterPager({container: $(".pager"), 
							output: '{startRow} - {endRow} / {filteredRows} ({totalRows})', 
							fixedHeight: true, 
							removeRows: false, 
							cssGoto: '.gotoPage' });
});
</script>

<div class="content-header"></div>
	<div class="UI_Header_Title">
		<h1><?=$this->avatar;?>  Daftar Catatan Rapat</h1>
		<div class="header_nav_links"><span class="right context_menu"><a href="/admin/catatan-rapat/add" class="UIlink-button small right">Tambah Catatan Rapat</a></span>
	</div>
</div>
<div class="clear"></div>
<br/>
<? if (count($this->rows) > 0) { ?>
	<?=$this->pager;?>

	<table cellspacing="1" cellpadding="6" width="100%" class="tablesorter">
		<thead>
			<tr>
				<th align="center">AKD</th>
				<th align="center">Bidang</th>
				<th align="center">Acara</th>
				<th align="center">Tanggal</th>
				<th>&nbsp;</th>
			</tr>
		</thead>
		<tbody>
		<?php
			foreach($this->rows as $row) 
			{
				echo "<tr>";
				echo "<td>" . $row->id_akd . "</td>";
				echo "<td align='center'>" . $row->bidang . "</td>";
				echo "<td>" . $row->acara . "</td>";
				echo "<td align='center'>" . $this->FormatDate($row->tanggal) . "</td>";
				echo "<td align='center'><a href='/admin/catatan-rapat/edit/id/". $row->id ."'>EDIT</a>";
				if ($this->getRole() == "admin" || $this->getRole() == "super") {
					echo "&nbsp;|&nbsp;<a href='/admin/catatan-rapat/delete/id/" . $row->id . "' onclick='return confirmDelete();'>DELETE</a></td>";
				}
				echo '</tr>';
			}
		?>
		
		</tbody>
	</table>
<? } else {
	echo 'Data tidak ditemukan.';
} ?>