<script type="text/javascript">
$(function() {
	$("#search_table")
		.tablesorter({theme: 'blue', widthFixed: true, widgets: ['zebra', 'filter']})
		.tablesorterPager({container: $(".pager2"), 
							output: '{startRow} - {endRow} / {filteredRows} ({totalRows})', 
							fixedHeight: true, 
							removeRows: false, 
							cssGoto: '.gotoPage' });
});
</script>

<?=$this->pager2;?>

<table id="search_table" class="tablesorter">
	<thead>
		<tr>
			<th>Nomor</th>
			<th>Nama</th>
			<th>Aksi</th>
		</tr>
	</thead>
	<tbody>
		<?
		$i = 1;
		foreach($this->rows as $row)
		{
			echo '<tr>';
			echo '<td align="center">' . $row->nomor . '</td>';
			echo '<td align="center">' . $row->nama . '</td>';
			echo '<td align="center"><a href="javascript:selectFields(1, \'' . $row->id . '\', \'' . $row->nomor . '\', \'' . $row->nama . '\')">PILIH</a></td>';
			echo '</tr>';

			$i++;
		}	
		?>	
	</tbody>
</table>