<script type="text/javascript">
    $(function() {
        $("#table_facebox")
            .tablesorter({
                theme: 'blue',
                widthFixed: true,
                widgets: ['zebra', 'filter']
            })
            .tablesorterPager({
                container: $(".pager2"),
                output: '{startRow} - {endRow} / {filteredRows} ({totalRows})',
                fixedHeight: true,
                removeRows: false,
                cssGoto: '.gotoPage'
            });
    });


        // Cari semua elemen gambar dengan kelas "close_image"
        var closeImages = document.getElementsByClassName("close_image");

        // Loop melalui setiap elemen gambar
        for (var i = 0; i < closeImages.length; i++) {
        var image = closeImages[i];
        
        // Periksa apakah atribut src mengandung "/facebox/closelabel.png"
        if (image.src.includes("/facebox/closelabel.png")) {
            // Ganti isi atribut src dengan URL baru
            image.src = "https://cdnjs.cloudflare.com/ajax/libs/facebox/1.3/closelabel.png";
        }
        }

    
</script>

<div class="content-header"></div>
<div class="UI_Header_Title">
    <h1><?= $this->avatar; ?> Pilih Nama Batch </h1>
</div>
<div class="clear"></div>
<br>

<? if (count($this->rows) > 0) { ?>
    <?= $this->pager2; ?>

    <table cellspacing="1" cellpadding="6" width="100%" class="tablesorter" id="table_facebox">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nama Batch</th>
                <th>Aksi</th>
            </tr>
        </thead>
        <tbody>
            <?
            $i = 1;
            foreach ($this->rows as $row) {
                echo '<tr>';
                echo '<td align="center">' . $row->id . '</td>';
                echo '<td>'. $row->judul_batch .'</td>';
                echo '<td align="center"><a href="javascript:selectFields1(\'' . $row->id . '\', \'' . $row->id . '\', \'' . $row->judul_batch . '\')">PILIH</a></td>';
                echo '</tr>';

                $i++;
            }
            ?>
        </tbody>
    </table>
<? } else {
    echo 'Data tidak ditemukan.';
}
?>