<script id="js">
	$(function(){
		$("table")
			.tablesorter({
				theme: 'blue', 
				widthFixed: true, 
				widgets: ['zebra', 'filter']
			})
			.tablesorterPager({
				container: $(".pager"), 
				output: '{startRow} - {endRow} / {filteredRows} ({totalRows})', 
				fixedHeight: true, 
				removeRows: false, 
				cssGoto: '.gotoPage' 
			});
	});
</script>

<div class="content-header"></div>
	<div class="UI_Header_Title">
		<h1><?=$this->avatar;?> Daftar Penugasan</h1>
		<!-- <div class="header_nav_links"><span class="right context_menu"><a href="/penilai/penugasan/add" class="UIlink-button small right">Tambah Penugasan</a></span>
	</div> -->
</div>
<div class="clear"></div>
<br>

<? if (count($this->rows) > 0) { ?>
	<?=$this->pager;?>

	<table class="tablesorter">
		 <thead>
			 <tr>
			 	<th width="5px">No.</th>
				<th align="center">Nama Peserta</th>
				<th align="center">Judul Batch</th>
				<th align="center">Title</th>
				<th align="center">File Tugas</th>
				<th align="center">File Jawaban</th>
				<th align="center">Skor</th>
				<th align="center">Aksi</th>
			</tr>
		</thead>
		<tbody>
			<?php
			$index = 1;
			foreach($this->rows as $row)
			{
				echo '<tr>';
				echo '<td align="center">'. $index++ .'.</td>';
				foreach($this->peserta as $x){
					if($x->id == $row->id_peserta){
						echo '<td align="center">'. $x->nama .'</td>';
						break;
					}
				}
				foreach($this->Batch as $y){
					if($y->id == $row->id_batch){
						echo '<td align="center">'. $y->judul_batch .'</td>';
						break;
					}
				}
				echo '<td align="center">'. $row->title .'</td>';
				echo '<td align="center">'.($row->file_title == '' ? '-': $row->file_title).'</td>';
				echo '<td align="center">'.($row->file_tugas == '' ? '-': $row->file_tugas).'</td>';
				echo '<td align="center">'. $row->skor_akhir .'</td>';
				echo '<td align="center">
				'.($row->file_tugas == '' ? 'Belum Dapat Dinilai': '<a href="/penilai/penugasan/nilai/id/'. $row->id .'">NILAI</a>');
				echo '</td>';
				echo '</tr>';
			}
			?>
		</tbody>
	</table>
<? } else {
	echo 'Data tidak ditemukan.';
}
?>