<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Portal LMS</title>
  <link rel="stylesheet" href="./style.css">
  <style>
    body, html {
      height:100%;
      background: #1c1e21;
        overflow-x: hidden;
      font-family: 'Dosis', sans-serif;
    }

    btn {
      border-radius: 0
    }

    .btn:focus, .btn:active, .btn.active, .btn:active:focus {
      outline: 0;
      border-radius: 0
    }

    .btn-larger {
      padding: 15px 40px !important;
      border:2px solid #F7CA18 !important;;
      border-radius: 0px !important;;
      text-transform: uppercase;
      font-family: 'Dosis', sans-serif;
      font-size: 18px;
      font-weight: 300;
      color: #F7CA18;
      background-color: transparent;
      -webkit-transition: all .6s;
      -moz-transition: all .6s;
      transition: all .6s;
    }
    
    .btn-larger:hover, .btn-larger:focus, .btn-larger:active, .btn-larger.active, .open .dropdown-toggle.btn-larger {
      border-color: #F7CA18;
      color: #fff;
      background-color: #F7CA18;
      border-radius: 0
    }
    .btn-larger:active, .btn-larger.active, .open .dropdown-toggle.btn-larger {
      background-image: none;
    }
    .btn-larger.disabled, .btn-larger[disabled], fieldset[disabled] .btn-larger, .btn-larger.disabled:hover, .btn-larger[disabled]:hover, fieldset[disabled] .btn-larger:hover, .btn-larger.disabled:focus, .btn-larger[disabled]:focus, fieldset[disabled] .btn-larger:focus, .btn-larger.disabled:active, .btn-larger[disabled]:active, fieldset[disabled] .btn-larger:active, .btn-larger.disabled.active, .btn-larger[disabled].active, fieldset[disabled] .btn-larger.active {
      border-color: #AEA8D3;
      background-color: #AEA8D3;
    }
    .btn-larger .badge {
      color: #AEA8D3;
      background-color: #fff;
    }

    div#form {
      color: #fff;
      background-attachment: scroll;
      background: #1c1e21 url(https://static.pexels.com/photos/8819/warsaw.jpg);
      background-position: center center;
      background-repeat: none;
      -webkit-background-size: cover;
      -moz-background-size: cover;
      background-size: cover;
      -o-background-size: cover;
      min-height:100%;

    }

    #userform {
      background: rgba(0,0,0,0.8);
      margin: 20px 0 20px 0
    }
    @media (min-width: 768px) {
    #userform {
      background: rgba(0,0,0,0.8);
      margin: 50px 0 20px 0
    }
    }
    #userform .nav-tabs.nav-justified > li > a {
      text-transform: uppercase;
      font-size: 20px;
      color: #F7CA18;
      background-color: rgba(90,90,90,0.5);
    }
    #userform .nav-tabs.nav-justified > .active > a, #userform .nav-tabs.nav-justified > .active > a:hover, #userform .nav-tabs.nav-justified > .active > a:focus {
      border: 0;
      background: #F7CA18;
      color: white;
      border-radius: 0;
    }
    #userform .nav-tabs > li > a {
      border: 0px solid transparent;
      border-radius: 0
    }
    #userform .nav-tabs.nav-justified > li > a:hover {
      background: #F7CA18;
      color: #FFF;
      border-radius: 0;
      border: 0;
      -webkit-transition: all .6s;
      -moz-transition: all .6s;
      transition: all .6s;
    }
    
    #userform .nav-tabs {
      border-bottom: 0px solid #ddd;
    }
    #userform .tab-pane h2 {
      margin: 10px 0;
      color: #FFF;
    }
    #userform .tab-pane p.lead {
      margin-top: 20px;
    }
    #userform .tab-content {
      padding: 20px
    }
    #userform .form-group {
      margin-bottom: 0px;
      color: #FFF;
    }
    .mrgn-30-top {
      margin-top: 30px
    }
    
  </style>
<script type="text/javascript">
	$(document).ready(function() {
		$("#signup").validate();
	})
</script>
</head>
<body>
<!-- partial:index.partial.html -->
<html lang="en">
<head>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  </head>

<body>
<div id="form">
  <div class="container">
    <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-md-8 col-md-offset-2" style="margin-top: 10%;">
      <div id="userform">
        <? 
			$auth = Zend_Auth::getInstance()->getIdentity(); ?>
        <ul class="nav nav-tabs nav-justified" role="tablist">
          <li class="active"><a href="#signup"  role="tab" data-toggle="tab">Pendaftaran</a></li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane fade active in">
            <form id="signup" name="compose" method="post" action="" enctype="multipart/form-data">
              <div class="form-group">
                  <label> Nama Lengkap </label>
                  <input type="text" class="form-control" id="name" name="name" required data-validation-required-message="Harap isi nama lengkap anda terlebih dahulu." autocomplete="off" placeholder="Nama">
                  <p class="help-block text-danger"></p>
              </div>

              <div class="form-group">
                  <label> Email </label>
                  <input type="email" class="form-control" id="email" name="email" required data-validation-required-message="Harap isi email anda terlebih dahulu." autocomplete="off" placeholder="E-mail">
                  <p class="help-block text-danger"></p>
              </div>

              <div class="form-group">
                  <label> Kontak </label>
                  <input type="text" class="form-control" id="kontak" name="kontak" required data-validation-required-message="Harap isi nomor telepon anda terlebih dahulu." autocomplete="off" placeholder="Nomor Handphone">
                  <p class="help-block text-danger"></p>
              </div>
              <div class="mrgn-30-top">
              <button type="submit" class="btn btn-larger btn-block"/>
                DAFTAR
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /.container --> 
</div>

</body>
</html>
