<script id="js">
$(function(){
	$("table")
		.tablesorter({theme: 'blue', widthFixed: true, widgets: ['zebra', 'filter']})
		.tablesorterPager({container: $(".pager"), 
			output: '{startRow} - {endRow} / {filteredRows} ({totalRows})', 
			fixedHeight: true, 
			removeRows: false, 
			cssGoto: '.gotoPage' 
		});
});
</script>

<div class="content-header"></div>
	<div class="UI_Header_Title">
		<h1><?=$this->avatar;?> Daftar Forum</h1>
		
		<div class="header_nav_links"><span class="right context_menu"><a href="/admin/forum-diskusi/add" class="UIlink-button small right">Tambah Forum Diskusi</a></span>
	</div>
</div>
<div class="clear"></div>
<br>

<? if (count($this->rows) > 0) { ?>
	<?=$this->pager;?>

	<table class="tablesorter">
		 <thead>
			 <tr>
			 	<th width="5px" align="center">No.</th>
				<th align="center">Title</th>
				<th align="center">Aksi</th>
			</tr>
		</thead>
		<tbody>
			<?php
			$index = 1;
			foreach($this->rows as $row)
			{
				echo '<tr>';
				echo '<td align="center">'. $index++ .'.</td>';
				echo '<td align="center">'. $row->title .'</td>';
				echo '<td align="center"><a href="/admin/forum-diskusi/reply/id/'. $row->id .'">REPLY</a> &nbsp;|&nbsp <a href="/admin/forum-diskusi/edit/id/'. $row->id .'">EDIT</a>';
				if ($this->getRole() == 'admin' || $this->getRole() == 'super') {
					echo '&nbsp;|&nbsp;<a href="/admin/forum-diskusi/delete/id/'. $row->id .'" onclick="return confirmDelete();">DELETE</a>';
				}
				echo '</td>';
				echo '</tr>';
			}
			?>
		</tbody>
	</table>
<? } else {
	echo 'Data tidak ditemukan.';
}
?>