<link rel="stylesheet" href="https://berkas.dpr.go.id/mooc/assets/css/belajar-pelatihan-saya.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.6/dist/sweetalert2.min.css" />
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.6/dist/sweetalert2.min.js"></script>

<!-- sidebar -->
<div class="area"></div>
    <nav class="main-menu " style="max-width: 100vw; margin-top: 85px;  ">
        <div id="mySidebar" class="sidebar background-content" style=" z-index: 999;  margin-top: 85px; overflow-y: auto; max-height: calc(100vh - 85px); background-color: #E5E7E9;">
            <a style="color: #D4A216;" href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
            <div class="p-3">
                <p class="fs-5">Table of Contents</p>
                <hr>
                <?php
                
                $progress = explode("-", $this->progress->status_progress);
                
                ?>
                <a <?= ($progress[0] == 'Pretest' ? ' style="pointer-events: none; cursor: default;" ' : '') ?> href="/peserta/pelatihan-saya/pretest/id/<?= $this->batch->id ?>">Pretest<br><i class="bi bi-check-circle-fill text-success"></i> Selesai
                </a>
                <hr>
                
                <div>
                    <?php
                    $batas_waktu = (int)$this->get_materi['batas_waktu']*60; 
                    $progress = explode("-", $this->progress->status_progress);
                    $count_silabus = 0;
                    $next_silabus = 1;
                    $next_materi = 1;

                    foreach ($this->silabus as $key => $silabus) {



                        $count_silabus++;
                        echo '<ul  style="margin-left: -35px; '. (($key + 1) == (int) $progress[1] ? 'color: #D4A216;' : '') .' ">';
                        echo ' <a class=" collapsed dropdown-toggle" type="button" data-bs-toggle="collapse"
                                    data-bs-target="#a' . $silabus->id . '" aria-expanded="false" aria-controls="collapseExample">' . $silabus->nama_silabus . ' </a>';
                        echo '</ul>';

                        echo ' <div class="collapse" id="a' . $silabus->id . '" >';
                        echo '<ul >';

                        $i = 0;
                        foreach ($this->materi as $idx => $materi) {
                            if ($materi->id_silabus == $silabus->id) {
                                if($this->get_materi->id == $materi->id && $this->get_materi->id_silabus == $materi->id_silabus){
                                    $next_materi = 0;
                                } else if ($next_materi == 0){
                                    $next_silabus = $key + 1;
                                    $next_materi = $i + 1;
                                }
                                // echo var_dump($progress[0],$this->progress->status_progress);
                                echo '<li>
                                            <a    ' . (($key + 1) > (int) $progress[1] && $progress[0] != 'Postest' && $progress[0] != 'Mentoring' && $progress[0] != 'Penugasan' && $progress[0] != 'Penilaian' && $progress[0] != 'Sertifikat' ? 'disabled="disabled" class="disabled"' : '') . 'style="margin-left: -42px;" href="/peserta/pelatihan-saya/belajar/id/' . $this->batch->id . '/silabus/' . ($key + 1) . '/materi/' . ++$i . '">' . $materi->nama_materi . '' . (($key + 1) > (int) $progress[1] && $progress[0] != 'Postest' && $progress[0] != 'Mentoring' && $progress[0] != 'Penugasan' && $progress[0] != 'Penilaian' && $progress[0] != 'Sertifikat'  ? '<i class="bi bi-lock-fill text-secondary"></i>' : '') . '
                                            ' . (($key + 1) < (int) $progress[1] ? '<br><i class="bi bi-check-circle-fill text-success"></i> Selesai</a>' : '') . '
                                            ' . (($key + 1) == (int) $progress[1] && $i < (int) $progress[2] || $progress[0] == 'Postest' || $progress[0] == 'Mentoring' || $progress[0] == 'Penugasan' || $progress[0] == 'Penilaian' || $progress[0] == 'Sertifikat' ? '<br><i class="bi bi-check-circle-fill text-success"></i> Selesai</a>' : '') . '
                                    </li>';
                            }

                            if ($progress[1] == ($key + 1)) {
                                $count_materi = $i;
                            }
                        }


                        echo '</ul>';
                        echo '</div>';
                    }

                    $next_url = '';
                    if($next_materi == 0){
                        $next_url = '/peserta/pelatihan-saya/mentoring/id/' . $this->batch->id;
                    } else {
                        $next_url = '/peserta/pelatihan-saya/belajar/id/' . $this->batch->id . '/silabus/' . $next_silabus . '/materi/' . $next_materi;
                    }

                    if ($progress[2] == $count_materi) {
                        $progress[1] = (int) $progress[1] + 1;
                        $progress[2] = 1;
                    } else {
                        $progress[2] = (int) $progress[2] + 1;
                    }

                    $url = '/peserta/pelatihan-saya/belajar/id/' . $this->batch->id . '/silabus/' . $progress[1] . '/materi/' . $progress[2];

                    if ((int) $progress[1] > $count_silabus) {
                        $url = '/peserta/pelatihan-saya/postest/id/' . $this->batch->id;
                        $progress[1] = 'postest';
                    }

                    ?>
                </div>

                <hr>
                <a <?= ($progress[0] == 'Pretest' || $progress[0] == 'Materi' ? 'disabled="disabled" class="disabled"' : '') ?> href="/peserta/pelatihan-saya/postest/id/<?= $this->batch->id; ?>">
                
                Postest
                
                <?= ($progress[0] == 'Pretest' || $progress[0] == 'Materi' ? '<i class="bi bi-lock-fill text-secondary"></i>' : '') ?>
                <?=  ($progress[0] == 'Mentoring' || $progress[0] == 'Penugasan' || $progress[0] == 'Penilaian' || $progress[0] == 'Sertifikat' ? '<br><i class="bi bi-check-circle-fill text-success"></i> Selesai' : '') ?>
                </a>
                
                <?php
            // Cek apakah $this->pelatihan->tipe_pelatihan adalah "nonclassical"
                if ($this->pelatihan->tipe_pelatihan == "nonclassical") {
                    echo "<hr>";
                    echo '<a ';
                    echo ($progress[0] == 'Materi' || $progress[0] == 'Pretest' || $progress[0] == 'Postest' ? 'disabled="disabled" class="disabled"' : '');
                    echo ' href="/peserta/pelatihan-saya/mentoring/id/' . $this->batch->id . '">';
                    echo 'Mentoring';
                    echo ($progress[0] == 'Materi' || $progress[0] == 'Pretest' || $progress[0] == 'Postest' ? '<i class="bi bi-lock-fill text-secondary"></i>' : '');
                    echo ($progress[0] == 'Penugasan' || $progress[0] == 'Penilaian' || $progress[0] == 'Sertifikat' ? '<br><i class="bi bi-check-circle-fill text-success"></i> Selesai' : '');
                    echo '</a>';
                }
                ?>

               
                <hr>
                <a <?= ($progress[0] == 'Materi' || $progress[0] == 'Pretest' || $progress[0] == 'Postest' || $progress[0] == 'Mentoring' ? 'disabled="disabled" class="disabled"' : '') ?> href="/peserta/pelatihan-saya/penugasan/id/<?= $this->batch->id ?>">
                
                Tugas Akhir
                
                <?= ($progress[0] == 'Materi'  || $progress[0] == 'Postest' || $progress[0] == 'Mentoring' || $progress[0] == 'Pretest' ? '<i class="bi bi-lock-fill text-secondary"></i>' : '') ?>
                <?=  ($progress[0] == 'Penilaian' || $progress[0] == 'Sertifikat' ? '<br><i class="bi bi-check-circle-fill text-success"></i> Selesai' : '') ?>
                </a>
                
                <hr>
                <a <?= ($progress[0] !== 'Sertifikat' ? 'disabled="disabled" class="disabled"' : '') ?> href="/peserta/pelatihan-saya/sertifikat/id/<?= $this->batch->id ?>">Sertifikat
                <?= ($progress[0] !== 'Sertifikat' ? '<i class="bi bi-lock-fill text-secondary"></i>' : '') ?>
                <?=  ($progress[0] == 'Sertifikat' ? '<br><i class="bi bi-check-circle-fill text-success"></i> Selesai' : '') ?>
                </a>
                <hr>
                <div style="text-align: center;">
                    <button class=" btn btn-outline-danger" onclick="menyerahClicked()"><i class="bi bi-x-circle"></i> Menyerah</button>
                </div>
                <hr>
            </div>
        </div>

        <div id="main">
            <button class="openbtn background-content" id="nav-icon" onclick="toggleNav()" style="z-index: 2; position: fixed; margin-left: -23px; display: flex;
            justify-content: center; align-items: center; color: #D4A216; background-color: #E5E7E9; font-size: 41px; padding: 10px 0px 15px 0;"> &#8250;</button>

        <div class="row content-header mb-3">
            <div class="col-1"></div>
            <div class="sub-content-header col-10">
                <div class="card rounded-4 background-content" style="border:none; background-color: #E5E7E9; box-shadow: 2.0px 4.0px 4.0px hsl(0deg 0% 0% / 0.38); ">
                    <div class="card-body" style=" color: #808080; ">
                        <a class="text-decoration-none" href="/peserta" style="color: #808080;">Belajar Saya</a>&nbsp &nbsp|&nbsp &nbsp
                        <a class="text-decoration-none" href="/peserta/pelatihan" style="color: #808080;">Pelatihan</a>&nbsp &nbsp|&nbsp &nbsp
                        <a class="text-decoration-none" style="color: #808080;" href="/peserta/pelatihan-saya/belajar/id/<?= $this->batch->id ?>/silabus/1/materi/1"><?= $this->pelatihan->nama_pelatihan; ?></a>&nbsp &nbsp|&nbsp &nbsp
                        <a class="text-dark text-decoration-none" ><?= $this->get_materi->nama_materi; ?></a>
                    </div>
                </div>
            </div>
            <div class=" col-1"></div>
        </div>

        <div class="row container-read-timer" style="margin-top: 10px; margin-bottom: 30px;">
            <div class="col-1"></div>
            <div class="col-10 content-read-timer">
                <div class="card rounded-4 background-content" style=" border:none; background-color: #E5E7E9; box-shadow: 2.0px 4.0px 4.0px hsl(0deg 0% 0% / 0.38);">
                    <div class="card-body">
                        <div id="timer" class="text-end" style="width: 100%;">Waktu Baca :</div>
                        <?= '<p class="fs-3">' . $this->get_materi['nama_materi'] . '</p>'; ?>
                        <? $this->get_materi['batas_waktu'] ?>
                    </div>
                </div>
            </div>
            <div class="col-1"></div>
        </div>

        <div class="row container-materi" style="margin-top: 10px; ">
            <div class="col-1"></div>
            <div class="col-10 content-materi">
                <div class="card rounded-4 border-0" style="overflow: hidden; box-shadow: 2.0px 4.0px 4.0px hsl(0deg 0% 0% / 0.38);">
                    <div class="card-body background-content" style="width: 100%; background-color: #E5E7E9;">
                        <?php
                            if ($this->get_materi['gambar_materi_uri'] == "") {
                                echo '';

                            } else {
                                echo '<div  style="margin:5px; text-align:center;"><img style="position: relative; display: inline; max-width: 35%;" src="https://berkas.dpr.go.id/mooc/gambarmateri/' . $this->get_materi['gambar_materi_uri'] . '"  /></div>';

                            }

                            if ($this->get_materi['document_materi_uri'] == "") {
                                echo '';

                            } else {
                                echo'<div style=" margin:5px; text-align:center;">
                                        <a href="https://berkas.dpr.go.id/mooc/filemateri/' . $this->get_materi['document_materi_uri'] . '" target="_blank" download><button class="btn btn-danger ">Download File</button></a>
                                </div>';
                            }


                            if ($this->get_materi['audio_materi_uri'] == "") {
                                echo '';

                            } else {
                                echo '<div style="margin:5px; text-align:center;"><audio style="position: relative; display: inline; max-width: 100%;" src="https://berkas.dpr.go.id/mooc/filemateri/' . $this->get_materi['audio_materi_uri'] . '" controls></audio></div>';
                            }

                            if ($this->get_materi['video_materi_uri'] == "") {
                                echo '';

                            } else {
                                echo '<div style="margin:5px; "><video controls style=" border-radius: 13px; position:relative; width: 100%;">
                                <source src="https://berkas.dpr.go.id/mooc/filemateri/' . $this->get_materi['video_materi_uri'] . '" type="video/mp4">
                                Your browser does not support the video tag.
                                </video> </div>';

                            }

                            if ($this->get_materi['isi_materi'] == "") {
                                echo '';

                            } else {
                                echo '<div style="margin:5px; ">';
                                echo $this->get_materi['isi_materi'];
                                echo '</div>';
                            }
                        ?>
                    </div>
                </div>
            </div>
            <div class="col-1"></div>
        </div>

        <div class="row container-btn-next" style="margin-top: 30px;">
            <div class="col-1"></div>
            <div class="col-10 content-btn-next">
                <div class="card rounded-4 border-0" style="overflow: hidden; box-shadow: 2.0px 4.0px 4.0px hsl(0deg 0% 0% / 0.38);">
                    <div class="card-body background-content" style="background-color: #E5E7E9;">
                        <div class="row d-flex flex-row align-items-center">
                            <?= ($progress[0] == 'Materi' ? 
                                '<div class="col-md-6 title-next d-flex justify-content-center align-items-center text-center">
                                    <p class="fs-3">Apakah Anda Sudah Memahami?</p>
                                    <p id="nextBtn" class="hidden"></p>
                                </div>

                                <div class="col-md-6 btn-next text-end">
                                    <button type="submit" class="btn" id="myBtn" disabled>
                                        <i class="bi bi-check-circle-fill"></i> &nbsp; &nbsp; Ya, Saya Sudah Paham.
                                    </button>
                                </div>' :
                                
                                '<div class="col-md-6 title-next d-flex justify-content-center align-items-center text-center">
                                    <p class="fs-3 m-0"">Hai, kita berjumpa lagi &nbsp;&nbsp;</p>
                                    <p id="myBtn" class="hidden" ></p>
                                </div>

                                <div class="col-md-6 btn-next text-end">
                                    <button type="submit" "id="nextBtn" class="btn border-0" style="color: #fff; background-color: #D4A216;">
                                        <i class="bi bi-box-arrow-in-right"></i> &nbsp; &nbsp; Selanjutnya
                                    </button>
                                </div>
                            ') ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-1"></div>
        </div>
    </nav>

<script>
    function menyerahClicked() {
        Swal.fire({
            title: 'Konfirmasi',
            text: 'Ketik "MENYERAH" (dengan huruf besar) untuk menyerah',
            input: 'text',
            showCancelButton: true,
            confirmButtonText: 'Submit',
            cancelButtonText: 'Batal',
            inputValidator: (value) => {
                if (value !== 'MENYERAH') {
                    return 'Tulisan tidak cocok';
                }
            }
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    url: '/peserta/pelatihan-saya/menyerah',
                    type: 'POST',
                    data: {
                        id: '<?=$this->progress->id?>',
                        id_peserta: '<?=$this->progress->id_peserta?>',
                        id_batch: '<?=$this->progress->id_batch?>',
                        status_progress: '<?=$this->progress->status_progress?>',
                        status_riwayat: 'Menyerah',
                        // status_progress: 'Menyerah',
                    },
                    success: function (response) {
                        window.location.href = '/peserta/riwayat';
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        console.log('Failed: ' + textStatus);
                        console.log(errorThrown);
                    }
                });
            }
        });
    }

    // timer baca
    const COUNTER_KEY = 'my-countdown';
    function countDown(i, callback) {
        timer = setInterval(function() {    
            minutes = parseInt(i / 60, 10);
            seconds = parseInt(i % 60, 10);
            minutes = minutes < 10 ? "0" + minutes : minutes;
            seconds = seconds < 10 ? "0" + seconds : seconds;

            document.getElementById("timer").innerHTML = "<span class='fw-bold text-danger'>Waktu Baca :</span> 00:" + minutes + ":" + seconds;

            if ((i--) > 0) {
                window.sessionStorage.setItem(COUNTER_KEY, i);
            } else {
                window.sessionStorage.removeItem(COUNTER_KEY);
                clearInterval(timer);
                callback();
            }
        }, 1000);
    }

    window.onload = function() {
        let countDownTime = window.sessionStorage.getItem(COUNTER_KEY) || <?= $batas_waktu ?>;
        countDown(countDownTime, function() {
            $("#myBtn").removeAttr("disabled");
        });
    };
        
    const next = document.getElementById('nextBtn');
    if(next) {
        next.addEventListener('click', function () {
            window.location.href = '<?= $next_url ?>';
        });
    }

    document.getElementById('myBtn').addEventListener('click', function () {
        Swal.fire({
            title: 'Mantap!',
            text: 'Pelatihan ini berhasil kamu selesaikan. Lanjut ke materi selanjutnya ya.',
            icon: 'success',
            showCancelButton: false,
            confirmButtonText: 'Oke!',
            confirmButtonColor: '#4CAF50',
        })
        .then(function (result) {
            if (result.isConfirmed) {
                $.ajax({
                    url: '/peserta/pelatihan-saya/belajar',
                    type: 'POST',
                    data: {
                        id_silabus: '<?= $progress[1] ?>',
                        id_materi: '<?= $progress[2] ?>',
                        id_progress: '<?= $this->progress->id ?>',
                    },
                    success: function (response) {
                            window.location.href = '<?= $url ?>';
                    }
                }).done(function (response) {
                    console.log(response);
                }).fail(function (jqXHR, textStatus, errorThrown) {
                    console.log('Failed: ' + textStatus);
                    console.log(errorThrown);
                });
            }
        });
    });
  
    //membuat button sidebar tetap ketika scroll
    window.onscroll = function () { scrollFunction() };

    function scrollFunction() {
        var button = document.getElementById("nav-icon");
        if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
            button.style.display = "flex";
        } else {
            button.style.display = "flex";
        }
    }

    function toggleNav() {
        var sidebar = document.getElementById("mySidebar");
        var navIcon = document.getElementById("nav-icon");

        if (window.innerWidth < 768) {
            if (sidebar.style.width == "100%") {
                sidebar.style.width = "0";
                navIcon.innerHTML = "&#8250;";
            } else {
                sidebar.style.width = "100%";
                navIcon.innerHTML = "&#8249;";
            }
        } else {
            if (sidebar.style.width == "250px") {
                sidebar.style.width = "0";
                document.getElementById("main").style.marginLeft = "0";
                navIcon.innerHTML = "&#8250;";
            } else {
                sidebar.style.width = "250px";
                document.getElementById("main").style.marginLeft = "250px";
                navIcon.innerHTML = "&#8249;";
            }
        }
    }
  
    function closeNav() {
        document.getElementById("mySidebar").style.width = "0";
        document.getElementById("main").style.marginLeft = "0";
    }
</script>
