<link rel="stylesheet" href="https://code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
    crossorigin="anonymous"></script>
<!-- <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script> -->
<style>
    .section-container {
        display: flex;
        justify-content: center;
        align-items: center;
        flex-wrap: wrap;

        /* height: 100%;  */
        /* Optional: Jika ingin konten berada di tengah secara vertikal */
    }

    .section-panduan {
        display: flex;
        justify-content: center;
        /* align-items: center; */
        flex-wrap: wrap;

        padding: 43px;
        /* height: 100%;  */
        /* Optional: Jika ingin konten berada di tengah secara vertikal */
    }

    .card {
        width: 150px;
        height: 100px;
        border-radius: 5px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.5);
        color: white;
        font-size: 12px;
        text-align: center;
        display: inline-block;
        margin: 10px;
        transition: transform 0.2s ease-in-out;
        /* Add a smooth transition */
    }


    .card1 {
        background: linear-gradient(135deg, #ff512f 0%, #dd2476 100%);
    }

    .card2 {
        background: linear-gradient(135deg, #08aeea 0%, #2af598 100%);
    }

    .card3 {
        background: linear-gradient(135deg, #eb3349 0%, #f45c43 100%);
    }

    .card4 {
        background: linear-gradient(135deg, #603813 0%, #b29f94 100%);
    }

    .card5 {
        background: linear-gradient(135deg, #4a90e2 0%, #1255a4 100%);
    }

    .card6 {
        background: linear-gradient(135deg, #ffcc00 0%, #ff9900 100%);
    }

    .card7 {
        background: linear-gradient(135deg, #2c3e50 0%, #34495e 100%);
    }

    .card8 {
        background: linear-gradient(135deg, #9b59b6 0%, #8e44ad 100%);
    }

    .card9 {
        background: linear-gradient(135deg, #27ae60 0%, #2ecc71 100%);
    }

    .card10 {
        background: linear-gradient(135deg, #e74c3c 0%, #c0392b 100%);
    }

    /* Add hover animation */
    .card:hover {
        transform: scale(1.1);
        /* Increase the card size on hover */
    }
</style>



<section class="section-container">
    <div class="card card5">
        <div class="card-body">
            <p class="card-title">Total Peserta</p>
            <h3 class="card-text" id="count-peserta">0</h3>
        </div>
    </div>

    <div class="card card5">
        <div class="card-body">
            <p class="card-title">Total Admin</p>
            <h3 class="card-text" id="count-admin">0</h3>
        </div>
    </div>

    <div class="card card5">
        <div class="card-body">
            <p class="card-title">Total Pengajar</p>
            <h3 class="card-text" id="count-pengajar">0</h3>
        </div>
    </div>

    <div class="card card5">
        <div class="card-body">
            <p class="card-title">Total Coach</p>
            <h3 class="card-text" id="count-coach">0</h3>
        </div>
    </div>
    <div class="card card5">
        <div class="card-body">
            <p class="card-title">Total Mentor</p>
            <h3 class="card-text" id="count-mentor">0</h3>
        </div>
    </div>
    <div class="card card5">
        <div class="card-body">
            <p class="card-title">Total Penguji</p>
            <h3 class="card-text" id="count-penguji">0</h3>
        </div>
    </div>
    <div class="card card7">
        <div class="card-body">
            <p class="card-title">Total Mata Pelatihan</p>
            <h3 class="card-text" id="count-mata-pelatihan">0</h3>
        </div>
    </div>
    <div class="card card7">
        <div class="card-body">
            <p class="card-title">Total Agenda</p>
            <h3 class="card-text" id="count-agenda">0</h3>
        </div>
    </div>
    <div class="card card7">
        <div class="card-body">
            <p class="card-title">Total Pelatihan</p>
            <h3 class="card-text" id="count-pelatihan">0</h3>
        </div>
    </div>
    <div class="card card7">
        <div class="card-body">
            <p class="card-title">Total Batch</p>
            <h3 class="card-text" id="count-batch">0</h3>
        </div>
    </div>
    <div class="card card9">
        <div class="card-body">
            <p class="card-title">Total Progress</p>
            <h3 class="card-text" id="count-progress">0</h3>
        </div>
    </div>
    <div class="card card9">
        <div class="card-body">
            <p class="card-title">Total Nontes</p>
            <h3 class="card-text" id="count-nontes">0</h3>
        </div>
    </div>
    <div class="card card9">
        <div class="card-body">
            <p class="card-title">Total Penugasan</p>
            <h3 class="card-text" id="count-penugasan">0</h3>
        </div>
    </div>
    <div class="card card9">
        <div class="card-body">
            <p class="card-title">Total Sertifikat</p>
            <h3 class="card-text" id="count-sertifikat">0</h3>
        </div>
    </div>
    <div class="card card9">
        <div class="card-body">
            <p class="card-title">Total Riwayat</p>
            <h3 class="card-text" id="count-riwayat">0</h3>
        </div>
    </div>

</section>

<section class="section-panduan">
    <style>
        .column {
            float: left;
            padding-bottom: 100px;
        }

        .portlet {
            margin: 0 1em 1em 0;
        }

        .portlet-header {
            margin: 0.3em;
            padding-bottom: 4px;
            padding-left: 0.2em;
        }

        .portlet-header .ui-icon {
            float: right;
        }

        .portlet-content {
            padding: 0.4em;
        }

        .ui-sortable-placeholder {
            border: 1px dotted black;
            visibility: visible !important;
            height: 50px !important;
        }

        .ui-sortable-placeholder * {
            visibility: hidden;
        }
    </style>

    <div class="column" style="width: 60%;">

        <div class="portlet">
            <div style="font-size:12px;" class="portlet-header">User Manual</div>
            <div class="portlet-content">
                <table width="100%">
                    <tr>
                        <td align="center"><a style="font-size:10px;"
                                href="https://berkas.dpr.go.id/mooc/assets/documents/Buku_Manual_SiCakap_Role_Admin.pdf"
                                target="_blank"><img style="width:100px;"
                                    src="<?= $this->url_statik; ?>/images/admin/mantel/pdf_icon.png"><br>Panduan
                                Penggunaan Untuk Admin</a></td>
                    </tr>
                </table>
            </div>
        </div>

    </div>

    <div class="column" style="width: 40%;">

        <div class="portlet">
            <div style="font-size:12px;" class="portlet-header">Notifikasi</div>
            <div class="portlet-content">

            </div>
        </div>

    </div>

    <script type="text/javascript">
        $(function () {
            $(".column").sortable({
                connectWith: ".column"
            });

            $(".portlet").addClass("ui-widget ui-widget-content ui-helper-clearfix ui-corner-all")
                .find(".portlet-header")
                .addClass("ui-widget-header ui-corner-all")
                .prepend("<span class='ui-icon ui-icon-minusthick'></span>")
                .end()
                .find(".portlet-content");

            $(".portlet-header .ui-icon").click(function () {
                $(this).toggleClass("ui-icon-minusthick").toggleClass("ui-icon-plusthick");
                $(this).parents(".portlet:first").find(".portlet-content").toggle();
            });

            $(".column").disableSelection();
        });
    </script>

</section>


<script>

    document.addEventListener('DOMContentLoaded', function () {

        // Function to animate the count-up
        function animateCountUp(targetElement, start, end, duration) {
            let current = start;
            const range = end - start;
            const increment = end > start ? 1 : -1;
            const stepTime = Math.abs(Math.floor(duration / range));
            const element = document.getElementById(targetElement);

            const timer = setInterval(() => {
                current += increment;
                element.innerText = current;
                if (current === end) {
                    clearInterval(timer);
                }
            }, stepTime);
        }


        // animateCountUp('count-peserta', 0, <?= count($this->peserta); ?>, 2000);
        // animateCountUp('count-admin', 0, <?= count($this->admin); ?>, 2000);
        // animateCountUp('count-pengajar', 0, <?= count($this->pengajar); ?>, 2000);
        // animateCountUp('count-coach', 0, <?= count($this->coach); ?>, 2000);
        // animateCountUp('count-mentor', 0, <?= count($this->mentor); ?>, 2000);
        // animateCountUp('count-penguji', 0, <?= count($this->penguji); ?>, 2000);

        // animateCountUp('count-mata-pelatihan', 0, <?= count($this->materisilabus); ?>, 2000);
        // animateCountUp('count-agenda', 0, <?= count($this->silabus); ?>, 2000);
        // animateCountUp('count-pelatihan', 0, <?= count($this->pelatihan); ?>, 2000);
        // animateCountUp('count-batch', 0, <?= count($this->batch); ?>, 2000);

        // animateCountUp('count-progress', 0, <?= count($this->progress); ?>, 2000);
        // animateCountUp('count-nontes', 0, <?= count($this->nontes); ?>, 2000);
        // animateCountUp('count-penugasan', 0, <?= count($this->penugasan); ?>, 2000);
        // animateCountUp('count-sertifikat', 0, <?= count($this->sertifikat); ?>, 2000);
        // animateCountUp('count-riwayat', 0, <?= count($this->riwayat); ?>, 2000);



        let pesertaCount = <?= count($this->peserta); ?>;
        let adminCount = <?= count($this->admin); ?>;
        let pengajarCount = <?= count($this->pengajar); ?>;
        let coachCount = <?= count($this->coach); ?>;
        let mentorCount = <?= count($this->mentor); ?>;
        let pengujiCount = <?= count($this->penguji); ?>;


        if (pesertaCount > 0) {
            animateCountUp('count-peserta', 0, pesertaCount, 2000);
        } else {
            document.getElementById('count-peserta').innerText = 0;
        }

        if (adminCount > 0) {
            animateCountUp('count-admin', 0, adminCount, 2000);
        } else {
            document.getElementById('count-admin').innerText = 0;
        }

        if (pengajarCount > 0) {
            animateCountUp('count-pengajar', 0, pengajarCount, 2000);
        } else {
            document.getElementById('count-pengajar').innerText = 0;
        }

        if (coachCount > 0) {
            animateCountUp('count-coach', 0, coachCount, 2000);
        } else {
            document.getElementById('count-coach').innerText = 0;
        }

        if (mentorCount > 0) {
            animateCountUp('count-mentor', 0, mentorCount, 2000);
        } else {
            innerText = 0
        }

        if (pengujiCount > 0) {
            animateCountUp('count-penguji', 0, pengujiCount, 2000);
        } else {
            document.getElementById('count-penguji').innerText = 0;
        }


        let materisilabusCount = <?= count($this->materisilabus); ?>;
        let agendaCount = <?= count($this->silabus); ?>;
        let pelatihanCount = <?= count($this->pelatihan); ?>;
        let batchCount = <?= count($this->batch); ?>;

        if (materisilabusCount > 0) {
            animateCountUp('count-mata-pelatihan', 0, materisilabusCount, 2000);
        } else {
            document.getElementById('count-mata-pelatihan').innerText = 0;
        }

        if (agendaCount > 0) {
            animateCountUp('count-agenda', 0, agendaCount, 2000);
        } else {
            document.getElementById('count-agenda').innerText = 0;
        }

        if (pelatihanCount > 0) {
            animateCountUp('count-pelatihan', 0, pelatihanCount, 2000);
        } else {
            document.getElementById('count-pelatihan').innerText = 0;
        }
        
        if (batchCount > 0) {
            animateCountUp('count-batch', 0, batchCount, 2000);
        } else {
            document.getElementById('count-batch').innerText = 0;
        }
        
        let progressCount = <?= count($this->progress); ?>;
        let nontesCount = <?= count($this->nontes); ?>;
        let penugasanCount = <?= count($this->penugasan); ?>;
        let sertifikatCount = <?= count($this->sertifikat); ?>;
        let riwayatCount = <?= count($this->riwayat); ?>;

        if (progressCount > 0) {
            animateCountUp('count-progress', 0, progressCount, 2000);
        } else {
            document.getElementById('count-progress').innerText = 0;
        }
        
        if (nontesCount > 0) {
            animateCountUp('count-nontes', 0, nontesCount, 2000);
        } else {
            document.getElementById('count-nontes').innerText = 0;
        }
        
        if (penugasanCount > 0) {
            animateCountUp('count-penugasan', 0, penugasanCount, 2000);
        } else {
            document.getElementById('count-penugasan').innerText = 0;
        }
        
        if (sertifikatCount > 0) {
            animateCountUp('count-sertifikat', 0, sertifikatCount, 2000);
        } else {
            document.getElementById('count-sertifikat').innerText = 0;
        }
        
        if (riwayatCount > 0) {
            animateCountUp('count-riwayat', 0, riwayatCount, 2000);
        } else {
            document.getElementById('count-riwayat').innerText = 0;
        }
        
    });
</script>