<section class="container-tentang mb-5 d-flex flex-column justify-content-evenly p-3" style="padding-top: 150px !important; max-width: 100vw;">
    <p class="fs-2 fw-bold text-center">PANDUAN</p>
    <p class="fs-5 fw-bold text-center">Panduan Penggunaan Untuk Peserta</p>
    <div style="text-align: center; " >
        <embed src="https://berkas.dpr.go.id/mooc/assets/documents/Buku_Manual_SiCakap_Role_Pengguna.pdf" width="80%" type="application/pdf" style="height: 500px; box-shadow: 5px 5px 15px rgba(0, 0, 0, 0.2);"">
    </div>
</section>