<script type="text/javascript">
	$(document).ready(function() {
		$("#compose").validate();
	})

	function selectFields1(id, id, nama_pelatihan) {
		$('#id_pelatihan').val(id);
		$('#nama_pelatihan').val(nama_pelatihan);
		$.facebox.close();
	}

	function ClearFields1() {
		document.getElementById("id_pelatihan").value = "";
		document.getElementById("nama_pelatihan").value = "";
	}

	// function selectFields2(id, id, nama) {
	// 	$('#id_peserta').val(id);
	// 	$('#nama_peserta').val(nama);
	// 	$.facebox.close();
	// }

	// function ClearFields2() {
	// 	document.getElementById("id_peserta").value = "";
	// 	document.getElementById("nama").value = "";
	// }
	
</script>


<div class="content-header"></div>
<div class="UI_Header_Title">
	<h1><?=$this->avatar;?>Tambah Nontes</h1>
	<div class="header_nav_links"><a href="/admin/pelatihan/edit/id/<?= $this->pelatihan->id ?>">Kembali ke Pelatihan <?= $this->pelatihan->nama_pelatihan ?></a></div>
</div>
<div class="clear"></div>
<form id="compose" name="compose" method="post" action="" enctype="multipart/form-data">
	<div class="tabular">
		<p><label>Pelatihan</label>
			<input readonly type="text" id="nama_pelatihan" autocomplete="disable" name="nama_pelatihan" style="height:30px;  width: 400px;padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;" value="<?= $this->pelatihan->nama_pelatihan ?>" />
			<input type="hidden" id="id_pelatihan" autocomplete="disable" name="id_pelatihan" value="<?= $this->pelatihan->id ?>" />
			<input type="button" value="..." id="btnpelatihan" style="height:30px;" onclick="jQuery.facebox({ ajax: '/admin/nontes/search-pelatihan'});">
			<input type="button" style="height:30px;" onclick="ClearFields1();" value="Clear">
			<font color="red">*</font>
		</p>
		<!-- <p id="daftar-peserta" class="daftar-user">
			<label>Nama Peserta</label>
			<input readonly type="text" id="nama_peserta" autocomplete="disable" name="nama" style="height:30px; padding: 0px; padding-left: 10px; width: 400px; border: 1px solid grey; border-radius: 2px;" />
			<input type="button" value="..." id="btnpeserta" style="height:30px;" onclick="jQuery.facebox({ ajax: '/admin/nontes/search-peserta/'});">
			<input type="hidden" id="id_peserta" autocomplete="disable" name="id_peserta" />
			<input type="button" style="height:30px;" onclick="ClearFields2();" value="Clear">
			<font color="red">*</font>
		</p> -->
		<p>
			<label class="left" for="title">Isi Nontes</label>
			<input type="text" id="title" class="event-message" wrap="soft" name="title" style="width: 450px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;">
			<font color="red">*</font>
		</p>

		<p>
			<label class="left" for="file_nontes">File Nontes</label>
			<input type="file" id="file_nontes" class="event-message" wrap="soft" name="file_nontes" style="width: 180px; height:30px; padding: 0px; border-radius: 2px;">
			<font color="red">*</font>
		</p>

		<p class="savecancel"><label class="UIbutton-small"><input type="submit" value="Simpan" class=""/></label><a href="/admin/pelatihan/edit/id/<?= $this->pelatihan->id?>" class="UIbutton-small">Batal</a></p>
	</div>
</form>
<div style="clear:both"></div>



<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.13.0/jquery-ui.min.js"></script>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ui-timepicker-addon/1.6.3/jquery-ui-timepicker-addon.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-ui-timepicker-addon/1.6.3/jquery-ui-timepicker-addon.min.css">

<script src="https://cdnjs.cloudflare.com/ajax/libs/facebox/1.3/facebox.min.js" integrity="sha512-DafgdU2HdE6zzOrLOWGtLs9EeirqW76V1aLoyzTC+eriqIfX+FdwVFwvex+k3C2h1jafDa5nFVe7/qq7GWpT7w==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.hoverintent/1.10.2/jquery.hoverIntent.min.js" integrity="sha512-sw+oNcbTS/A0W2RCoTKChyNVw/OClp76mxn3yaOZiDaxpGMXFIWrZC6BlgtieaWp2oh2asgj44TJd1f4Lz2C8Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js" integrity="sha512-rstIgDs0xPgmG6RX1Aba4KV5cWJbAMcvRCVmglpam9SoHZiUCyQVDdH2LPlxoHtrv17XWblE/V/PP+Tr04hbtA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.3/js/jquery.tablesorter.min.js" integrity="sha512-qzgd5cYSZcosqpzpn7zF2ZId8f/8CHmFKZ8j7mU4OUXTNRd5g+ZHBPsgKEwoqxCtdQvExE5LprwwPAgoicguNg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.3/js/extras/jquery.tablesorter.pager.min.js" integrity="sha512-y845ijdup9lDunrcSRQAlFdQICHVhkB5UNguWRX8A3L+guxO7Oow0poojw0PLckhcKij++h85bnyro80fjR9+A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>




<script>
  $(function() {
    $("#deadline_tanggal").datepicker({
      yearRange: "-1:+5",
      changeYear: true,
      changeMonth: true,
      dateFormat: "yy-mm-dd",
    });

    $("#deadline_waktu").timepicker({
      timeFormat: "HH:mm",
    });
  });

</script>




