<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Prasmanan Learning</title>
  <!-- bootstrap -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

  
  <!-- bootstrap icon -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
  <link rel="shortcut icon" type="image/x-icon" href="https://berkas.dpr.go.id/mooc/favicon.ico" />

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.6/dist/sweetalert2.min.css" />
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.6/dist/sweetalert2.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
  <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">

  <!-- CSS -->
  <link rel="stylesheet" href="https://berkas.dpr.go.id/mooc/assets/css/layout-default.css">
  <link rel="stylesheet" href="https://berkas.dpr.go.id/mooc/assets/css/darkmode.css">
</head>

<?php
  // $auth = Zend_Auth::getInstance()->getIdentity();
  // $peran = $auth->peran;
  // $username = $auth->nama;
  // print_r($auth);
  // $session = new Zend_Session_Namespace('loggedInUser');
  // $auth_non_asn = $session->user;
  // print_r($auth_non_asn);

  $session = new Zend_Session_Namespace('loggedInUser');
  $auth = $session->user;
  $user_log = isset($auth->username) ? $auth->username : $auth = Zend_Auth::getInstance()->getIdentity();

  $this->BatchService = new BatchService();
  $batchs = $this->BatchService->getAllDataByPelatihan();

?>

<body>
  <!-- navbar -->
  <?
    if (!($auth->id)) {
      // navbar auth
      echo'<nav class="navbar navbar-expand-lg background-content fixed-top" style="max-width: 100vw; background-color: #E5E7E9; box-shadow: 2.0px 4.0px 4.0px hsl(0deg 0% 0% / 0.38); z-index: 100">
              <div class="container-fluid background-content" style="background-color: #E5E7E9">
                <a href="/default/index/" class="mooc navbar-brand text-center mx-3" style="width: 200px;" href="/home/home/index">
                  <img src="https://berkas.dpr.go.id/mooc/assets/images/mooc.png" alt="MOOC">
                </a>
                <br><br><br>
                  
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                  
                <div id="navbarSupportedContent" class="collapse navbar-collapse" style="max-width: 100vw">
                  <ul class="navbar-nav mb-lg-0 d-flex justify-content-between me-5 my-navbar" style="width: 80%;">
                    <form class="nav-item d-flex search-form" style="min-width: 20vw; height: 100%" role="search">
                      <div class="box" style="width: 3em;">
                        <form name="search">
                          <input type="text" id="search-input" class="input" name="txt" placeholder="Cari disini..." autocomplete="off">
                          <i class="bi bi-search" style="font-size: 25px; left: 0.7em;"></i>
                        </form>
                      </div>
                    </form>
                    <div id="search-navbar" class="search-navbar background-content position-fixed flex flex-column rounded-3 p-2" style="min-width: 18.5vw; display: none; z-index: 999; top: 70px; background: white;">
                      
                    </div>

                    <div class="dropdown-animation"> 
                      <a href="/peserta/index" class="btn-have-login text-decoration-none text-dark">KELAS</a>
                    </div>
                
                    <div  class=" dropdown-animation div-text">KEGIATAN
                      <ul class=" p-3 background-content dropdown-animation-menu">
                        <hr>
                        <li class="m-3"><a class="m-0" href="#">Seminar</a></li>
                        <hr>
                        <li class="m-3"><a class="m-0" href="#">Webinar</a></li>
                        <hr>
                        <li class="m-3"><a class="m-0" href="#">Workshop</a></li>
                        <hr>
                        <li class="m-3"><a class="m-0" href="#">Forum Grup Discussion</a></li>
                        <hr>
                        <li class="m-3"><a class="m-0" href="#">Character Building & Teamwork</a></li>
                        <hr>
                      </ul>
                    </div>

                    <div class="dropdown-animation"> 
                      <a href="/default/panduan" class="text-decoration-none text-dark">PANDUAN</a>
                    </div>
                  
                    <div class="dropdown-animation div-text">BANTUAN
                      <ul class=" p-3 background-content dropdown-animation-menu">
                      <hr>
                      <li class="m-3"><a class="m-0" href="/default/faq">FAQ</a></li>
                      <hr>
                      <li class="m-3"><a class="m-0" href="/default/about-us">Tentang Kami</a></li>
                      <hr>
                      <li class="m-3"><a class="m-0" href="/default/contact-us">Hubungi Kami</a></li>
                      <hr>
                      <li class="m-3"><a class="m-0" href="/default/privacy-policy">Kebijakan Privasi</a></li>
                      <hr>
                      </ul>
                    </div>
                  </ul>
                  <br> 
              
                  <ul class="nav-item container-logreg m-0 d-flex flex-column text-end p-0" style="width: 20%;">
                    <li class="nav-item text-end mb-2 list-unstyled" style="width: 100%;">
                      <button type="button" class="btn fw-bold" style="width: 7em; border: 2px solid #D4A216; color: #D4A216;" type="submit" data-bs-toggle="modal" data-bs-target="#login">Masuk</button>
                    </li>
                  
                    <li class="nav-item text-end list-unstyled" style="width: 100%;">
                      <button type="button" class="btn text-light fw-bold" style="width: 7em; background-color: #D4A216" type="submit" data-bs-toggle="modal" data-bs-target="#daftar">Daftar</button>
                    </li>
                  </ul>
                  
                </div>
              </div>
          </nav>';
      // end navbar auth
    } else if (($auth->jenis_peserta == "NonASN")) {
      // navbar profile
      $this->PesertaService = new PesertaService();
      $peserta = $this->PesertaService->getData($auth->id_peserta);

      echo'<nav class="navbar navbar-expand-lg background-content fixed-top" style="max-width: 100vw; background-color: #E5E7E9; box-shadow: 2.0px 4.0px 4.0px hsl(0deg 0% 0% / 0.38); z-index: 100">
            <div class="container-fluid background-content" style="background-color: #E5E7E9">
              <a href="/default/index/" class="mooc navbar-brand text-center mx-3" style="width: 200px;">
                <img src="https://berkas.dpr.go.id/mooc/assets/images/mooc.png" alt="MOOC">
              </a>
              <br><br><br>
                
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
                
              <div class="collapse navbar-collapse" style="max-width: 100vw" id="navbarSupportedContent">
                <ul class="navbar-nav mb-lg-0 d-flex justify-content-between me-5 my-navbar" style="width: 80%;">
                  <form class="nav-item d-flex search-form" style="min-width: 20vw; height: 100%" role="search">
                    <div class="box" style="width: 3em;">
                      <form name="search">
                        <input type="text" id="search-input" class="input" name="txt" placeholder="Cari disini..." autocomplete="off">
                        <i class="bi bi-search" style="font-size: 25px; left: 0.7em;"></i>
                      </form>
                    </div>
                  </form>
                  <div id="search-navbar" class="search-navbar background-content position-fixed flex flex-column rounded-3 p-2" style="min-width: 18.5vw; display: none; z-index: 999; top: 70px; background: white;">
                    
                  </div>

                  <div class="dropdown-animation"> 
                    <a href="/pesertanonasn/index" class="text-decoration-none text-dark">KELAS</a>
                  </div>
            
                  <div  class=" dropdown-animation div-text">KEGIATAN
                    <ul class=" p-3 background-content dropdown-animation-menu">
                      <hr>
                      <li class="m-3"><a class="m-0" href="#">Seminar</a></li>
                      <hr>
                      <li class="m-3"><a class="m-0" href="#">Webinar</a></li>
                      <hr>
                      <li class="m-3"><a class="m-0" href="#">Workshop</a></li>
                      <hr>
                      <li class="m-3"><a class="m-0" href="#">Forum Grup Discussion</a></li>
                      <hr>
                      <li class="m-3"><a class="m-0" href="#">Character Building & Teamwork</a></li>
                      <hr>
                    </ul>
                  </div>

                  <div class="dropdown-animation"> 
                    <a href="/default/panduan" class="text-decoration-none text-dark">PANDUAN</a>
                  </div>
              
                  <div class="dropdown-animation div-text">BANTUAN
                    <ul class=" p-3 background-content dropdown-animation-menu">
                      <hr>
                      <li class="m-3"><a class="m-0" href="/default/faq">FAQ</a></li>
                      <hr>
                      <li class="m-3"><a class="m-0" href="/default/about-us">Tentang Kami</a></li>
                      <hr>
                      <li class="m-3"><a class="m-0" href="/default/contact-us">Hubungi Kami</a></li>
                      <hr>
                      <li class="m-3"><a class="m-0" href="/default/privacy-policy">Kebijakan Privasi</a></li>
                      <hr>
                    </ul>
                  </div>
                </ul>

                <ul class="nav-item container-profile d-flex flex-row align-items-center justify-content-end p-0 m-0" style="width: 20%;"> 
                  <li class="btn-group list-unstyled d-flex justify-content-center align-items-center position-relative">
                    <button type="button" class="background-content btn d-flex justify-content-center align-items-center rounded-circle" style="width: 40px; height: 40px; background-color: #E5E7E9; box-shadow: 2.0px 4.0px 4.0px hsl(0deg 0% 0% / 0.38);" data-bs-toggle="dropdown" aria-expanded="false">';
                      if($peserta->fotopesertanonasn_uri != "") {
                        echo'<img src="https://berkas.dpr.go.id/mooc/fotopesertanonasn/'.$peserta->fotopesertanonasn_uri.'" alt="'. $peserta->nama .'" class="rounded-circle" style="width: 40px; height: 40px;">';
                      } else {
                        echo'<img src="https://berkas.dpr.go.id/mooc/assets/images/username-orange.png" alt="default-photo" class="rounded-circle" style="width: 30px; height: 30px;">';
                      }
                    echo '</button>
                            
                    <ul class="dropdown-menu position-absolute background-content" style="left: -200px; z-index: 99999999999; margin-top: 14px; padding: 10px; min-width: 300px;">
                      <li class="text-center"> <p class="fs-4">' . $peserta->nama . '</p></li>
                      <li class="text-center"><a class="dropdown-item btn border" href="/pesertanonasn/profile/index/id/' . $auth->id_peserta . '">View Profile</a></li>
                      <!--<div class="dropdown-divider"></div>
                      <li><a class="dropdown-item" href="#"><i class="bi bi-gear"></i> Setting</a></li> -->
                      <div class="dropdown-divider"></div>
                      <li><a class="dropdown-item" href="/loginselainasn/logout"><i class="bi bi-box-arrow-right"></i> Logout</a></li>
                    </ul>
                  </li>
                      
                  <li class="list-unstyled d-flex justify-content-center align-items-center" style="width: 50px;">
                    <button type="button" class="background-content btn position-relative d-flex justify-content-center align-items-center rounded-circle" style="width: 40px; height: 40px; background-color: #E5E7E9;">
                      <img src="https://berkas.dpr.go.id/mooc/assets/images/bell.png" alt="" class="rounded-circle position-absolute" style="width: 25px; height: 25px;">
                      <span class="position-absolute m-0 bg-danger rounded-circle" style="width: 10px; height: 10px; right: 3px; top: 3px;"></span>
                    </button>
                  </li>
                </ul>

              </div>
            </div>
          </nav>';
          // end profile
    } else {
      // navbar profile
      $this->PesertaService = new PesertaService();
      $peserta = $this->PesertaService->getData($auth->id_peserta);

      echo'<nav class="navbar navbar-expand-lg background-content fixed-top" style="max-width: 100vw; background-color: #E5E7E9; box-shadow: 2.0px 4.0px 4.0px hsl(0deg 0% 0% / 0.38); z-index: 100">
            <div class="container-fluid background-content" style="background-color: #E5E7E9">
              <a href="/default/index/" class="mooc navbar-brand text-center mx-3" style="width: 200px;">
                <img src="https://berkas.dpr.go.id/mooc/assets/images/mooc.png" alt="MOOC">
              </a>
              <br><br><br>
                
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
                
              <div class="collapse navbar-collapse" style="max-width: 100vw" id="navbarSupportedContent">
                <ul class="navbar-nav mb-lg-0 d-flex justify-content-between me-5 my-navbar" style="width: 80%;">
                  <form class="nav-item d-flex search-form" style="min-width: 20vw; height: 100%" role="search">
                    <div class="box" style="width: 3em;">
                      <form name="search">
                        <input type="text" id="search-input" class="input" name="txt" placeholder="Cari disini..." autocomplete="off">
                        <i class="bi bi-search" style="font-size: 25px; left: 0.7em;"></i>
                      </form>
                    </div>
                  </form>
                  <div id="search-navbar" class="search-navbar background-content position-fixed flex flex-column rounded-3 p-2" style="min-width: 18.5vw; display: none; z-index: 999; top: 70px; background: white;">
                    
                  </div>

                  <div class="dropdown-animation"> 
                    <a href="/peserta/index" class="text-decoration-none text-dark">KELAS</a>
                  </div>
            
                  <div  class=" dropdown-animation div-text">KEGIATAN
                    <ul class=" p-3 background-content dropdown-animation-menu">
                      <hr>
                      <li class="m-3"><a class="m-0" href="#">Seminar</a></li>
                      <hr>
                      <li class="m-3"><a class="m-0" href="#">Webinar</a></li>
                      <hr>
                      <li class="m-3"><a class="m-0" href="#">Workshop</a></li>
                      <hr>
                      <li class="m-3"><a class="m-0" href="#">Forum Grup Discussion</a></li>
                      <hr>
                      <li class="m-3"><a class="m-0" href="#">Character Building & Teamwork</a></li>
                      <hr>
                    </ul>
                  </div>

                  <div class="dropdown-animation"> 
                    <a href="/default/panduan" class="text-decoration-none text-dark">PANDUAN</a>
                  </div>
              
                  <div class="dropdown-animation div-text">BANTUAN
                    <ul class=" p-3 background-content dropdown-animation-menu">
                    <hr>
                    <li class="m-3"><a class="m-0" href="/default/faq">FAQ</a></li>
                    <hr>
                    <li class="m-3"><a class="m-0" href="/default/about-us">Tentang Kami</a></li>
                    <hr>
                    <li class="m-3"><a class="m-0" href="/default/contact-us">Hubungi Kami</a></li>
                    <hr>
                    <li class="m-3"><a class="m-0" href="/default/privacy-policy">Kebijakan Privasi</a></li>
                    <hr>
                    </ul>
                  </div>
                </ul>

                <ul class="nav-item container-profile d-flex flex-row align-items-center justify-content-end p-0 m-0" style="width: 20%;"> 
                  <li class="btn-group list-unstyled d-flex justify-content-center align-items-center position-relative">
                    <button type="button" class="background-content btn d-flex justify-content-center align-items-center rounded-circle" style="width: 40px; height: 40px; background-color: #E5E7E9; box-shadow: 2.0px 4.0px 4.0px hsl(0deg 0% 0% / 0.38);" data-bs-toggle="dropdown" aria-expanded="false">';
                      if($peserta->fotopesertanonasn_uri != "") {
                        echo'<img src="https://berkas.dpr.go.id/mooc/fotopesertanonasn/'.$peserta->fotopesertanonasn_uri.'" alt="'. $peserta->nama .'" class="rounded-circle" style="width: 40px; height: 40px;">';
                      } else {
                        echo'<img src="https://berkas.dpr.go.id/mooc/assets/images/username-orange.png" alt="default-photo" class="rounded-circle" style="width: 30px; height: 30px;">';
                      }
                    echo '</button>
                            
                    <ul class="dropdown-menu position-absolute background-content" style="left: -200px; z-index: 99999999999; margin-top: 14px; padding: 10px; min-width: 300px;">
                      <li class="text-center"> <p class="fs-4">' . $peserta->nama . '</p></li>
                      <li class="text-center"><a class="dropdown-item btn border" href="/peserta/profile/index/id/' . $auth->id_peserta . '">View Profile</a></li>
                      <!--<div class="dropdown-divider"></div>
                      <li><a class="dropdown-item" href="#"><i class="bi bi-gear"></i> Setting</a></li> -->
                      <div class="dropdown-divider"></div>
                      <li><a class="dropdown-item" href="/login/logout"><i class="bi bi-box-arrow-right"></i>Logout</a></li>
                    </ul>
                  </li>
                      
                  <li class="list-unstyled d-flex justify-content-center align-items-center" style="width: 50px;">
                    <button type="button" class="background-content btn position-relative d-flex justify-content-center align-items-center rounded-circle" style="width: 40px; height: 40px; background-color: #E5E7E9;">
                      <img src="https://berkas.dpr.go.id/mooc/assets/images/bell.png" alt="" class="rounded-circle position-absolute" style="width: 25px; height: 25px;">
                      <span class="position-absolute m-0 bg-danger rounded-circle" style="width: 10px; height: 10px; right: 3px; top: 3px;"></span>
                    </button>
                  </li>
                </ul>

              </div>
            </div>
          </nav>';
          // end profile
    }
  ?>
  <!-- end navbar -->

  <!-- dark & light mode -->
  <div class="container-dark-mode position-absolute" style="top: 120px; right: 1.5em; z-index: 99; cursor: pointer;">
    <div class="sun sun-logo" style="fill: #D4A216;">
      <svg viewBox="0 0 512 512" width="40" title="sun">
        <path d="M256 160c-52.9 0-96 43.1-96 96s43.1 96 96 96 96-43.1 96-96-43.1-96-96-96zm246.4 80.5l-94.7-47.3 33.5-100.4c4.5-13.6-8.4-26.5-21.9-21.9l-100.4 33.5-47.4-94.8c-6.4-12.8-24.6-12.8-31 0l-47.3 94.7L92.7 70.8c-13.6-4.5-26.5 8.4-21.9 21.9l33.5 100.4-94.7 47.4c-12.8 6.4-12.8 24.6 0 31l94.7 47.3-33.5 100.5c-4.5 13.6 8.4 26.5 21.9 21.9l100.4-33.5 47.3 94.7c6.4 12.8 24.6 12.8 31 0l47.3-94.7 100.4 33.5c13.6 4.5 26.5-8.4 21.9-21.9l-33.5-100.4 94.7-47.3c13-6.5 13-24.7.2-31.1zm-155.9 106c-49.9 49.9-131.1 49.9-181 0-49.9-49.9-49.9-131.1 0-181 49.9-49.9 131.1-49.9 181 0 49.9 49.9 49.9 131.1 0 181z" />
      </svg>
    </div>
    <div class="moon moon-logo">
      <svg viewBox="0 0 512 512" width="40" title="moon">
        <path d="M283.211 512c78.962 0 151.079-35.925 198.857-94.792 7.068-8.708-.639-21.43-11.562-19.35-124.203 23.654-238.262-71.576-238.262-196.954 0-72.222 38.662-138.635 101.498-174.394 9.686-5.512 7.25-20.197-3.756-22.23A258.156 258.156 0 0 0 283.211 0c-141.309 0-256 114.511-256 256 0 141.309 114.511 256 256 256z" />
      </svg>
    </div>
  </div>
  <!-- end dark & light mode -->

  <!-- modal daftar -->
  <div class="modal fade" id="daftar" tabindex="-1" aria-labelledby="loginLabel" aria-hidden="true">
    <div class="modal-dialog rounded-4 border border-0">
      <div class="modal-content background-content p-5 rounded-4">
        <div class="m-auto">
          <p class="modal-title fs-4 fw-bold text-center text-secondary" id="loginLabel">Daftar Menggunakan Akun</p>
          <p class="modal-title fs-4 fw-bold text-center text-secondary" >PORTAL DPR RI</p>
        </div>
        <div class="modal-body">
	        <form id="compose" name="compose" method="post" action="" enctype="multipart/form-data">
            <div class="mb-3 position-relative d-flex align-items-center">
              <img class="position-absolute me-3" src="https://berkas.dpr.go.id/mooc/assets/images/username.png" alt="" style="width: 20px; height: 20px; left: 10px;">
              <input type="text" name="pengguna" id="pengguna" class="form-control sub-background-content px-5 text-secondary input100" style="outline: none !important;" placeholder="Pengguna">
            </div>
            <div class="mb-3 position-relative d-flex align-items-center justify-content-between">
              <img class="position-absolute me-3" src="https://berkas.dpr.go.id/mooc/assets/images/password.png" alt="" style="width: 20px; height: 20px; left: 10px;">
              <input type="password" name="sandi" id="login_password" class="form-control sub-background-content px-5 text-secondary input100" style="outline: none !important;" placeholder="Password" autocomplete="disable">
              <i id="eyeIconPasswordLogin" class="bi bi-eye-slash position-absolute me-3" style="width: 20px; height: 15px; right: 5px; cursor: pointer;" onclick="hideShowPasswordLogin()"></i>

              <!-- <img class="position-absolute me-3" src="https://berkas.dpr.go.id/mooc/assets/images/hide-password.png" alt="" style="width: 20px; height: 15px; right: 5px; cursor: pointer;" onclick="hideShowPasswordLogin()"> -->
            </div>
            
            <div class="g-recaptcha d-flex justify-content-center" data-sitekey="6LcrjkwnAAAAAM3bLuWp7mNSWUwVo_6yIwIvLQzA"></div>


            <div class="mb-1 p-1 text-center rounded-3 mt-3" style="max-width: 100vw; background-color: #D4A216">

            
              <button type="submit" class="btn text-white fw-bold" style="background-color: #D4A216;width: 22em;">Daftar</button>
            </div>
            <!-- <p class="text-secondary text-center fw-bold" style="letter-spacing: 0.8px">Lupa password? <a
                class="fw-bold" style="letter-spacing: 0.8px; color: #D4A216;" href=""> Ubah password</a></p> -->

                <div class="row">
          <div class="col-md-12">
            <p class="text-secondary text-center fw-bold" style="letter-spacing: 0.8px">Daftar Untuk Selain ASN Sekretariat DPR RI?&nbsp;&nbsp; 
              <a class="fw-bold" style="letter-spacing: 0.8px; color: #D4A216;" href="" data-bs-toggle="modal" data-bs-target="#register"> Daftar disini</a>
            </p>
          </div>
        </div>

          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- end modal daftar -->

  <!-- modal login -->
  <div class="modal fade" id="login" tabindex="-1" aria-labelledby="loginLabel" aria-hidden="true">
    <div class="modal-dialog rounded-4 border border-0">
      <div class="modal-content background-content p-5 rounded-4">
        <div class="m-auto ">
          <p class="modal-title fs-4 fw-bold text-center text-secondary" id="loginLabel">Selamat Datang di Prasmanan Learning!</p>
          <p class="modal-title fs-6 fw-bold text-center text-secondary" >Masuk untuk mengeksplorasi galaksi pengetahuan!</p>
          <br>
          <p class="modal-title fs-5 fw-bold text-center "  style="color: #D4A216;">Dari mana Anda berasal?</p>
        </div>
        <div class="modal-body">
            <div class="mb-1 p-1 text-center rounded-3 mt-1" style="max-width: 100vw; background-color: #D4A216">
              <button class=" btn text-white fw-bold" style="background-color: #D4A216; width: 22em;" onclick="window.location.href = 'https://belajar.dpr.go.id/admin';">ASN Sekretariat DPR RI</button>
            </div>
            <div class="mb-1 p-1 text-center rounded-3 mt-3" style="max-width: 100vw; border: 2px solid #D4A216; color: #D4A216; ">
              <button class="btn  fw-bold" style="color: #D4A216; width: 22em;" data-bs-toggle="modal" data-bs-target="#loginselainasn" >Selain ASN Sekretariat DPR RI</button>

            </div>


            <!-- <p class="text-secondary text-center fw-bold" style="letter-spacing: 0.8px">Lupa password? <a
                class="fw-bold" style="letter-spacing: 0.8px; color: #D4A216;" href=""> Ubah password</a></p> -->
                <div class="row ">
          <div class="col-md-12">
            <p class="text-secondary text-center fw-bold" style="letter-spacing: 0.8px">
            Gunakan akun Anda secara bijak dan JANGAN bagi pakai akun Anda kepada orang lain.
            </p>
          </div>
        </div>
        </div>
      </div>
    </div>
  </div>
  <!-- end modal login -->

  <!-- modal login selain asn -->
  <div class="modal fade" id="loginselainasn" tabindex="-1" aria-labelledby="loginLabel" aria-hidden="true">
    <div class="modal-dialog rounded-4 border border-0">
      <div class="modal-content background-content p-5 rounded-4">
        <div class="m-auto">
          <p class="modal-title fs-4 fw-bold text-center text-secondary" id="loginLabel">Login Selain ASN</p>
        </div>
        <div class="modal-body">
	        <form id="compose" name="compose" method="post" action="/loginselainasn/login" enctype="multipart/form-data">
            <div class="mb-3 position-relative d-flex align-items-center">
              <img class="position-absolute me-3" src="https://berkas.dpr.go.id/mooc/assets/images/username.png" alt="" style="width: 20px; height: 20px; left: 10px;">
              <input type="text" name="username" id="username" class="form-control sub-background-content px-5 text-secondary input100" style="outline: none !important;" placeholder="Pengguna">
            </div>
            <div class="mb-3 position-relative d-flex align-items-center justify-content-between">
              <img class="position-absolute me-3" src="https://berkas.dpr.go.id/mooc/assets/images/password.png" alt="" style="width: 20px; height: 20px; left: 10px;">
              <input type="password" name="password" id="password" class="form-control sub-background-content px-5 text-secondary input100" style="outline: none !important;" placeholder="Password" autocomplete="disable">
              <i id="eyeIconPasswordLogin" class="bi bi-eye-slash position-absolute me-3" style="width: 20px; height: 15px; right: 5px; cursor: pointer;" onclick="hideShowPasswordLogin()"></i>

              <!-- <img class="position-absolute me-3" src="https://berkas.dpr.go.id/mooc/assets/images/hide-password.png" alt="" style="width: 20px; height: 15px; right: 5px; cursor: pointer;" onclick="hideShowPasswordLogin()"> -->
            </div>
            <div class="mb-1 p-1 text-center rounded-3 mt-3" style="max-width: 100vw; background-color: #D4A216">
              <button type="submit" class="btn text-white fw-bold" style="background-color: #D4A216;">Login</button>
            </div>

                <div class="row">
          <div class="col-md-12">
            <p class="text-secondary text-center fw-bold" style="letter-spacing: 0.8px">Belum Memiliki Akun?&nbsp;&nbsp; 
              <a class="fw-bold" style="letter-spacing: 0.8px; color: #D4A216;" href="" data-bs-toggle="modal" data-bs-target="#register"> Daftar disini</a>
            </p>
          </div>
        </div>

          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- end modal login selain asn -->
  <?php
    $loginError = new Zend_Session_Namespace('loginError');
    if (isset($loginError->message)) {
        echo '<script>alert("' . $loginError->message . '");</script>';
        unset($loginError->message);
    }
  ?>

  <!-- modal register -->
  <div class="modal fade" id="register" tabindex="-1" aria-labelledby="registerLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content background-content p-5 rounded-4">
        <div class="m-auto">
          <p class="modal-title fs-4 fw-bold text-center" id="registerLabel">Pendaftaran Selain ASN Sekretariat DPR RI</p>
        </div>
        <div class="modal-body">
          <form id="register-formXXX" method="post" action="/default/pendaftaran/index" enctype="multipart/form-data">
            <div class="row">
              <div class="col-md-6">
                <div class="mb-3 position-relative d-flex align-items-center">
                  <i class="position-absolute bi bi-person-fill text-secondary" style="left: 15px;"></i>
                  <input type="text" class="form-control sub-background-content px-5 text-secondary" id="nama" name="nama" placeholder="Nama Lengkap" required>
                </div>

                <div class="mb-3 position-relative d-flex align-items-center">
                  <i class="position-absolute bi bi-person-vcard-fill text-secondary" style="left: 15px;"></i>
                  <input type="text" class="form-control sub-background-content px-5 text-secondary" id="identitas" name="identitas" placeholder="NIK" required>
                </div>

                <div class="mb-3 position-relative d-flex align-items-center">
                  <i class="position-absolute bi bi-envelope-fill text-secondary" style="left: 15px;"></i>
                  <input type="email" class="form-control sub-background-content px-5 text-secondary" id="email" name="email" placeholder="Email" required>
                </div>

                <div class="mb-3 position-relative d-flex align-items-center">
                  <i class="position-absolute bi bi-calendar-date-fill text-secondary" style="left: 15px;"></i>
                  <input type="date" class="form-control sub-background-content px-5 text-secondary" id="tanggal_lahir" name="tanggal_lahir" placeholder="Tanggal Lahir" required>
                </div>

                <div class="mb-3 position-relative d-flex align-items-center">
                  <i class="position-absolute bi bi-person-vcard-fill text-secondary" style="left: 15px;"></i>
                  <input type="text" class="form-control sub-background-content px-5 text-secondary" id="tempatlahir" name="tempatlahir" placeholder="Tempat Lahir" required>
                </div>

                <div class="mb-3 position-relative d-flex align-items-center">
                  <i class="position-absolute bi bi-person-workspace text-secondary" style="left: 15px;"></i>
                  <select class="form-control sub-background-content px-5 text-secondary" id="jenis_kelamin" name="jenis_kelamin" required>
                    <option value="" disabled selected>Jenis Kelamin</option>
                    <option value="laki-laki">Laki-laki</option>
                    <option value="perempuan">Perempuan</option>
                  </select>
                </div>
              </div>

              <div class="col-md-6">
                <div class="mb-3 position-relative d-flex align-items-center">
                  <i class="position-absolute bi bi-person-workspace text-secondary" style="left: 15px;"></i>
                  <input type="text" class="form-control sub-background-content px-5 text-secondary" id="pekerjaan" name="pekerjaan" placeholder="Pekerjaan" required>
                </div>

                <div class="mb-3 position-relative d-flex align-items-center">
                  <i class="position-absolute bi bi-flag-fill text-secondary" style="left: 15px;"></i>
                  <input type="text" class="form-control sub-background-content px-5 text-secondary" id="kewarganegaraan" name="kewarganegaraan" placeholder="Kewarganegaraan" required>
                </div>

                <div class="mb-3 position-relative d-flex align-items-center">
                  <i class="position-absolute bi bi-telephone-plus-fill text-secondary" style="left: 15px;"></i>
                  <input type="text" class="form-control sub-background-content px-5 text-secondary" id="telepon" name="telepon" placeholder="Telepon" required>
                </div>

                <div class="mb-3 position-relative d-flex align-items-center">
                  <i class="position-absolute bi bi-person-badge-fill text-secondary" style="left: 15px;"></i>
                  <input type="text" class="form-control sub-background-content px-5 text-secondary" id="usernamex" name="usernamex" placeholder="Username" required>
                </div>

                <div class="mb-3 position-relative d-flex align-items-center justify-content-between">
                  <i class="position-absolute bi bi-file-lock2 text-secondary" style="left: 15px;"></i>
                  <input type="password" class="form-control sub-background-content px-5 text-secondary" id="register_password" name="password" placeholder="Password" autocomplete="disable" required>
                  <i id="eyeIconPasswordRegister" class="bi bi-eye-slash position-absolute me-3" style="width: 20px; height: 15px; right: 5px; cursor: pointer;" onclick="hideShowPasswordRegister()"></i>
                </div>

                <div class=" border mb-3 position-relative d-flex align-items-center justify-content-between">
                  <i class="position-absolute bi bi-file-lock2 text-secondary" style="left: 15px;"></i>
                  <input type="password" class="form-control sub-background-content px-5 text-secondary" id="confirm_password" name="cpassword" placeholder="Ketik ulang password" required>
                  <i id="eyeIconPasswordRegisterConfirm"class="bi bi-eye-slash position-absolute me-3" style="width: 20px; height: 15px; right: 5px; cursor: pointer;" onclick="hideShowPasswordRegisterConfirm()"></i>
                </div>
                <div id="password_match_warning" class="mb-3 text-danger px-5 " style=" display: none;"> <i class="bi bi-exclamation-circle"></i> Password tidak cocok.</div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="mb-1 p-1 text-center rounded-3" style="max-width: 100vw; background-color: #D4A216;">
                  <button type="submit" class="btn text-white fw-bold" style="background-color: #D4A216;">Daftar</button>
                </div>
                <p class="text-secondary text-center fw-bold" style="letter-spacing: 0.8px">Punya akun Portal DPR RI?&nbsp;&nbsp;
                  <a class="fw-bold" style="letter-spacing: 0.8px; color: #D4A216; " href="" data-bs-toggle="modal" data-bs-target="#daftar">Daftar disini</a>
                </p>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- end modal register -->

  <!-- -------------------------------------------------------------------------------------------------------------------- -->
  <?= $this->layout()->content; ?>

  <!-- footer -->
  <footer class=" px-3 py-4" style="background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(240,152,25,1) 0%, rgba(226,211,88,1) 100%);">
    <div class="container">
      <div class="row">
        <div class="col-md-4 text-center">
          <img src="https://berkas.dpr.go.id/mooc/assets/images/logo_setjendpr.png" alt="" class="m-0"
            style="height: 15vh;">
          <h5 class="m-10" style="font-size: 1em;">Sekretariat Jenderal DPR RI</h5>
        </div>
        <div class="col-md-4">
        <h5 class="fs-5">Prasmanan Learning</h5>
          <ul class="list-unstyled">
            <li><a href="/default/panduan" class="text-decoration-none" style="font-size: 0.8em; color: black !important;"><i class="bi bi-info-circle"></i> Panduan</a></li>
            <li><a href="/default/faq" class="text-decoration-none" style="font-size: 0.8em; color: black !important;"><i class="bi bi-question-circle"></i> FAQ</a></li>
            <li><a href="/default/about-us" class="text-decoration-none" style="font-size: 0.8em; color: black !important;"><i class="bi bi-person"></i> Tentang Kami</a></li>
            <li><a href="/default/contact-us" class="text-decoration-none" style="font-size: 0.8em; color: black !important;"><i class="bi bi-envelope"></i> Hubungi Kami</a></li>
            <li><a href="/default/privacy-policy" class="text-decoration-none" style="font-size: 0.8em; color: black !important;"><i class="bi bi-shield-lock"></i> Kebijakan Privasi</a></li>
          </ul>
        </div>
        <div class="col-md-4">
          <h5 class="fs-5">Kontak</h5>
          <div class="social-feed">
            <div class="feed-line">
              <i class="bi bi-phone" style="font-size: 0.8em;"></i> Telp: (021) 571 56100, (021) 571 56069
            </div>
            <div class="feed-line">
              <i class="bi bi-envelope" style="font-size: 0.8em;"></i> pusdiklat@dpr.go.id
            </div>
            <div class="feed-line">
              <i class="bi bi-geo-alt-fill" style="font-size: 0.8em;"></i> Jalan Jenderal Gatot Subroto, Senayan,<br>
              &nbsp &nbsp  Jakarta 10270
            </div>
            
          </div>
        </div>
      </div>
      <hr class="my-4" style="border-color: black;">
      <div class="text-center">
        <p class="m-0" style="color: black !important;">&copy; Made with <i class="bi bi-heart-fill text-danger"></i> by Pusat Teknologi Informasi. All
          Rights Reserved</p>
      </div>
    </div>
  </footer>
  <!-- end footer -->

  <!-- onmouseout="this.value = ''; this.blur();" -->

  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  <script src="https://www.google.com/recaptcha/api.js" async defer></script>

  <script>
    // search
    document.addEventListener('DOMContentLoaded', function() {
      let batchs = <?php echo json_encode($batchs); ?>;
      let searchNavbar = document.getElementById('search-navbar');

      // Function generate card pelatihan
      function generateSearchNavbarContainer(data) {
        searchNavbar.style.display = "block";
        searchNavbar.innerHTML = '';

        data.forEach(function(item) {
          let searchNavbarContainer = document.createElement('div');
          searchNavbarContainer.classList.add('mb-2');

          let searchNavbarContent = `<a href="/default/detail-batch/index/id/${item.id_batch}" class="text-secondary text-decoration-none border-bottom border-secondary">${item.nama_pelatihan}</a>`;

          searchNavbarContainer.innerHTML = searchNavbarContent;
          searchNavbar.appendChild(searchNavbarContainer);
        });
      }

      // Function filter data
      let searchInput = document.getElementById('search-input');
      searchInput.addEventListener('input', filterPelatihan);

      function filterPelatihan() {
        let inputValue = searchInput.value.toLowerCase().trim();
        let filteredBatch = batchs.filter(function(item) {
          return item.nama_pelatihan.toLowerCase().includes(inputValue);
        });
        
        if(inputValue === "") {
          searchNavbar.style.display = "none";
          searchNavbar.innerHTML = '';
        } else if(filteredBatch.length > 0) {
          searchNavbar.style.display = "block";
          generateSearchNavbarContainer(filteredBatch);
        } else {
          searchNavbar.innerHTML = '<p class="mb-2 text-secondary border-bottom border-secondary">Pelatihan tidak ditemukan</p>';
        }      
      }
    });
    // end search

    function checkPasswordMatch() {
      var password = document.getElementById("register_password").value;
      var confirmPassword = document.getElementById("confirm_password").value;
      
      if (password !== confirmPassword) {
        document.getElementById("password_match_warning").style.display = "block";
      } else {
        document.getElementById("password_match_warning").style.display = "none";
      }
    }
  
    document.getElementById("register_password").addEventListener("keyup", checkPasswordMatch);
    document.getElementById("confirm_password").addEventListener("keyup", checkPasswordMatch);

    $('#register-form').submit(function(event) {
        event.preventDefault();
        $.ajax({
            url: '/default/pendaftaran/index',
            type: 'POST',
            data: {
              usernamex: $('#usernamex').val(),
              email: $('#email').val(),
              password: $('#register_password').val(),
              nama: $('#nama').val(),
              identitas: $('#identitas').val(),
              kewarganegaraan: $('#kewarganegaraan').val(),
              pekerjaan: $('#pekerjaan').val(),
              jenis_kelamin: $('#jenis_kelamin').val(),
              telepon: $('#telepon').val(),
              tempatlahir: $('#tempatlahir').val(),
              tanggal_lahir: $('#tanggal_lahir').val(),
                            },
            success: function(response) {
                // console.log(response);
              Swal.fire(
                'Pendaftaran Berhasil!',
                'Silahkan Login',
                'success'
              )
              setTimeout(function() {
                window.location.href = '/?showModalLogin=true';
              }, 2000);
            },
            error: function(xhr, status, error) {
                console.log('Register submission failed');
                console.log(xhr.responseText);
            }
        });
    });

    // Check for the query parameter 'showModal'
    const urlParams = new URLSearchParams(window.location.search);
    const showModal = urlParams.get('showModalLogin');

    if (showModal === 'true') {
      $(document).ready(function() {
        $('#loginselainasn').modal('show');
      });
    }

    function hideShowPasswordLogin() {
      let passwordLogin = document.getElementById("login_password");
      let eyeIcon = document.getElementById("eyeIconPasswordLogin");

      if (passwordLogin.type === "password") {
        passwordLogin.type = "text";
        eyeIcon.classList.remove("bi-eye-slash");
        eyeIcon.classList.add("bi-eye");
      } else if (passwordLogin.type === "text") {
        passwordLogin.type = "password";
        eyeIcon.classList.remove("bi-eye");
        eyeIcon.classList.add("bi-eye-slash");
      }
    }

    function hideShowPasswordRegister() {
      let passwordRegister = document.getElementById("register_password");
      let eyeIcon = document.getElementById("eyeIconPasswordRegister");

      if (passwordRegister.type === "password") {
        passwordRegister.type = "text";
        eyeIcon.classList.remove("bi-eye-slash");
        eyeIcon.classList.add("bi-eye");
      } else if (passwordRegister.type === "text") {
        passwordRegister.type = "password";
        eyeIcon.classList.remove("bi-eye");
        eyeIcon.classList.add("bi-eye-slash");
      }
    }

    function hideShowPasswordRegisterConfirm() {
      let passwordRegister = document.getElementById("confirm_password");
      let eyeIcon = document.getElementById("eyeIconPasswordRegisterConfirm");

      if (passwordRegister.type === "password") {
        passwordRegister.type = "text";
        eyeIcon.classList.remove("bi-eye-slash");
        eyeIcon.classList.add("bi-eye");
      } else if (passwordRegister.type === "text") {
        passwordRegister.type = "password";
        eyeIcon.classList.remove("bi-eye");
        eyeIcon.classList.add("bi-eye-slash");
      }
    }

    // dark mode
    document.addEventListener("DOMContentLoaded", function() {
      let darkMode = localStorage.getItem("darkMode");
      if (darkMode === "true") {
        // Jika darkMode bernilai "true", terapkan dark mode pada elemen yang diperlukan
        document.querySelector(".sun-logo").classList.add("animate-sun");
        document.querySelector(".moon-logo").classList.add("animate-moon");
        document.querySelector("body").classList.add("dark");
        toggleTextColor();
      }
    });

    document.querySelector(".container-dark-mode").addEventListener("click", function() {
      // Toggle class animate-sun, animate-moon, dan dark pada elemen yang diperlukan
      document.querySelector(".sun-logo").classList.toggle("animate-sun");
      document.querySelector(".moon-logo").classList.toggle("animate-moon");
      document.querySelector("body").classList.toggle("dark");
      toggleTextColor();
      // Mengecek apakah elemen body memiliki class dark setelah perubahan
      let isDarkMode = document.querySelector("body").classList.contains("dark");
      // Menyimpan status mode gelap ke dalam local storage
      localStorage.setItem("darkMode", isDarkMode);
    });

    function toggleTextColor() {
      let tagP = document.getElementsByTagName("p");
      for (let i = 0; i < tagP.length; i++) {
        tagP[i].classList.toggle("white-text");
      }

      let tagA = document.getElementsByTagName("a");
      for (let i = 0; i < tagA.length; i++) {
        tagA[i].classList.toggle("white-text");
      }

      let textDiv = document.querySelectorAll(".div-text");
      for (let i = 0; i < textDiv.length; i++) {
        textDiv[i].classList.toggle("white-text");
      }

      let backgroundContent = document.querySelectorAll(".background-content");
      for (let i = 0; i < backgroundContent.length; i++) {
        backgroundContent[i].classList.toggle("background-dark");
      }

      let subBackgroundContent = document.querySelectorAll(".sub-background-content");
      for (let i = 0; i < subBackgroundContent.length; i++) {
        subBackgroundContent[i].classList.toggle("sub-background-dark");
      }
    }
    // end dark mode

    // btn have login
    let btnHaveLogin = document.querySelector(".btn-have-login")
    if (btnHaveLogin) {
      btnHaveLogin.addEventListener("click", () => {
        Swal.fire({
          icon: 'warning',
          title: 'Warning',
          html: 'Anda belum login, silahkan login terlebih dahulu',
          confirmButtonColor: '#4CAF50',
          customClass: {
            popup: 'my-custom-popup-class',
            title: 'my-custom-title-class',
            content: 'my-custom-content-class',
            confirmButton: 'confirm-button-class'
          }
        });
      });
    }
    // end btn have login
  </script>
</body>
</html>
