<section class="container-tentang mb-5 d-flex flex-column justify-content-evenly p-3" style="padding-top: 150px !important; max-width: 100vw;">
    <p class="fs-2 fw-bold text-center">HUBUNGI KAMI</p>
    <p class="text-center">Telp: (021) 571 56100, (021) 571 56069</p>
    <p class="text-center">pusdiklat@dpr.go.id</p>
    <p class="text-center">Jalan Jenderal Gatot Subroto, Senayan, Jakarta 10270</p>
</section>