<section class="container-tentang mb-5 d-flex flex-column justify-content-evenly p-3"
    style="padding-top: 150px !important; max-width: 100vw;">
    <p class="fs-2 fw-bold text-center">KEBIJAKAN PRIVASI</p>
    <p class="fs-5 fw-bold text-center">Pengantar</p>
    <p class="px-5" style="text-align: justify;">Pemberitahuan Privasi berikut ini digunakan untuk menginformasikan
        pengunjung mengenai kebijakan DPR-RI dalam mengumpulkan, menyimpan, menggunakan, mengolah, mentransfer,
        mengungkapkan dan melindungi Informasi Pribadi anda. Penggunaan, dan pengungkapan Informasi Pribadi jika ada
        yang memutuskan untuk menggunakan Layanan kami.</p>
    <p class="fs-5 fw-bold text-center">Pengakuan dan Persetujuan</p>
    <p class="px-5" style="text-align: justify;">Dengan menyetujui Pemberitahuan Privasi, anda mengakui bahwa anda telah
        membaca dan
        memahami Pemberitahuan Privasi ini dan menyetujui segala ketentuannya. Secara khusus, anda
        setuju dan memberikan persetujuan kepada kami untuk mengumpulkan, menggunakan,
        membagikan, mengungkapkan, menyimpan, mentransfer, atau mengolah Informasi Pribadi anda
        sesuai dengan Pemberitahuan Privasi ini.</p>
    <p class="px-5" style="text-align: justify;">Dalam keadaan di mana anda menyediakan kepada kami Informasi Pribadi
        yang berkaitan
        dengan anda dan individu lain (seperti Informasi Pribadi yang berkaitan dengan pasangan anda,
        anggota keluarga, teman, atau pihak lain), anda menyatakan dan menjamin bahwa anda telah
        memperoleh persetujuan dari individu tersebut, dan dengan ini menyetujui atas nama individu
        tersebut untuk, pengumpulan, penggunaan, pengungkapan dan pengolahan Informasi Pribadi
        mereka oleh kami.
    </p>
    <p class="fs-5 fw-bold text-center">Pengumpulan dan Penggunaan Informasi</p>
    <p class="px-5" style="text-align: justify;">Untuk pengalaman yang lebih baik, saat menggunakan Layanan kami, kami
        mungkin meminta
        Anda untuk memberikan kami informasi identitas pribadi tertentu. Informasi yang kami minta
        akan disimpan oleh kami dan digunakan sebagaimana dijelaskan dalam kebijakan privasi ini.</p>
    <p class="px-5" style="text-align: justify;">Kami mengumpulkan Informasi Pribadi saat anda menggunakan Aplikasi
        kami. Kami juga
        mengumpulkan informasi perangkat dan teknis dari anda, dan informasi lain yang mungkin anda
        kirimkan saat anda menggunakan Aplikasi kami. Jika anda memilih untuk tidak menyediakan
        informasi tersebut, kami tidak akan dapat menyediakan Aplikasi kepada anda secara normal.</p>
    <p class="px-5" style="text-align: justify;"> <b>“Informasi Pribadi”</b> berarti informasi yang mengidentifikasi
        atau dapat digunakan untuk
        mengidentifikasi, menghubungi, atau menemukan orang atau perangkat yang terkait dengan
        informasi tersebut. Sepanjang diizinkan oleh Peraturan Perundang-undangan yang Berlaku, kami
        dapat mengumpulkan, menggunakan, menyimpan dan mentransfer jenis-jenis berbeda dari
        Informasi Pribadi tentang anda yang telah kami kategorikan sebagai berikut:</p>
    <ul style="margin-left:40px;" class="px-5" style="text-align: justify;">
        <li><p><b>Data Identitas</b> termasuk NIK, nama, nama pengguna, tanggal kelahiran, jenis kelamin,
            tempat kelahiran, pekerjaan dan/atau kebangsaan.</p></li>
        <li><p><b>Data Kontak</b> termasuk alamat email, dan nomor telepon. </p></li>
    </ul>
    <p class="px-5" style="text-align: justify;">
        Kami dapat membuat, menggunakan, atau mengungkapkan Data Gabungan seperti data statistik
        atau demografi untuk tujuan apa pun. Data Gabungan dapat berasal dari Informasi Pribadi anda
        tetapi tidak akan dianggap sebagai Informasi Pribadi karena data ini tidak akan secara langsung
        atau tidak langsung mengungkapkan identitas anda karena kami akan memastikan: (i) bahwa
        semua pengenal telah dihapus sedemikian rupa sehingga data, sendiri atau bersama-sama
        dengan data lain yang tersedia, tidak dapat dikaitkan atau dihubungkan dengan atau tidak dapat
        mengidentifikasi siapa pun, dan (ii) data tersebut kemudian digabungkan dengan data serupa
        sehingga data asli membentuk bagian dari kumpulan data yang lebih besar.
    </p>
    <p class="fs-5 fw-bold text-center">Melindungi Informasi Pribadi Anda</p>
    <ul style="margin-left:40px;" class="px-5" style="text-align: justify;">
        <li><p><b>Keamanan Data</b> Kerahasiaan Informasi Pribadi anda adalah hal yang terpenting bagi 
kami. Kami akan memberlakukan upaya terbaik untuk melindungi dan mengamankan  
Informasi Pribadi anda dari akses, pengumpulan, penggunaan atau pengungkapan oleh 
orang-orang yang tidak berwenang dan dari pengolahan yang bertentangan dengan 
hukum, kehilangan yang tidak disengaja, pemusnahan dan kerusakan atau risiko serupa. 
Namun, pengiriman informasi melalui internet tidak sepenuhnya aman. Walau kami akan 
berusaha sebaik mungkin untuk melindungi Informasi Pribadi anda, anda mengakui 
bahwa kami tidak dapat menjamin keutuhan dan keakuratan Informasi Pribadi apa pun 
yang anda kirimkan melalui Internet, atau menjamin bahwa Informasi Pribadi tersebut 
tidak akan dicegat, diakses, diungkapkan, diubah atau dihancurkan oleh pihak ketiga yang 
tidak berwenang, karena faktor-faktor di luar kendali kami. Anda bertanggung jawab 
untuk menjaga kerahasiaan detail Akun anda dan anda harus selalu menjaga dan 
bertanggung jawab atas keamanan perangkat yang anda gunakan.</p></li>
<li><p><b>Penyimpanan Data</b> Informasi Pribadi anda hanya akan disimpan selama diperlukan 
untuk memenuhi tujuan dari pengumpulannya, atau selama penyimpanan tersebut 
diperlukan atau diperbolehkan oleh Peraturan Perundang-undangan yang Berlaku. Kami 
akan berhenti menyimpan Informasi Pribadi, atau menghapus maksud dari dikaitkannya 
Informasi Pribadi tersebut dengan anda sebagai individu, segera setelah dianggap bahwa 
tujuan pengumpulan Informasi Pribadi tersebut tidak lagi dibutuhkan. Mohon 
diperhatikan bahwa masih ada kemungkinan bahwa beberapa Informasi Pribadi anda 
disimpan oleh pihak lain dengan termasuk institusi pemerintah cara tertentu. Dalam hal 
kami membagikan Informasi Pribadi anda kepada institusi pemerintah yang berwenang 
dan/atau institusi lainnya yang dapat ditunjuk oleh pemerintah yang berwenang atau 
memiliki kerja sama dengan kami, anda menyetujui dan mengakui bahwa penyimpanan 
Informasi Pribadi anda oleh institusi terkait akan mengikuti kebijakan penyimpanan data 
masing-masing institusi tersebut.</p>
</li>
    </ul>

    <p class="fs-5 fw-bold text-center">Hak anda sebagai pengguna</p>
    <ul style="margin-left:40px;" class="px-5" style="text-align: justify;" >
        <li><p><b>Hak Hukum Anda</b> Anda mungkin memiliki hak tertentu berdasarkan Peraturan Perundang-undangan yang Berlaku 
untuk meminta kepada kami terhadap akses kepada, koreksi dari dan/atau penghapusan 
terhadap Informasi Pribadi anda yang berada dalam penguasaan dan kendali kami. Sepanjang 
hak ini tersedia bagi anda sesuai dengan ketentuan Peraturan Perundang-undangan yang 
Berlaku, anda dapat melaksanakan hak tersebut dengan menghubungi kami di perincian yang 
disediakan di bawah ini.  Kami berhak menolak permintaan anda terhadap akses pada, koreksi dari dan/atau penghapusan 
terhadap, sebagian atau semua Informasi Pribadi anda yang kami kuasai atau kendalikan jika 
diizinkan atau diperlukan berdasarkan Peraturan Perundang-undangan yang Berlaku. Hal ini 
termasuk dalam keadaan di mana Informasi Pribadi tersebut dapat berisi referensi kepada orang 
lain atau di mana permintaan untuk akses atau permintaan untuk mengoreksi atau menghapus 
adalah untuk alasan yang kami anggap tidak relevan, tidak serius, atau menyulitkan. Tunduk pada 
Peraturan Perundang-undangan yang Berlaku, kami mencadangkan hak untuk membebankan 
biaya administratif untuk setiap permintaan akses dan/atau koreksi.</p></li>
<li><p><b>Pembaharuan Terhadap Pemberitahuan Privasi</b> Kami dapat meninjau kembali dan mengubah Pemberitahuan Privasi ini atas kebijakan kami 
sendiri dari waktu ke waktu, untuk memastikan bahwa Pemberitahuan Privasi ini konsisten 
dengan perkembangan kami di masa depan, dan/atau perubahan persyaratan hukum atau 
peraturan. Jika kami memutuskan untuk mengubah Pemberitahuan Privasi ini, kami akan 
memberitahu anda tentang perubahan tersebut melalui pemberitahuan umum yang 
dipublikasikan pada Aplikasi dan/atau situs web, atau ke alamat e-mail anda yang tercantum 
dalam Akun anda. Anda setuju bahwa adalah tanggung jawab anda untuk memeriksa
Pemberitahuan Privasi ini secara berkala untuk mengetahui informasi terbaru tentang 
pengolahan data dan praktik pelindungan data kami, dan bahwa dengan anda terus 
menggunakan Aplikasi atau situs web kami, berkomunikasi dengan kami, atau mengakses dan 
menggunakan layanan setelah adanya perubahan apapun terhadap Pemberitahuan Privasi ini 
akan dianggap sebagai persetujuan anda terhadap Pemberitahuan Privasi ini dan segala 
perubahannya.</p></li>
    </ul>

</section>