<script id="js">
$(function(){
	$("table")
		.tablesorter({theme: 'blue', widthFixed: true, widgets: ['zebra', 'filter']})
		.tablesorterPager({container: $(".pager"), 
							output: '{startRow} - {endRow} / {filteredRows} ({totalRows})', 
							fixedHeight: true, 
							removeRows: false, 
							cssGoto: '.gotoPage' });
});
</script>

<div class="content-header"></div>
	<div class="UI_Header_Title">
		<h1><?=$this->avatar;?> Daftar Kegiatan</h1>
		<div class="header_nav_links"><span class="right context_menu"><a href="/admin/kegiatan/add" class="UIlink-button small right">Tambah Kegiatan</a></span>
	</div>
</div>
<div class="clear"></div>
<br>

<? if (count($this->rows) > 0) { ?>
	<?=$this->pager;?>

	<table class="tablesorter">
		 <thead>
			 <tr>
				<th>No.</th>
				<th>Judul Kegiatan</th>
				<th>Jenis Kegiatan</th>
				<th>Awal</th>
				<th>Akhir</th>
				<th>Deskripsi</th>
				<th>Kuota Peserta</th>
				<th>Penyelenggara</th>
				<th>Aksi</th>
			</tr>
		</thead>
		<tbody>
			<?php
			$index = 1;
			foreach($this->rows as $row)
			{
				echo '<tr>';
				echo '<td align="center">'. $index++ .'.</td>';
				echo '<td>'. $row->title .'</td>';
				echo '<td>'. $row->tipe_kegiatan .'</td>';
				echo '<td>'. date('d-m-Y', strtotime($row->tgl_awal)) .'</td>';
				echo '<td>'. date('d-m-Y', strtotime($row->tgl_akhir)) .'</td>';
				echo '<td>'. $row->deskripsi .'</td>';
				echo '<td>'. $row->kuota_peserta .'</td>';
				echo '<td>'. $row->penyelenggara .'</td>';
				echo '<td align="center"><a href="/admin/kegiatan/edit/id/'. $row->id .'">EDIT</a>';
				if ($this->getRole() == 'admin' || $this->getRole() == 'super') {
					echo '&nbsp;|&nbsp;<a href="/admin/kegiatan/delete/id/'. $row->id .'" onclick="return confirmDelete();">DELETE</a>';
				}
				echo '</td>';
				echo '</tr>';
			}
			?>
		</tbody>
	</table>
<? } else {
	echo 'Data tidak ditemukan.';
}
?>