<script type="text/javascript">
	$(document).ready(function() {
		$("#compose").validate();
	})
</script>

<div class="content-header"></div>
<div class="UI_Header_Title">
	<h1><?=$this->avatar;?>Tambah Gambar Banner</h1>
	<div class="header_nav_links"><a href="/admin/banner/index">Back to Daftar Banner</a></div>
</div>
<div class="clear"></div>
<form id="compose" name="compose" method="post" action="" enctype="multipart/form-data">
	<div class="tabular">
		
		<p>
			<label class="left" for="gambar_uri">Gambar Banner</label> 
			<input type="file" accept="image/*" id="file_name" name="file_name">
		</p>

		
		<p class="savecancel"><label class="UIbutton-small"><input type="submit" value="Simpan" class=""/></label><a href="/admin/banner/index" class="UIbutton-small">Batal</a></p>
	</div>
</form>
<div style="clear:both"></div>
