<script type="text/javascript">
	$(document).ready(function() {
		$("#compose").validate();
	})

	function selectFields1(id, id, username) {
		$('#id_user').val(id);
		$('#username').val(username);
		$.facebox.close();
	}

	function ClearFields1() {
		document.getElementById("id_user").value = "";
		document.getElementById("username").value = "";
	}
	$(function() {
		$("#tanggal_lahir").datepicker({
			yearRange: "-100:+0",
			changeYear: "true",
			changeMonth: "true",
			dateFormat: "dd-mm-yy"
		});
	});
</script>

<div class="content-header"></div>
<div class="UI_Header_Title">
	<h1><?= $this->avatar; ?>Tambah Pengajar</h1>
	<div class="header_nav_links"><a href="/admin/pengajar/index">Back to Daftar Pengajar</a></div>
</div>
<div class="clear"></div>
<form id="compose" name="compose" method="post" action="" enctype="multipart/form-data">
	<div class="tabular">
		<p><label>User</label>
			<input readonly type="text" id="username" autocomplete="disable" name="username" style="height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;" />
			<input type="hidden" id="id_user" autocomplete="disable" name="id_user"/>
			<input type="button" value="..." id="btnuser" style="height:30px;" onclick="jQuery.facebox({ ajax: '/admin/pengajar/search-user'});">
			<input type="button" style="height:30px;" onclick="ClearFields1();" value="Clear">
			<font color="red">*</font>
		</p>
		<p>
			<label class="left" for="nama_penagajar">Nama Pengajar</label>
			<input type="text" id="nama_pengajar" class="event-message" wrap="soft" name="nama_pengajar" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;"><?= $this->nama_pengajar; ?>
		</p>
		<p>
            <label>Jenis Kelamin</label>
            <select class="required" id="jenis_kelamin" name="jenis_kelamin" style="overflow: hidden; display: block; width: 360px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;">
                <option <?= ($this->row->jenis_kelamin == 'Pria' ? 'selected' : '') ?> value="Pria">Pria</option>
                <option <?= ($this->row->jenis_kelamin == 'Wanita' ? 'selected' : '') ?> value="Wanita">Wanita</option>
            </select>  
        </p>
        <? $ttl = explode(", ",$this->row->ttl); ?>
        <p>
			<label class="left" for="tempat_lahir">Tempat Lahir</label>
			<input type="text" id="tempat_lahir" class="event-message" wrap="soft" name="tempat_lahir" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;" value="<?= $ttl[0]; ?>">
		</p>
        <p>
			<label>Tanggal Lahir</label>
			<input class="required" type="text" id="tanggal_lahir" autocomplete="disable" name="tanggal_lahir" value="<?= date('d-m-Y', strtotime($ttl[1])); ?>" style="width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px; background-color: white;" />
			<font color="red">*</font>
		</p>
		<p>
			<label class="left" for="identitas_pengajar">NIP/NIK</label>
			<input type="number" id="identitas_pengajar" class="event-message" wrap="soft" name="identitas_pengajar" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;"><?= $this->identitas_pengajar ?>
		</p>
		<p>
			<label class="left" for="pangkat">Pangkat/Golongan</label>
			<input type="text" id="pangkat" class="event-message" wrap="soft" name="pangkat" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;" value="<?= $this->row->pangkat; ?>">
		</p>
		<p>
			<label class="left" for="instansi">Asal Instansi</label>
			<input type="text" id="instansi" class="event-message" wrap="soft" name="instansi" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;"><?= $this->status_asal; ?>
		</p>
		<p>
			<label class="left" for="npwp">NPWP</label>
			<input type="text" id="npwp" class="event-message" wrap="soft" name="npwp" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;" value="<?= $this->row->npwp; ?>">
		</p>
		<p>
			<label class="left" for="email">Email</label>
			<input type="email" id="email" class="event-message" wrap="soft" name="email" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;"><?= $this->email; ?>
		</p>
		<p>
			<label class="left" for="no_telp">No Telepon</label>
			<input type="number" id="no_telp" class="event-message" wrap="soft" name="no_telp" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;"><?= $this->no_telp ?>
		</p>
		<p>
			<label class="left" for="norekening">No. Rekening</label>
			<input type="text" id="norekening" class="event-message" wrap="soft" name="norekening" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;" value="<?= $this->row->norekening; ?>">
		</p>
		<p>
			<label class="left" for="namabank">Nama Bank</label>
			<input type="text" id="namabank" class="event-message" wrap="soft" name="namabank" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;" value="<?= $this->row->namabank; ?>">
		</p>
		<p>
			<label class="left" for="fotopengajar_uri">Foto Pengajar</label> 
			<input type="file" accept="image/*" id="file_name" name="file_name">
		</P>



		<p class="savecancel"><label class="UIbutton-small"><input type="submit" value="Simpan" class="" /></label><a href="/admin/pengajar/index" class="UIbutton-small">Batal</a></p>
	</div>
</form>
<div style="clear:both"></div>