<script id="js">
	$(function() {
		$("table")
			.tablesorter({
				theme: 'blue',
				widthFixed: true,
				widgets: ['zebra', 'filter']
			})
			.tablesorterPager({
				container: $(".pager"),
				output: '{startRow} - {endRow} / {filteredRows} ({totalRows})',
				fixedHeight: true,
				removeRows: false,
				cssGoto: '.gotoPage'
			});
	});
</script>

<div class="content-header"></div>
<div class="UI_Header_Title">
	<h1><?= $this->avatar; ?> Daftar Pengajar</h1>
	<div class="header_nav_links"><span class="right context_menu"><a href="/admin/pengajar/add" class="UIlink-button small right">Tambah Pengajar</a></span>
	</div>
</div>
<div class="clear"></div>
<br>

<? if (count($this->rows) > 0) { ?>
	<?= $this->pager; ?>

	<table class="tablesorter">
		<thead>
			<tr>
				<th width="5px">No.</th>
				<th>Foto</th>
				<th>Nama/NIP Pengajar</th>
				<th>Instansi</th>
				<th>Kontak</th>
				<th>Aksi</th>
			</tr>
		</thead>
		<tbody>
		<?php
			$index = 1;
			foreach($this->rows as $row) {
				echo '<tr>';
				echo '<td align="center">'. $index++ .'.</td>';
				echo '<td align="center"><img src="https://berkas.dpr.go.id/mooc/fotopengajar/'.$row->fotopengajar_uri.'" width="80px"></td>';
				echo '<td>'.$row->nama_pengajar.'<br><span class="timespan">'.'NIP/NIK:'.''.$row->identitas_pengajar.'</span></td>';
				echo '<td align="center">'.$row->instansi.'</td>';
				echo '<td>'.$row->email.'<br><span class="timespan">'.$row->no_telp.'</span></td>';
				echo '<td align="center"><a href="/admin/pengajar/edit/id/'. $row->id .'">EDIT</a>';
				// if ($this->getRole() == 'admin' || $this->getRole() == 'super') {
					echo '&nbsp;|&nbsp;<a href="/admin/pengajar/delete/id/'. $row->id .'" onclick="return confirmDelete();">DELETE</a>';
				// }
				echo '</td>';
				echo '</tr>';
			}
			?>
		</tbody>
	</table>
<? } else {
	echo 'Data tidak ditemukan.';
}
?>