<?php  
$this->headTitle('DPR-RI');
$this->headTitle()->setSeparator(' - '); 
$this->headTitle()->append('Error'); 
echo $this->headTitle();
?>

<script type="text/javascript">
	setTimeout(function(){ location.href ='http://www.dpr.go.id'}, 5000);
</script>

<h1>Halaman tidak tersedia!</h1>
<img src=/images/layout/offline-ide-1.png>
<h3>Dalam 5 detik Anda akan di redirect ke <a href="http://www.dpr.go.id">halaman utama</a></h3>