<link href="https://fonts.googleapis.com/css?family=Roboto:700" rel="stylesheet">
<link rel="stylesheet" href="https://berkas.dpr.go.id/mooc/assets/css/error-admin.css">

<div class="container-error">
    <p class="mb-2 fw-bold" style="font-size: 80px;">404</p>
    <p class="fs-3 mb-2">Halaman tidak ditemukan</p>
    <p class="fs-7">Halaman yang Anda cari tidak ada atau terjadi kesalahan lainnya. Pergi ke<a href="/"> Halaman Home.</a></p>
</div>