<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Portal LMS</title>
  <link rel="stylesheet" href="./style.css">
  <style>
    body,
    html {
      height: 100%;
      background: #1c1e21;
      overflow-x: hidden;
      font-family: 'Dosis', sans-serif;
    }

    btn {
      border-radius: 0
    }

    .btn:focus,
    .btn:active,
    .btn.active,
    .btn:active:focus {
      outline: 0;
      border-radius: 0
    }

    .btn-larger {
      padding: 15px 40px !important;
      border: 2px solid #F7CA18 !important;
      ;
      border-radius: 0px !important;
      ;
      text-transform: uppercase;
      font-family: 'Dosis', sans-serif;
      font-size: 18px;
      font-weight: 300;
      color: #F7CA18;
      background-color: transparent;
      -webkit-transition: all .6s;
      -moz-transition: all .6s;
      transition: all .6s;
    }

    .btn-larger:hover,
    .btn-larger:focus,
    .btn-larger:active,
    .btn-larger.active,
    .open .dropdown-toggle.btn-larger {
      border-color: #F7CA18;
      color: #fff;
      background-color: #F7CA18;
      border-radius: 0
    }

    .btn-larger:active,
    .btn-larger.active,
    .open .dropdown-toggle.btn-larger {
      background-image: none;
    }

    .btn-larger.disabled,
    .btn-larger[disabled],
    fieldset[disabled] .btn-larger,
    .btn-larger.disabled:hover,
    .btn-larger[disabled]:hover,
    fieldset[disabled] .btn-larger:hover,
    .btn-larger.disabled:focus,
    .btn-larger[disabled]:focus,
    fieldset[disabled] .btn-larger:focus,
    .btn-larger.disabled:active,
    .btn-larger[disabled]:active,
    fieldset[disabled] .btn-larger:active,
    .btn-larger.disabled.active,
    .btn-larger[disabled].active,
    fieldset[disabled] .btn-larger.active {
      border-color: #AEA8D3;
      background-color: #AEA8D3;
    }

    .btn-larger .badge {
      color: #AEA8D3;
      background-color: #fff;
    }

    div#form {
      color: #fff;
      background-attachment: scroll;
      background: #1c1e21 url(https://berkas.dpr.go.id/mooc/assets/images/JKA_5864.JPG);
      background-position: center center;
      background-repeat: none;
      -webkit-background-size: cover;
      -moz-background-size: cover;
      background-size: cover;
      -o-background-size: cover;
      min-height: 100%;

    }

    #userform {
      background: rgba(0, 0, 0, 0.8);
      margin: 20px 0 20px 0
    }

    @media (min-width: 768px) {
      #userform {
        background: rgba(0, 0, 0, 0.8);
        margin: 50px 0 20px 0
      }
    }

    #userform .nav-tabs.nav-justified>li>a {
      text-transform: uppercase;
      font-size: 20px;
      color: #F7CA18;
      background-color: rgba(90, 90, 90, 0.5);
    }

    #userform .nav-tabs.nav-justified>.active>a,
    #userform .nav-tabs.nav-justified>.active>a:hover,
    #userform .nav-tabs.nav-justified>.active>a:focus {
      border: 0;
      background: #F7CA18;
      color: white;
      border-radius: 0;
    }

    #userform .nav-tabs>li>a {
      border: 0px solid transparent;
      border-radius: 0
    }

    #userform .nav-tabs.nav-justified>li>a:hover {
      background: #F7CA18;
      color: #FFF;
      border-radius: 0;
      border: 0;
      -webkit-transition: all .6s;
      -moz-transition: all .6s;
      transition: all .6s;
    }

    #userform .nav-tabs {
      border-bottom: 0px solid #ddd;
    }

    #userform .tab-pane h2 {
      margin: 10px 0;
      color: #FFF;
    }

    #userform .tab-pane p.lead {
      margin-top: 20px;
    }

    #userform .tab-content {
      padding: 20px
    }

    #userform .form-group {
      margin-bottom: 0px;
      color: #FFF;
    }

    .mrgn-30-top {
      margin-top: 30px
    }
  </style>

</head>

<body>
  <!-- partial:index.partial.html -->
  <html lang="en">

  <head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  </head>

  <body>

    <?= $this->layout()->content; ?>

  </body>

</html>