<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>MOOC Admin - DPR RI</title>

	<?= $this->headScript(); ?>
	<?= $this->headLink(); ?>

	<script type="text/javascript">
		var DecimalSeparator = ",";
		var ThousandSeparator = ".";
		var CurrencyDecimalDigits = 0;

		$(document).ready(function() {
			/** 
			 * Build menu 
			 */
			$('ul.t_a_ui_mega_menu li.sub').css({
				'opacity': '0'
			});
			$('ul.t_a_ui_mega_menu li').hoverIntent({
				sensitivity: 2,
				interval: 100,
				over: megaHoverOver,
				timeout: 200,
				out: megaHoverOut
			});
		});
	</script>
</head>

<?
$auth = Zend_Auth::getInstance()->getIdentity();
$peran = $auth->peran;
$username = $auth->nama;
?>

<body>
	<div id="container">
		<!-- header -->
		<div id="header">
			<div id="top"></div>
			<div id="nav-bar">
				<div id="topnav-bar">
					<div id="topleft">
						<ul id="topnav">

							<!-- <li><a class="home" href="/admin"><img width=60 src="https://w7.pngwing.com/pngs/147/513/png-transparent-learning-management-system-course-computer-icons-educational-technology-others-miscellaneous-angle-text.png"></a></li> -->
							<!-- <li><a class="home" href="/admin"><img src="<?= $this->url_statik; ?>/images/admin/logoapp-<?= $this->domain; ?>.png"></a></li> -->
						</ul>
					</div>
					<div id="topright">
						<ul id="topnav">

							<li><a href="/login/logout">Log Out</a></li>
							<li id="help"><a href="http://portal.dpr.go.id">&nbsp;Portal&nbsp;</a></li>
						</ul>
					</div>
					<!-- START Menu -->
					<div id="menu">
						<ul class="t_a_ui_mega_menu">
							<? if ($peran == 'admin' || $peran == 'super' || $peran == 'user') { ?>
								<li>
									<a href="#">Login As 📟</a>
									<a style="text-shadow: 2px 2px 4px #ffffff; color: white;   ">ADMIN</a>
									<div style="opacity: 0; display: none; width: 700px;" class="sub">
										<div style="margin: 0px;" class="row">
											<ul>
												<li><a href="/index" title="Visitor">Pengunjung [Visitor]</a></li>
												<? if ($auth->id_admin !== NULL) { ?>
													<li><a href="/admin/index" title="Administrator">Login as [Administrator]</a></li>
												<? }
												if ($auth->id_coach !== NULL) { ?>
													<li><a href="/coach/index" title="Coach">Login as [Coach]</a></li>
												<? }
												if ($auth->id_mentor !== NULL) { ?>
													<li><a href="/mentor/index" title="Mentor">Login as [Mentor]</a></li>
												<? }
												if ($auth->id_pengajar !== NULL) { ?>
													<li><a href="/pengajar/index" title="Pengajar">Login as [Pengajar]</a></li>
												<? }
												if ($auth->id_penilai !== NULL) { ?>
													<li><a href="/penilai/index" title="Penguji">Login as [Penguji]</a></li>
												<? }
												if ($auth->id_peserta !== NULL) { ?>
													<li><a href="/peserta/index" title="Peserta">Login as [Peserta]</a></li>
												<? } ?>
											</ul>
										</div>
								</li>
								<li>
									<a href="#">MOOC</a>
									<div style="opacity: 0; display: none; width: 700px;" class="sub">
										<div style="margin: 0px;" class="row">
											<ul>
												<li><span>Prasmanan - Admin</span></li>
												<li><a href="/admin/kegiatan/index" title="Workshop, Webinar, FGD, CBTW">Daftar Kegiatan</a></li>
												<li><a href="/admin/pelatihan/index" title="Pelatihan">Daftar Pelatihan</a></li>
												<li><a href="/admin/batch/index" title="Batch">Daftar Batch</a></li>
												<li><a href="/admin/silabus/index" title="Agenda">Daftar Agenda</a></li>
												<li><a href="/admin/materi-silabus/index" title="Mata Pelatihan">Daftar Mata Pelatihan</a></li>
												<li><a href="/admin/forum-diskusi/index" title="Forum Diskusi">Daftar Forum Diskusi</a></li>
												<li><a href="/admin/nontes/index" title="Nontes">Daftar Nontes</a></li>
												<li><a href="/admin/penugasan/index" title="Penugasan">Daftar Penugasan</a></li>
												<li><a href="/admin/nilai-mentoring/index" title="Nilai">Daftar Nilai</a></li>
												<li><a href="/admin/sertifikat/index" title="Sertifikat">Daftar Sertifikat</a></li>
												<li><a href="/admin/progress/index" title="Progres">Daftar Progress</a></li>
												<li><a href="/admin/riwayat/index" title="Riwayat Pelatihan">Daftar Riwayat Pelatihan</a></li>
											</ul>
											<ul>
												<li><span>Referensi Role</span></li>
												<li><a href="/admin/admin/index" title="Admin">Daftar Admin</a></li>
												<li><a href="/admin/peserta/index" title="Peserta">Daftar Peserta ASN DPR-RI</a></li>
												<li><a href="/admin/pesertanonasn/index" title="Peserta">Daftar Peserta Selain ASN DPR-RI</a></li>
												<li><a href="/admin/pengajar/index" title="Pengajar">Daftar Pengajar</a></li>
												<li><a href="/admin/coach/index" title="Coach">Daftar Coach</a></li>
												<li><a href="/admin/mentor/index" title="Mentor">Daftar Mentor</a></li>
												<li><a href="/admin/penilai/index" title="Penguji">Daftar Penguji</a></li>
												<!-- <li><a href="/peserta/peserta/index" title="Home">Peserta</a></li> -->
											</ul>
											<ul>
												<li><span>Tampilan</span></li>
												<li><a href="/admin/banner/index" title="Banner">Daftar Banner</a></li>
											</ul>
										</div>
								</li>

								<!-- <li>
								<a href="#">MENU</a>
								<div style="opacity: 0; display: none; width: 700px;" class="sub">
								<div style="margin: 0px;" class="row">
									<ul>
										<li><span>Artikel</span></li>
										<li><a href="/admin/tipe-artikel/index" title="Tipe Artikel">Daftar Tipe Artikel</a></li>
										<li><a href="/admin/tipe-artikel/add" title="Tipe Artikel"><i>Tambah Tipe Artikel</i></a></li>
										<li><a href="/admin/subtipe-artikel/index" title="Subtipe Artikel">Daftar Subtipe Artikel</a></li>
										<li><a href="/admin/subtipe-artikel/add" title="Subtipe Artikel"><i>Tambah Subtipe Artikel</i></a></li>
										<li><a href="/admin/artikel/index" title="Artikel">Daftar Artikel</a></li>
										<li><a href="/admin/artikel/add" title="Artikel"><i>Tambah Artikel</i></a></li>
									</ul>
									<ul>
										<li><span>Website</span></li>
										<li><a href="/admin/faq/index" title="FAQ">Daftar FAQ</a></li>
										<li><a href="/admin/faq/add" title="FAQ"><i>Tambah FAQ</i></a></li>
										<li><a href="/admin/konten-setting/index" title="Konten Setting">Daftar Konten Setting</a></li>
										<li><a href="/admin/konten-setting/add" title="Konten Setting"><i>Tambah Konten Setting</i></a></li>
										<li><a href="/admin/konten-statis/index" title="Konten Statis">Daftar Konten Statis</a></li>
										<li><a href="/admin/konten-statis/add" title="Konten Statis"><i>Tambah Konten Statis</i></a></li>
										<li><a href="/admin/kontak/index" title="Kontak">Daftar Kontak</a></li>
										<li><a href="/admin/kontak/add" title="Kontak"><i>Tambah Kontak</i></a></li>
									</ul>
									<ul>
										<li><span>Laporan</span></li>
										<li><a href="/admin/laporan-kustom" title="Laporan">Laporan Kustom</a></li>
									</ul>
								</div>
							</li> -->

								<!-- <li>
								<a href="#">TESTER</a>
								<div style="opacity: 0; display: none; width: 700px;" class="sub">
								<div style="margin: 0px;" class="row">
									<ul>
										<li><span>Blank Page</span></li>
										<li><a href="/admin/tester/index" title="Tester"><i>Tester Page</i></a></li>
									</ul>
								</div>
							</li> -->
							<? } ?>
						</ul>
					</div>
					<!-- END Menu -->
				</div>
			</div>
		</div>
		<!-- header -->

		<!-- content -->
		<div id="content-container">
			<div id="content-block" class="single">
				<?= $this->layout()->content; ?>
			</div>
		</div>
		<div style="clear: both;"></div>
		<!-- content -->

		<!-- footer -->
		<div id="footer">
			<div style="clear: both;"></div>
			<?= $this->copyright; ?>
		</div>
		<!-- footer -->
	</div>
</body>
</html>