<script type="text/javascript">
	$(document).ready(function() {
		$("#compose").validate();
	});
	$(function() {
		$("#tanggal_lahir").datepicker({
			yearRange: "-11:+0",
			changeYear: "true",
			changeMonth: "true",
			dateFormat: "dd-mm-yy"
		});
		
	});
</script>

<div class="content-header"></div>
<div class="UI_Header_Title">
	<h1><?=$this->avatar;?>Tambah Peserta Selain ASN DPR RI</h1>
	<div class="header_nav_links"><a href="/admin/pesertanonasn/index">Back to Daftar Peserta Selain ASN DPR RI</a></div>
</div>
<div class="clear"></div>
<form id="compose" name="compose" method="post" action="" enctype="multipart/form-data">
	<div class="tabular">
	
		
		<p>
			<label class="left" for="username">Username</label>
			<input type="text" id="username" class="event-message" wrap="soft" name="username" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;"> <?= $this->username ?>
		</p>
		<p>
			<label class="left" for="password">Password</label>
			<input type="password" id="passowrd" class="event-message" wrap="soft" name="password" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;"> <?= $this->password ?>
		</p>
		<p>
			<label class="left" for="nama">Nama</label>
			<input type="text" id="nama" class="event-message" wrap="soft" name="nama" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;"> <?= $this->nama ?>
		</p>
		<p>
			<label class="left" for="identitas">NIK</label>
			<input type="number" id="identitas" class="event-message" wrap="soft" name="identitas" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;"> <?= $this->identitas ?>
		</p>
		<p>
			<label class="left" for="tanggal_lahir">Tanggal Lahir</label>
			<input type="text" id="tanggal_lahir" class="datepicker required" wrap="soft" name="tanggal_lahir" value="<?= date('d-m-Y'); ?>" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;"> <?= $this->tanggal_lahir ?>
		</p>
		<p>
			<label class="left" for="tempat_lahir">Tempat Lahir</label>
			<input type="text" id="tempat_lahir" class="event-message" wrap="soft" name="tempat_lahir" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;"> <?= $this->tempat_lahir ?>
		</p>
		<p>
			<label class="left" for="pekerjaan">Jenis Kelamin</label>
			<input type="text" id="pekerjaan" class="event-message" wrap="soft" name="pekerjaan" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;"> <?= $this->jenis_kelamin ?>
		</p>
		<p>
			<label class="left" for="pekerjaan">Pekerjaan</label>
			<input type="text" id="pekerjaan" class="event-message" wrap="soft" name="pekerjaan" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;"> <?= $this->pekerjaan ?>
		</p>
		<p>
			<label class="left" for="kewarganegaraan">Kewarganegaraan</label>
			<input type="text" id="kewarganegaraan" class="event-message" wrap="soft" name="kewarganegaraan" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;"> <?= $this->kewarganegaraan ?>
		</p>
		<p>
			<label class="left" for="email">Email</label>
			<input type="email" id="email" class="event-message" wrap="soft" name="email" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;"> <?= $this->email ?>
		</p>
		<p>
			<label class="left" for="no_telp">No Telp</label>
			<input type="number" id="no_telp" class="event-message" wrap="soft" name="no_telp" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;"> <?= $this->no_telp ?>
		</p>
		<p>
			<label class="left" for="file_name">Foto Peserta Non ASN</label> 
			<input type="file" accept="image/*" id="file_name" name="file_name">
		</p>
		
		<p class="savecancel"><label class="UIbutton-small"><input type="submit" value="Simpan" class=""/></label><a href="/admin/pesertanonasn/index" class="UIbutton-small">Batal</a></p>
	</div>
</form>
<div style="clear:both"></div>