<?php 
    $progress = [];
    
    foreach($this->batch as $val) { 
        foreach($this->progress as $prog) {
            if($val->id == $prog->id_batch) {

                $progress[] = array(
                    'id_batch' => $val->id,
                    'id_peserta' => $prog->id_peserta,
                    'status_progress' => $prog->status_progress,
                );
                
                break;
            }
        }
    }
    
?>

<link rel="stylesheet" href="https://berkas.dpr.go.id/mooc/assets/css/pelatihan.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.6/dist/sweetalert2.min.css" />
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.6/dist/sweetalert2.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

<!-- sidebar -->
<div class="area"></div>
<nav class="main-menu background-content" style="max-width: 100vw;" onmouseover="changeMarginLeft(20)" onmouseout="changeMarginLeft(0)">
    <ul class="background-content">
        <li class="has-subnav">
            <a href="/pesertanonasn/index/">
                <img src="https://berkas.dpr.go.id/mooc/assets/images/dashboardblack.png" alt="" class="icon" style="width: 20px; height: 20px;">
                <span class="nav-text">Dashboard</span>
            </a>
        </li>

        <li class="has-subnav active">
            <a href="/pesertanonasn/pelatihan">
                <img src="https://berkas.dpr.go.id/mooc/assets/images/pelatihan-white.png" alt="" class="icon" style="width: 20px; height: 20px;">
                <span class="nav-text">Pelatihan</span>
            </a>    
        </li>

        <li class="has-subnav">
            <a href="/pesertanonasn/forum">
                <img src="https://berkas.dpr.go.id/mooc/assets/images/forum-black.png" alt="" class="icon" style="width: 20px; height: 20px;">
                <span class="nav-text">Forum</span>
            </a>
        </li>

        <li class="has-subnav">
            <a href="/pesertanonasn/riwayat">
                <img src="https://berkas.dpr.go.id/mooc/assets/images/hourglass-split.svg" alt="" class="icon" style="width: 20px; height: 20px;">
                <span class="nav-text">Riwayat</span>
            </a>
        </li>
        
    </ul>
</nav>
<!-- end sidebar -->

<!-- pelatihan -->
<? if(count($this->batch) > 0) { ?>
    echo'<section class="container-pelatihan d-flex flex-column rounded-4" style="max-width: 80vw; margin-left: 10%; padding-top: 130px;">
            <div class="mb-2">
                <p class="fs-3 fw-bold">Pelatihan</p>
            </div> 

            <div class="content-pelatihan d-flex flex-column justify-content-start rounded-4" style="width: 100%;">
                <div class="row content-seacrh-filter m-0 mb-3 d-flex flex-row justify-content-between pe-3" style="width: 100%;">
                    <!-- filter -->
                    <div class="col-md-6 content-filter p-0 d-flex flex-row">
                        <div class="dropdown me-4 p-0">
                            <button class="dropdown-toggle background-content m-0 btn border-0" style="background-color: #E5E7E9; box-shadow: 2.0px 4.0px 4.0px hsl(0deg 0% 0% / 0.38);" type="button" data-bs-toggle="dropdown" aria-expanded="false">Tipe Pelatihan</button>
                            <ul class="dropdown-menu background-content">
                                <li><button id="btn-classical" class="dropdown-item rounded-0" onclick="filterCard('classical')">Classical</button></li>
                                <li><button id="btn-non-classical" class="dropdown-item rounded-0" onclick="filterCard('non-classical')">Non Classical</button></li>
                                <li><button id="btn-blended" class="dropdown-item rounded-0" onclick="filterCard('blended')">Blended</button></li>
                            </ul>
                        </div>
                    
                        <div class="dropdown">
                            <button class="dropdown-toggle background-content btn border-0" style="background-color: #E5E7E9; box-shadow: 2.0px 4.0px 4.0px hsl(0deg 0% 0% / 0.38);" type="button" data-bs-toggle="dropdown" aria-expanded="false">Urutkan</button>
                            <ul class="dropdown-menu background-content">
                                <li><button id="btn-ascending" class="dropdown-item rounded-0" onclick="sortCard('A - Z')">A - Z</button></li>
                                <li><button id="btn-descending" class="dropdown-item rounded-0" onclick="sortCard('Z - A')">Z - A</button></li>
                            </ul>
                        </div>
                    </div>

                    <!-- search -->
                    <div class="col-md-6 content-search pe-2">
                        <form class="nav-item d-flex search-form m-0" style="height: 100%" role="search">
                            <div class="box-pelatihan">
                                <form name="search">
                                    <input type="text" id="search-input" class="input-pelatihan text-secondary background-content" style="width: 70%; background-color: #E5E7E9;" name="txt" placeholder="Cari disini...">
                                    
                                    <img src="https://berkas.dpr.go.id/mooc/assets/images/search.png" alt="" style="width: 25px; height: 25px;">
                                </form>
                            </div>
                        </form>
                    </div>
                </div>

                <!-- card -->
                <div class="content-card rounded-4 pe-3" style="width: 100%;">
                    <div id="card-pelatihan-container" class="row m-0 d-flex flex-row flex-wrap gap-3" style="width: 100%">
                        <!-- content card pelatihan -->
                    </div>
                </div>
            </div>
        </section>';
<?  } else {
        echo'<section class="container-pelatihan d-flex flex-column rounded-4" style="max-width: 80vw; margin-left: 10%; padding-top: 150px;">
                <div class="mb-2">
                    <p class="fs-3 fw-bold">Pelatihan</p>
                </div>

                <div class="content-pelatihan-kosong d-flex flex-column justify-content-start align-items-center rounded-4" style="width: 100%; box-shadow: 2.0px 4.0px 4.0px hsl(0deg 0% 0% / 0.38);">
                    <div class="m-0 d-flex justify-content-center p-3" style="width: 100%;">
                        <div class="rounded-circle" style="width: 7em; height: 7em; background-color: #D9D9D9"></div>
                    </div>
                    <p class="text-center fs-3 fw-bold">Sangat disayangkan</p>
                    <p class="text-center" style="width: 100%;">Kamu belum memiliki program pelatihan, pilih pelatihan sesuai keinginanmu sekarang juga!</p>
                    <div class="rounded-4 text-center p-1 mb-5" style="background-color: #D4A216; overflow: hidden">
                        <a href="/" class="border border-0 text-light p-1 px-2 text-decoration-none" style="background-color: #D4A216;">Pilih pelatihan sekarang</a>
                    </div>
                </div>
            </section>';
    }
?>
<!-- end pelatihan -->

<script>
    // search data
    document.addEventListener('DOMContentLoaded', function() {
        let batch = <?php echo json_encode($this->batch); ?>;
        let progress = <?php echo json_encode($progress); ?>;

        console.log(batch);
        let cardPelatihanContainer = document.getElementById('card-pelatihan-container');

        // Function generate card pelatihan
        function generateCardPelatihanContainer(data) {
            cardPelatihanContainer.innerHTML = '';

            data.forEach(function(item) {
                let card = document.createElement('div');
                card.classList.add('col-md-4', 'sub-content-card', 'background-content', 'rounded-4', 'p-2');
                card.style.width = '32%';
                card.style.height = '450px';
                card.style.backgroundColor = '#E5E7E9';
                card.style.boxShadow = '2.0px 4.0px 4.0px hsl(0deg 0% 0% / 0.38)';

                let mentorName = item.nama_mentor !== null ? item.nama_mentor : "";
                let cardPelatihanContent = '<img src="https://berkas.dpr.go.id/mooc/thumbkelas/' + item.sampul_pelatihan + '" alt="" class="rounded-4 overflow-hidden mb-2" style="width: 100%; height: 250px; object-fit: cover;">' +
                    '<p class="text-start text-secondary m-1" style="font-size: 14px;">' + mentorName + '</p>';

                    let lanjut = '';
                    let progressStatus = "";

                    progress.forEach(function(prog) {
                        if (item.id == prog.id_batch) {
                            progressStatus = prog.status_progress.split("-");
                            if (progressStatus[0] === 'Terdaftar') {
                                lanjut = '#';
                            } else if (progressStatus[0] === 'Peserta') {
                                lanjut = '/pesertanonasn/pelatihan-saya/pretest/id/' + item.id;
                            } else if (progressStatus[0] === 'Pretest') {
                                lanjut = '/pesertanonasn/pelatihan-saya/pretest/id/' + item.id;
                            } else if (progressStatus[0] === 'Materi') {
                                lanjut = '/pesertanonasn/pelatihan-saya/belajar/id/' + item.id + '/silabus/' + progressStatus[1] + '/materi/' + progressStatus[2];
                            } else if (progressStatus[0] === 'Postest') {
                                lanjut = '/pesertanonasn/pelatihan-saya/postest/id/' + item.id;
                            } else if (progressStatus[0] === 'Mentoring') {
                                lanjut = '/pesertanonasn/pelatihan-saya/mentoring/id/' + item.id;
                            } else if (progressStatus[0] === 'Penugasan') {
                                lanjut = '/pesertanonasn/pelatihan-saya/penugasan/id/' + item.id;
                            } else if (progressStatus[0] === 'Penilaian') {
                                lanjut = '/pesertanonasn/pelatihan-saya/penugasan/id/' + item.id;
                            } else if (progressStatus[0] === 'Selesai') {
                                lanjut = '/pesertanonasn/riwayat';;
                            } else if (progressStatus[0] === 'Sertifikat') {
                                lanjut = '/pesertanonasn/pelatihan-saya/sertifikat/id/' + item.id;;
                            }
                        }
                    });

                    if (progressStatus[0] == "Terdaftar") {
                        cardPelatihanContent += '<button type="button" id="latihan-disable" class="title-pelatihan m-1 text-dark text-start fs-4 fw-bold border-0 bg-transparent" style="width: 100%; z-index: 1; cursor: pointer;">' + (item.nama_pelatihan.length > 12 ? item.nama_pelatihan.substr(0, 20) + '...' : item.nama_pelatihan) + '<i class="bi bi-lock-fill text-secondary"></i></button>';

                    } else {
                        cardPelatihanContent += '<a href="'+ lanjut +'" class="m-0 text-dark text-start fs-4 fw-bold text-decoration-none" style="width: 100%; z-index: 1">' + (item.nama_pelatihan.length > 12 ? item.nama_pelatihan.substr(0, 20) + '...' : item.nama_pelatihan) + '</a>';
                    }

                    cardPelatihanContent += '<div class="d-flex flex-row align-items-center my-2">' +
                        '<img src="https://berkas.dpr.go.id/mooc/assets/images/book-variant-grey.png" alt="" class="me-2" style="width: 20px; height: 20px;">' +
                        '<p style="font-size: 14px;" class="m-0 text-secondary text-start">' + item.nama_pelatihan.length + ' Kelas</p>' +
                        '<img src="https://berkas.dpr.go.id/mooc/assets/images/account-multiple-black.png" alt="" class="me-2" style="width: 20px; height: 20px; margin-left: 27px;">' +
                        '<p style="font-size: 14px" class="m-0 text-secondary text-start">' + (item.kuota_peserta ? item.kuota_peserta : '0') + ' Peserta</p>' +
                    '</div>' +
                    '<div class="d-flex flex-row align-items-center mb-4">' +
                        '<img src="https://berkas.dpr.go.id/mooc/assets/images/equalizer.png" alt="" class="me-2" style="width: 20px; height: 20px;">' +
                        '<p style="font-size: 14px" class="m-0 text-secondary text-start me-3">Beginner</p>' +
                        '<img src="https://berkas.dpr.go.id/mooc/assets/images/clock.png" alt="" class="me-2" style="width: 20px; height: 20px;">' +
                        '<p style="font-size: 14px" class="m-0 text-secondary text-start"> 20 Jam </p>' +
                    '</div>';

                card.innerHTML = cardPelatihanContent;
                cardPelatihanContainer.appendChild(card);
            });

            // alert waiting class
            let btnLatihanDisable = document.querySelectorAll('#latihan-disable');
            if(btnLatihanDisable) {
                btnLatihanDisable.forEach(function(element) {
                    element.addEventListener('click', function() {
                        Swal.fire({
                            title: 'Maaf',
                            text: 'Pelatihan anda sedang dalam proses persetujuan admin dan coach.',
                            icon: 'error',
                            confirmButtonText: 'OK',
                            confirmButtonColor: '#4CAF50'
                        });
                    });
                });
            }
            // end alert waiting class
        }
        generateCardPelatihanContainer(batch);

        // function filter data 
        let searchInput = document.getElementById('search-input');
        searchInput.addEventListener('input', filterCardPelatihanContainer);

        function filterCardPelatihanContainer() {
            let inputValue = searchInput.value.toLowerCase().trim();

            // filter dan ambil nama pelatihan
            let filteredBatch = batch.filter(function(item) {
                return item.nama_pelatihan.toLowerCase().includes(inputValue);
            });

            if (filteredBatch.length === 0) {
                cardPelatihanContainer.innerHTML = '<p class="mt-5 fs-4 text-center text-danger fst-italic">Pelatihan tidak ditemukan</p>';
            } else {
                generateCardPelatihanContainer(filteredBatch);
            }
        }        
    });
    // end search data

    // sort data
    function sortCard(sortType) {
        let batch = <?php echo json_encode($this->batch); ?>;
        let progress = <?php echo json_encode($progress); ?>;
        let cardPelatihanContainer = document.getElementById('card-pelatihan-container');

        // Menghapus card pelatihan sebelumnya
        while (cardPelatihanContainer.firstChild) {
            cardPelatihanContainer.removeChild(cardPelatihanContainer.firstChild);
        }
        
        if (sortType === "A - Z") {
            batch.sort(function(a, b) {
                // localeCompare untuk membandingkan properti nama_pelatihan dari dua elemen dalam array (a dan b). 
                return a.nama_pelatihan.localeCompare(b.nama_pelatihan);
            });
        } else if (sortType === "Z - A") {
            batch.sort(function(a, b) {
                return b.nama_pelatihan.localeCompare(a.nama_pelatihan);
            });
        }
    
        batch.forEach(function(item) {
            let card = document.createElement('div');
            card.classList.add('col-md-4', 'sub-content-card', 'background-content', 'rounded-4', 'p-2');
            card.style.width = '32%';
            card.style.height = '450px';
            card.style.backgroundColor = '#E5E7E9';
            card.style.boxShadow = '2.0px 4.0px 4.0px hsl(0deg 0% 0% / 0.38)';

            let mentorName = item.nama_mentor !== null ? item.nama_mentor : "";
            let cardPelatihanContent = 
                '<img src="https://berkas.dpr.go.id/mooc/thumbkelas/' + item.sampul_pelatihan + '" alt="" class="rounded-4 overflow-hidden mb-2" style="width: 100%; height: 250px; object-fit: cover;">' +
                '<p class="text-start text-secondary m-1" style="font-size: 14px;">' + mentorName + '</p>';

                let lanjut = '';
                let progressStatus = "";

                progress.forEach(function(prog) {
                    if (item.id == prog.id_batch) {
                        progressStatus = prog.status_progress.split("-");
                        if (progressStatus[0] === 'Terdaftar') {
                            lanjut = '#';
                        } else if (progressStatus[0] === 'Peserta') {
                            lanjut = '/peserta/pelatihan-saya/pretest/id/' + item.id;
                        } else if (progressStatus[0] === 'Pretest') {
                            lanjut = '/peserta/pelatihan-saya/pretest/id/' + item.id;
                        } else if (progressStatus[0] === 'Materi') {
                            lanjut = '/peserta/pelatihan-saya/belajar/id/' + item.id + '/silabus/' + progressStatus[1] + '/materi/' + progressStatus[2];
                        } else if (progressStatus[0] === 'Postest') {
                            lanjut = '/peserta/pelatihan-saya/postest/id/' + item.id;
                        } else if (progressStatus[0] === 'Mentoring') {
                            lanjut = '/peserta/pelatihan-saya/mentoring/id/' + item.id;
                        } else if (progressStatus[0] === 'Penugasan') {
                            lanjut = '/peserta/pelatihan-saya/penugasan/id/' + item.id;
                        } else if (progressStatus[0] === 'Penilaian') {
                            lanjut = '/peserta/pelatihan-saya/penugasan/id/' + item.id;
                        } else if (progressStatus[0] === 'Selesai') {
                            lanjut = '/peserta/riwayat';
                        } else if (progressStatus[0] === 'Sertifikat') {
                            lanjut = '/peserta/pelatihan-saya/sertifikat/id/' + item.id;
                        }
                    }
                });

                if (progressStatus[0] == "Terdaftar") {
                    cardPelatihanContent += '<button type="button" id="latihan-disable" class="title-pelatihan m-1 text-dark text-start fs-4 fw-bold border-0 bg-transparent" style="width: 100%; z-index: 1; cursor: pointer;">' + (item.nama_pelatihan.length > 12 ? item.nama_pelatihan.substr(0, 20) + '...' : item.nama_pelatihan) + '<i class="bi bi-lock-fill text-secondary"></i></button>';
                } else {
                    cardPelatihanContent += '<a href="'+ lanjut +'" class="m-0 text-dark text-start fs-4 fw-bold text-decoration-none" style="width: 100%; z-index: 1">' + (item.nama_pelatihan.length > 12 ? item.nama_pelatihan.substr(0, 20) + '...' : item.nama_pelatihan) + '</a>';
                }

                cardPelatihanContent += 
                '<div class="d-flex flex-row align-items-center my-2">' +
                    '<img src="https://berkas.dpr.go.id/mooc/assets/images/book-variant-grey.png" alt="" class="me-2" style="width: 20px; height: 20px;">' +
                    '<p style="font-size: 14px;" class="m-0 text-secondary text-start">' + item.nama_pelatihan.length + ' Kelas</p>' +
                    '<img src="https://berkas.dpr.go.id/mooc/assets/images/account-multiple-black.png" alt="" class="me-2" style="width: 20px; height: 20px; margin-left: 27px;">' +
                    '<p style="font-size: 14px" class="m-0 text-secondary text-start">' + (item.kuota_peserta ? item.kuota_peserta : '0') + ' Peserta</p>' +
                '</div>' +
                '<div class="d-flex flex-row align-items-center mb-4">' +
                    '<img src="https://berkas.dpr.go.id/mooc/assets/images/equalizer.png" alt="" class="me-2" style="width: 20px; height: 20px;">' +
                    '<p style="font-size: 14px" class="m-0 text-secondary text-start me-3">Beginner</p>' +
                    '<img src="https://berkas.dpr.go.id/mooc/assets/images/clock.png" alt="" class="me-2" style="width: 20px; height: 20px;">' +
                    '<p style="font-size: 14px" class="m-0 text-secondary text-start"> 20 Jam </p>' +
                '</div>';

            card.innerHTML = cardPelatihanContent;
            cardPelatihanContainer.appendChild(card);
        });

        // alert waiting class
        let btnLatihanDisable = document.querySelectorAll('#latihan-disable');
        if(btnLatihanDisable) {
            btnLatihanDisable.forEach(function(element) {
                element.addEventListener('click', function() {
                    Swal.fire({
                        title: 'Maaf',
                        text: 'Pelatihan anda sedang dalam proses persetujuan admin dan coach.',
                        icon: 'error',
                        confirmButtonText: 'OK',
                        confirmButtonColor: '#4CAF50'
                    });
                });
            });
        }
        // end alert waiting class
    }

    let btnAscending = document.getElementById('btn-ascending');
    let btnDescending = document.getElementById('btn-descending');
    let searchValue = document.getElementById('search-input');

    btnAscending.addEventListener('click', function() {
        sortCard('A - Z');
        searchValue.value = "";
    });

    btnDescending.addEventListener('click', function() {
        sortCard('Z - A');
        searchValue.value = "";
    });
    // end sort data

    // filter data
    function filterCard(dataFilter) {
        let batch = <?php echo json_encode($this->batch); ?>;
        let progress = <?php echo json_encode($progress); ?>;
        let cardPelatihanContainer = document.getElementById('card-pelatihan-container');

        // Menghapus card pelatihan sebelumnya
        while (cardPelatihanContainer.firstChild) {
            cardPelatihanContainer.removeChild(cardPelatihanContainer.firstChild);
        }

        // kondisi ketika filter kosong
        let emptyData = batch.filter(function(item) {
            return item.tipe_pelatihan === dataFilter;
        });

        if (emptyData.length === 0) {
            let textEmptyData = document.createElement('p');
            textEmptyData.classList.add('mt-5', 'fs-4', 'text-center', 'text-danger', 'fst-italic');
            textEmptyData.textContent = 'Pelatihan tidak ditemukan';
            cardPelatihanContainer.appendChild(textEmptyData);
            return;
        }

        batch.forEach(function(item) {
            if (item.tipe_pelatihan === dataFilter) {
                let prog = progress.find(function(prog) {
                    return item.id == prog.id_batch;
                });

                if(prog) {
                    let card = cardTipePelatihan(item, prog);
                    cardPelatihanContainer.appendChild(card);
                }
            }
        });

        // alert waiting class
        let btnLatihanDisable = document.querySelectorAll('#latihan-disable');
        if(btnLatihanDisable) {
            btnLatihanDisable.forEach(function(element) {
                element.addEventListener('click', function() {
                    Swal.fire({
                        title: 'Maaf',
                        text: 'Pelatihan anda sedang dalam proses persetujuan admin dan coach.',
                        icon: 'error',
                        confirmButtonText: 'OK',
                        confirmButtonColor: '#4CAF50'
                    });
                });
            });
        }
        // end alert waiting class
    }

    function cardTipePelatihan(item, prog) {
        let card = document.createElement('div');
        card.classList.add('col-md-4', 'sub-content-card', 'background-content', 'rounded-4', 'p-2');
        card.style.width = '32%';
        card.style.height = '450px';
        card.style.backgroundColor = '#E5E7E9';
        card.style.boxShadow = '2.0px 4.0px 4.0px hsl(0deg 0% 0% / 0.38)';

        let mentorName = item.nama_mentor !== null ? item.nama_mentor : "";
        let cardPelatihanContent = 
            '<img src="https://berkas.dpr.go.id/mooc/thumbkelas/' + item.sampul_pelatihan + '" alt="" class="rounded-4 overflow-hidden mb-2" style="width: 100%; height: 250px; object-fit: cover;">' +
            '<p class="text-start text-secondary m-1" style="font-size: 14px;">' + mentorName + '</p>';

            let lanjut = '';
            let progressStatus = "";

            if (item.id == prog.id_batch) {
                progressStatus = prog.status_progress.split("-");
                if (progressStatus[0] === 'Terdaftar') {
                    lanjut = '#';
                } else if (progressStatus[0] === 'Peserta') {
                    lanjut = '/peserta/pelatihan-saya/pretest/id/' + item.id;
                } else if (progressStatus[0] === 'Pretest') {
                    lanjut = '/peserta/pelatihan-saya/pretest/id/' + item.id;
                } else if (progressStatus[0] === 'Materi') {
                    lanjut = '/peserta/pelatihan-saya/belajar/id/' + item.id + '/silabus/' + progressStatus[1] + '/materi/' + progressStatus[2];
                } else if (progressStatus[0] === 'Postest') {
                    lanjut = '/peserta/pelatihan-saya/postest/id/' + item.id;
                } else if (progressStatus[0] === 'Mentoring') {
                    lanjut = '/peserta/pelatihan-saya/mentoring/id/' + item.id;
                } else if (progressStatus[0] === 'Penugasan') {
                    lanjut = '/peserta/pelatihan-saya/penugasan/id/' + item.id;
                } else if (progressStatus[0] === 'Penilaian') {
                    lanjut = '/peserta/pelatihan-saya/penugasan/id/' + item.id;
                } else if (progressStatus[0] === 'Selesai') {
                    lanjut = '/peserta/riwayat';
                } else if (progressStatus[0] === 'Sertifikat') {
                    lanjut = '/peserta/pelatihan-saya/sertifikat/id/' + item.id;
                }  
            };

            if (progressStatus[0] === 'Terdaftar') {
                lanjut = '#';
                cardPelatihanContent += '<button type="button" id="latihan-disable" class="title-pelatihan m-1 text-dark text-start fs-4 fw-bold border-0 bg-transparent" style="width: 100%; z-index: 1; cursor: pointer;">' + (item.nama_pelatihan.length > 12 ? item.nama_pelatihan.substr(0, 20) + '...' : item.nama_pelatihan) + '<i class="bi bi-lock-fill text-secondary"></i></button>';
            } else {
                cardPelatihanContent += '<a href="' + lanjut + '" class="m-0 text-dark text-start fs-4 fw-bold text-decoration-none" style="width: 100%; z-index: 1">' + (item.nama_pelatihan.length > 12 ? item.nama_pelatihan.substr(0, 20) + '...' : item.nama_pelatihan) + '</a>';
            }

            cardPelatihanContent += 
                '<div class="d-flex flex-row align-items-center my-2">' +
                    '<img src="https://berkas.dpr.go.id/mooc/assets/images/book-variant-grey.png" alt="" class="me-2" style="width: 20px; height: 20px;">' +
                    '<p style="font-size: 14px;" class="m-0 text-secondary text-start">' + item.nama_pelatihan.length + ' Kelas</p>' +
                    '<img src="https://berkas.dpr.go.id/mooc/assets/images/account-multiple-black.png" alt="" class="me-2" style="width: 20px; height: 20px; margin-left: 27px;">' +
                    '<p style="font-size: 14px" class="m-0 text-secondary text-start">' + (item.kuota_peserta ? item.kuota_peserta : '0') + ' Peserta</p>' +
                '</div>' +
                '<div class="d-flex flex-row align-items-center mb-4">' +
                    '<img src="https://berkas.dpr.go.id/mooc/assets/images/equalizer.png" alt="" class="me-2" style="width: 20px; height: 20px;">' +
                    '<p style="font-size: 14px" class="m-0 text-secondary text-start me-3">Beginner</p>' +
                    '<img src="https://berkas.dpr.go.id/mooc/assets/images/clock.png" alt="" class="me-2" style="width: 20px; height: 20px;">' +
                    '<p style="font-size: 14px" class="m-0 text-secondary text-start"> 20 Jam </p>' +
                '</div>';

            card.innerHTML = cardPelatihanContent;
            return card;
    }

    let btnClassical = document.getElementById('btn-classical');
    let btnNonClassical = document.getElementById('btn-non-classical');
    let btnBlended = document.getElementById('btn-blended');

    btnClassical.addEventListener('click', function() {
        filterCard('classical');
        searchValue.value = "";
    });

    btnNonClassical.addEventListener('click', function() {
        filterCard('non-classical');
        searchValue.value = "";
    });

    btnBlended.addEventListener('click', function() {
        filterCard('blended');
        searchValue.value = "";
    });
    // end filter data

    // progress bar
    let processing = document.querySelectorAll('.processing-bar');
    setTimeout(() => {
        processing.forEach(el => {
            el.style.opacity = 1;
            el.style.width = el.getAttribute('data-bar') + '%';
        })
    }, 500);
    // end progress bar

    // animation sidebar
    function changeMarginLeft(margin) {
        let containerPelatihan = document.querySelector('.container-pelatihan');
        if (margin === 0) {
            containerPelatihan.classList.remove('margin-left-20');
        } else {
            containerPelatihan.classList.add('margin-left-20');
        }
    }
    // end animation sidebar
</script>
