<style>
	.comment-body {
		overflow: hidden;
		line-height: normal;
		padding: 10px;
		margin-bottom: 5px;
		border: 1px solid #898121;
		border-radius: 5px;
		color: black;
		background-color: white;
	}

	.fn {
		font-style: normal;
		text-transform: capitalize;
		font-weight: 700;
	}

	.reply {
		float: right;
		border: 1.5px solid #d8d6d6;
		border-radius: 3px;
		color: #777;
		border: 1px solid #ccc;
		padding: 5px 15px;
		cursor: pointer;
		font-family: Open Sans;
		box-shadow: 0 1px 0 rgba(0, 0, 0, .08);
		background: #f8f8f8;
		font-weight: 700;
	}
</style>
<script type="text/javascript">
	$(document).ready(function() {
		$("#compose").validate();
	})
	
	function selectFields1(id, id, nama) {
		$('#id_pesertax').val(id);
		<?php $id_pesertax = "id"; ?>
		$('#nama_pesertax').val(nama);
		$.facebox.close();
	}

	function ClearFields1() {
		document.getElementById("id_pesertax").value = "";
		document.getElementById("nama_pesertax").value = "";
	}

	function changeRole(val) {
		$(".daftar-user").css("display", "none");
		if (val == "Mentor") {
			$("#daftar-mentor").show();
		} else if (val == "Peserta") {
			$("#daftar-peserta").show();
		}
		if (val == "Coach") {
			$("#daftar-coach").show();
			$('#id_user').val('<?= $this->id_coach; ?>');
		}
	}

	function addInput(user, id) {
		$('#balasan').text('Komentar balasan ke ' + user);
		$('#id_reply').val(id);
	}

	function deleteInput(id) {
		$('#balasan').text('Komentar');
		$('#id_reply').val('0');
	}
</script>



<link rel="stylesheet" href="https://berkas.dpr.go.id/mooc/assets/css/reply-mentoring.css">
<!-- <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script> -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
<!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.6/dist/sweetalert2.min.css" />
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.6/dist/sweetalert2.min.js"></script> -->


<div class="content-header"></div>
<div class="UI_Header_Title">
	
	<h5 class="fw-bold"><?= $this->avatar; ?>Chat Mentoring</h6>
	<div class="header_nav_links fs-6"><a href="/mentor/forum-mentoring/index">Back to Daftar Forum Mentoring</a></div>
</div>
<div class="clear"></div>
<form id="compose" name="compose" method="post" action="" enctype="multipart/form-data">
	<div class="tabular">
	<div class="m-5" style="border-radius: 7px; border: 2px  solid #D4A216; box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5); padding: 10px;">
    <h6 class="m-3">Title : <?= $this->rows->title; ?></h6>
    <h6 class="m-3">File : <a style="color: red;" href="https://berkas.dpr.go.id/mooc/mentoring/<?= $this->rows->file_mentoring; ?>" class="btn btn-outline-danger">Download</a></h6>
    <h6 class="m-3">Pelatihan : <?= $this->pelatihan->nama_pelatihan; ?></h6>
    <h6 class="m-3">Batch : <?= $this->batch->judul_batch; ?></h6>

	
			<label class="m-3">Jumlah Komentar Pada Semua Peserta</label>
			<input readonly type="hidden" id="id_pesertax" autocomplete="disable" style="height:30px; padding: 0px; padding-left: 10px; width: 400px; border: 1px solid grey; border-radius: 2px;" />
			<input readonly type="hidden" id="nama_pesertax" autocomplete="disable" style="height:30px; padding: 0px; padding-left: 10px; width: 400px; border: 1px solid grey; border-radius: 2px;" />
			<input class="btn btn-primary" type="button" value=" Lihat  " id="btnpesertax" style="height:30px;" onclick="jQuery.facebox({ ajax: '/mentor/forum-mentoring/search-pesertax/id/<?= $this->rows->id; ?>'});">
			
			<i class="bi bi-people-fill"></i>
			<!-- <input type="button" style="height:30px;" onclick="ClearFields1();" value="Clear"> -->
			<!-- <font color="red">*</font> -->
				<div class="container">
					<div class="right-position" style="display: flex; justify-content: flex-end;">

					<a href="#mentoring" class="toggles p-0 fs-7 text-decoration-none text-dark fw-bold">Reply</a>
						
					</div>
				</div>
			</div>

            <?php
				// format time
				function formatTime($time) {
					$date = new DateTime($time);
					$formattedDate = $date->format('d M Y H:m:s');

					return $formattedDate;
				}


                $auth = Zend_Auth::getInstance()->getIdentity();
                $this->ChatMentoringService = new ChatMentoringService();

                $replies = [];
                // mendapatkan data chat 
                foreach ($this->chat_mentorings as $key => $chat) {
                    
                    $nama2 = "-";
            
                    if ($chat->role_user == "Mentor") {
                        foreach ($this->mentor as $m) {
                            if ($m->id == $chat->id_user) {
                                $nama2 = $m->nama_mentor;
                                break;
                            }
                        }
                    } else if ($chat->role_user == "Peserta") {
                        foreach ($this->peserta as $p) {
                            if ($p->id == $chat->id_user) {
                                $nama2 = $p->nama;
                                break;
                            }
                        }
                    } else if ($chat->role_user == "Coach") {
                        foreach ($this->coach as $c) {
                            if ($c->id == $chat->id_user) {
                                $nama2 = $c->nama_coach;
                                break;
                            }
                        }
                    }
            
                    $data_chat = "";
            
                    if($chat->id_user == $auth->id_mentor) {
                        echo'<section id="' . $chat->id . '" class="container-mentoring-user d-flex flex-column rounded-4 my-0 ps-5" style=" max-width: 80vw; margin-left: 6%;">';
                    } else {
                        echo'<section id="' . $chat->id . '" class="container-mentoring-other d-flex flex-column rounded-4 my-0 pe-5" style="max-width: 80vw; margin-left: 6%;">';
                    }
            
                        $data_chat .= '<div class="background-content d-flex flex-column justify-content-center rounded-3 p-3 mb-5" style="width: 100%; background-color: #E5E7E9; border: 1px solid #D4A216;">        
                            <div class="d-flex flex-row mb-3">
                                <div class="d-flex flex-column justify-content-start" style="width: 100%;">
                                    <h6 class="m-0 fw-bold">'. $nama2 .'</h6>
                                    <h6 class="m-0 text-secondary" >'. formatTime($chat->tanggal_input) .'</h6>
                                </div>
            
                                <div>
                                    <button type="button" class="copy2 border-0 bg-transparent">
                                        <i class="bi bi-clipboard fs-5 div-text"></i>
                                    </button>
                                </div>
                            </div>';
                    
                            // looping data reply
                            $balasan = '';
            
                            if($chat->id_reply_mentoring != 0) {
                                foreach ($replies as $reply) {
                                    if ($reply['id'] == $chat->id_reply_mentoring) {
                                        $balasan .= $reply['isi'];
                                        break; 
                                    }
                                }
                            }
                            // End looping data reply
                            $data_chat .= $balasan . '<div   class=" content-message d-flex flex-column justify-content-between align-items-center">';
                                if($chat->file_mentoring != '') {
                                    $data_chat .= '<div class="sub-background-content d-flex flex-row justify-content-between align-items-center mb-1 rounded-3 p-2" style="width: 100%; background-color: #F4F6F6;">
                                            <input readonly class="sub-background-content fs-6 border-0" style="width: 100%; outline: white; background-color: #F4F6F6;" value="'. $chat->file_mentoring .'">
                                            <button type="button" class="border-0 bg-transparent" onclick="downloadFile(\'https://berkas.dpr.go.id/mooc/mentoring/'. $chat->file_mentoring .'\')">
                                                <i class="bi bi-download fs-5 fw-bold"></i>
                                            </button>
                                        </div>';
                                } 
                                $data_chat .= '<div class=" d-flex flex-row justify-content-between" style="width: 100%;">
                                    <input readonly class="background-content div-text input2 m-0 fs-6 border-0" style="width: 90%; background-color: #E5E7E9; outline: white;" value="'. $chat->isi .'">
                                    <a href="#mentoring" class="toggles p-0 fs-7 text-decoration-none text-dark fw-bold" cursor: pointer" onclick="addInput(\'' . $nama2 . '\',\'' . $chat->id . '\')">Reply</a>
                                </div>
                            </div>
                        </div>
                    </section>
					
					';
                    
                    // reply chat
                    $data_reply = '<div class="rounded-3 mb-3 p-3" style="background-color: #FFC55C;">
                                <div class="d-flex flex-column justify-content-start mb-3" style="width: 100%;">
                                    <p class="m-0 fw-bold">' . $nama2 . '</p>
                                    <p class="m-0">'. formatTime($chat->tanggal_input) .'</p>
                                </div>';
            
                                if ($chat->file_mentoring != "") {
                                    $data_reply.= '<div class="d-flex flex-row justify-content-between align-items-center mb-1 rounded-3 p-2" style="width: 100%; background-color: #FFB52E;">
                                        <input readonly class="div-text fs-6 border-0" style="width: 100%; outline: white; background-color: #FFB52E;" value="' . $chat->file_mentoring . '">
                                        <button type="button" class="border-0 bg-transparent" onclick="downloadFile(\'https://berkas.dpr.go.id/mooc/mentoring/' . $chat->file_mentoring . '\')">
                                            <i class="bi bi-download fs-5 fw-bold"></i>
                                        </button>
                                    </div>';
                                }
                                $data_reply.='<p class="m-0 fs-6" style="width: 80%">' . $chat->isi . '</p> 
                            </div>';
                    
                    $replies[] = ['id' => $chat->id, 'isi' => $data_reply];
                    //end reply chat
            
                    echo $data_chat;
                }
            ?>

		<!-- <br>
		<fieldset style="padding:30px; border:3px solid #898121; background:#F7F1E5;">
			<legend style="font-size: 15px;">&nbsp <b id="balasan"> Komentar </b> &nbsp</legend>

			<div class="content-isi">
				<p id="daftar-anonym" class="daftar-user">
					<label>Nama </label>
					<input readonly type="text" id="nama" value="<?= $this->nama; ?>" name="name_user" style="height:30px; padding: 0px; padding-left: 10px; width: 450px; border: 1px solid grey; border-radius: 2px;" />
					<input type="hidden" id="id_reply" name="id_reply" value='0' />
				</p>

				<p>
					<label class="left" for="isi"> Komentar </label>
					<input type="text" id="isi" name="isi" style="overflow: hidden; display: block; width: 450px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;">
				</p>
			</div>
		</fieldset>

		<p class="savecancel">
			<label class="UIbutton-small">
				<input type="submit" value="Submit" class="" />
			</label><a href="/mentor/forum-mentoring/index" class="UIbutton-small">Batal</a>
		</p> -->
	</div>
</form>

<div style="clear:both"></div>


<!-- popup message -->
<form method="post" action="" enctype="multipart/form-data">
    <section id="mentoring" class="popup-message message background-content position-fixed p-2 rounded-4" style="width: 74%; margin-left: 1%; height: 120px; bottom: -30px; background-color: #E5E7E9;">
        <legend style="font-size: 15px;"><b class="div-text" id="balasan"> Komentar </b></legend>
        <div style="width: 100%;">
            <?php
                $id_mentor = "-";

                foreach ($this->peserta_batch as $pb) {
                    $id_mentor = $pb->id_mentor;
                }
				
            ?>

            <div id="daftar-mentor" class="daftar-user" style="display:none;">
                <label style="width: 15%" for="id_reply_mentoring">Id Reply Mentoring</label>
                <input type="hidden" id="id_reply_mentoring" name="id_reply_mentoring" value="0" />
            </div>

            <div id="daftar-mentor" class="daftar-user" style="display:none;">
                <label style="width: 15%" for="role_user">Role User</label>
                <input type="hidden" id="role_user" autocomplete="disable" name="role_user" class="px-3 rounded-5 border-0" style="width: 50%; height:30px;" value="Mentor" />
            </div>

            <div id="daftar-mentor" class="daftar-user" style="display:none;">
                <label style="width: 15%" for="id_user">Id User</label>
                <input type="hidden" id="id_user" autocomplete="disable" name="id_user" class="px-3 rounded-5 border-0" style="width: 50%; height:30px;" value="<?= $id_mentor ?>" />
            </div>

            <div class="position-relative mb-2" style="width: 100%; height: 50px;">
                <button type="button" class="btn-popup-link position-absolute m-0 border-0 bg-transparent" style="width: 5em; height: 50px; left: 0; z-index: 10">
                    <i class="bi bi-link-45deg fs-3"></i>
                </button>

                <input type="text" id="isi" name="isi" class="sub-background-content div-text position-absolute m-0 rounded-5" style="width: 100%; height: 50px; padding-left: 5em; border: 2px solid #D4A216; outline: #D4A216;" placeholder="Ketik pesan">

                <button type="submit" class="position-absolute m-0 border-0" style="width: 5em; height: 50px; right: 0; background-color: #D4A216; border-top-right-radius: 50px; border-bottom-right-radius: 50px;">
                    <i class="bi bi-send-fill fs-5 text-light"></i>
                </button>
            </div>
        </div>
    </section>
</form>
<!-- end popup message -->

<form method="post" action="" enctype="multipart/form-data"> 
    <input type="hidden" id="id_user" autocomplete="disable" name="id_user" class="px-3 rounded-5 border-0" style="width: 50%; height:30px;" value="<?= $id_mentor ?>" />
    <input type="hidden" id="role_user" autocomplete="disable" name="role_user" class="px-3 rounded-5 border-0" style="width: 50%; height:30px;" value="Mentor" />
    <input type="hidden" id="id_reply_mentoringx" name="id_reply_mentoring" value="0" />
    <!-- popup tautan -->
    <div class="content-popup-link popup-link background-content" style="background-color: #E5E7E9;">
        <header>
            <span></span>
            <div class="close-popup-link" style="background-color: #F4F6F6"><i class="bi bi-x text-dark"></i></div>
        </header>
        <div class="content">
            <ul class="icons">
                <!-- foto -->
                <div class="d-flex flex-column align-items-center">
                    <div class="position-relative d-flex justify-content-center align-items-center rounded-circle" style="width: 50px; height: 50px; background-color: #ba55d3;">
                        <input type="file" name="file-mentoring" id="foto" class="position-absolute" style="width: 100%; height: 50px; opacity: 0; outline: white; cursor: pointer;" accept="image/*">
                        <i class="bi bi-image-fill fs-5 text-light"></i>
                    </div>
                    <label for="foto">Foto</label>
                </div>

                <!-- video -->
                <div class="d-flex flex-column align-items-center">
                    <div class="position-relative d-flex justify-content-center align-items-center rounded-circle" style="width: 50px; height: 50px; background-color: #9ecfc1;">
                        <input type="file" name="file-mentoring" id="video" class="position-absolute" style="width: 100%; height: 50px; opacity: 0; outline: white; cursor: pointer;" accept="video/*">
                        <i class="bi bi-camera-reels-fill fs-5 text-light"></i>
                    </div>
                    <label for="video">Video</label>
                </div>

                <!-- audio -->
                <div class="d-flex flex-column align-items-center">
                    <div class="position-relative d-flex justify-content-center align-items-center rounded-circle" style="width: 50px; height: 50px; background-color: #ff6347;">
                        <input type="file" name="file-mentoring" id="audio" class="position-absolute" style="width: 100%; height: 50px; opacity: 0; outline: white; cursor: pointer;" accept="audio/*">
                        <i class="bi bi-headset fs-5 text-light"></i>
                    </div>
                    <label for="audio">Audio</label>
                </div>

                <!-- document -->
                <div class="d-flex flex-column align-items-center">
                    <div class="position-relative d-flex justify-content-center align-items-center rounded-circle" style="width: 50px; height: 50px; background-color: #4682b4;">
                        <input type="file" name="file-mentoring" id="document" class="position-absolute" style="width: 100%; height: 50px; opacity: 0; outline: white; cursor: pointer;" accept=".doc, .docx, .pdf">
                        <i class="bi bi-file-earmark-fill fs-5 text-light"></i>
                    </div>
                    <label for="document">Dokumen</label>
                </div>

                <!-- camera -->
                <div class="d-flex flex-column align-items-center">
                    <div class="position-relative d-flex justify-content-center align-items-center rounded-circle" style="width: 50px; height: 50px; background-color: #fa8072;">
                        <input type="file" name="file-mentoring" id="camera" class="position-absolute" style="width: 100%; height: 50px; opacity: 0; outline: white; cursor: pointer;" accept="image/*">
                        <i class="bi bi-camera fs-5 text-light"></i>
                    </div>
                    <label for="camera">Kamera</label>
                </div>
            </ul>
        </div>
    </div>
    <!-- popup tautan -->

    <!-- popup send -->
    <div class="content-popup-send popup-send background-content" style="background-color: #E5E7E9;">
        <div class="content">
            <header>
                <p class="fs-5 fw-bold">Kirim sebagai file</p>
            </header>
           
            <div>
                <div class="d-flex flex-column mb-3">
                    <label for="file_mentoring" class="mb-2 fw-bold">Nama file</label>
                    <input type="file" name="file_mentoring" class="sub-background-content div-text border-bottom border-dark border-0 p-1 px-2 rounded-3" id="file_mentoring">
                </div>

                <div class="d-flex flex-column mb-3">
                    <label for="isi" class="mb-2 fw-bold">Keterangan</label>
                    <input type="text" name="isi" class="sub-background-content div-text border-bottom border-dark border-0 p-1 px-2 rounded-3" style="background-color: #E5E7E9; outline: white;" id="isi" placeholder="Ketik pesan">
                </div>
            </div>
            <div class="my-2 p-2 text-end" style="width: 100%;">
                <button type="button" class="close-popup-send fw-bold fs-6 mx-2 bg-transparent border-0">Cancel</button>
                <button type="submit" class="fw-bold fs-6 mx-2 bg-transparent border-0">Send</button>
            </div>
        </div>
    </div>
    <!-- end popup send -->
</form>
<!-- end mentoring -->




<script>

    window.onscroll = function() {
        scrollFunction() 
    };

    function scrollFunction() {
        var button = document.getElementById("nav-icon");
        if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
            button.style.display = "flex";
        } else {
            button.style.display = "flex";
        }
    }


    // reply mentoring
    function changeRole(val) {
        document.querySelectorAll(".daftar-user").forEach(function (el) {
            el.style.display = "none";
        });
        if (val === "Mentor") {
            document.querySelector("#daftar-mentor").style.display = "block";
        } else if (val === "Peserta") {
            document.querySelector("#daftar-peserta").style.display = "block";
        }

        if (val === "Coach") {
            document.querySelector("#daftar-coach").style.display = "block";
            document.querySelector('#id_user').value = '<?= $this->id_coach; ?>';
        }
    }

    function addInput(user, id) {
        document.querySelector('#balasan').textContent = 'Komentar balasan ke ' + user;
        document.querySelector('#id_reply_mentoring').value = id;
        document.querySelector('#id_reply_mentoringx').value = id;
    }
    // end reply mentoring

    // popup message
    let show = function (element) {
        element.style.display = 'block';
    };

    let hide = function (element) {
        element.style.display = 'none';
    };

    let toggleChat = function (element) {
        if (window.getComputedStyle(element).display === 'block') {
            hide(element);
            return;
        }

        show(element);
    };

    document.addEventListener('click', function (event) {
        let popupMessage = document.querySelector('.popup-message');
        let popupLink = document.querySelector(".popup-link");
        let popupSend = document.querySelector(".popup-send");
        let isPopupMessageVisible = window.getComputedStyle(popupMessage).display === 'block';
        let isPopupLinkVisible = window.getComputedStyle(popupLink).display === 'block';
        let isPopupSendVisible = window.getComputedStyle(popupSend).display === 'block';

        if (event.target.classList.contains('toggles')) {
            event.preventDefault();

            let target = event.target.hash ? document.querySelector(event.target.hash) : null;
            if (target) {
                toggleChat(target);
            }

            return;
        }

        if (!popupLink.contains(event.target) && !popupSend.contains(event.target)) {
            show(popupMessage)
            if(!popupMessage.contains(event.target)) {
                hide(popupMessage);
            }
        }
    });
    // end popup message

    // popup link
    const popupMessage = document.querySelector('.popup-message');
    const btnPopupLink = document.querySelector(".btn-popup-link");
    const popupLink = document.querySelector(".popup-link");
    const popupSend = document.querySelector('.popup-send');
    const closePopupLink = popupLink.querySelector(".close-popup-link");
    const closePopupSend = popupSend.querySelector(".close-popup-send");

    btnPopupLink.onclick = () => {
        popupLink.classList.toggle("show");
    }

    closePopupLink.onclick = () => {
        btnPopupLink.click();
    }

    closePopupSend.onclick = () => {
        // kosongkan value input ketika close popup send
        modalFileInput.value = '';
        modalTextInput.value = '';

        popupSend.classList.remove("show");
    }

    // end popup link

    // popup send
    const fileInputPopups = document.querySelectorAll('.popup-link input[type="file"]');
    const TextInputMessage = document.querySelector('.message input[type="text"]');
    
    // Menyalin text dan file dari input popup ke input popupSend
    const modalFileInput = document.querySelector('.popup-send input[name="file_mentoring"]');
    const modalTextInput = document.querySelector('.popup-send input[name="isi"]');

    fileInputPopups.forEach((fileInputPopup, index) => {
        fileInputPopup.addEventListener('change', function() {
            // Memeriksa apakah file telah dipilih
            if (fileInputPopup.files.length > 0) {
                // Memunculkan popupSend
                popupSend.classList.add('show');
    
                // salin value dan files input ke input popupSend
                modalFileInput.files = fileInputPopup.files;
                modalTextInput.value = TextInputMessage.value;
            }
        });
    });
    // end popup send

    // copy
    const copy1 = document.querySelectorAll(".copy1");
    const input1 = document.querySelectorAll(".input1");
    const copy2 = document.querySelectorAll(".copy2");
    const input2 = document.querySelectorAll(".input2");
    const copy3 = document.querySelectorAll(".copy3");
    const input3 = document.querySelectorAll(".input3");
    const copy4 = document.querySelectorAll(".copy4");
    const input4 = document.querySelectorAll(".input4");

    copy1.forEach((element, index) => {
        element.addEventListener("click", () => {
            input1[index].select();
            document.execCommand("copy");
            element.innerText = "Copied";
            element.style.backgroundColor = "transparent";

            setTimeout(() => {
                element.innerText = "Copy";
            }, 3000);
        });
    });

    copy2.forEach((element, index) => {
        element.addEventListener("click", () => {
            input2[index].select();
            document.execCommand("copy");
            element.innerText = "Copied";
            element.style.backgroundColor = "transparent";

            setTimeout(() => {
                element.innerText = "Copy";
            }, 3000);
        });
    });

    copy3.forEach((element, index) => {
        element.addEventListener("click", () => {
            input3[index].select();
            document.execCommand("copy");
            element.innerText = "Copied";
            element.style.backgroundColor = "transparent";

            setTimeout(() => {
                element.innerText = "Copy";
            }, 3000);
        });
    });

    copy4.forEach((element, index) => {
        element.addEventListener("click", () => {
            input4[index].select();
            document.execCommand("copy");
            element.innerText = "Copied";
            element.style.backgroundColor = "transparent";

            setTimeout(() => {
                element.innerText = "Copy";
            }, 3000);
        });
    });
    // end copy

    // download file
    function downloadFile(url) {
        var link = document.createElement('a');
        link.href = url;
        link.download = true;
        link.style.display = 'none';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    }
    // end download file
</script>