<script id="js">
$(function(){
	$("table")
		.tablesorter({theme: 'blue', widthFixed: true, widgets: ['zebra', 'filter']})
		.tablesorterPager({container: $(".pager"), 
			output: '{startRow} - {endRow} / {filteredRows} ({totalRows})', 
			fixedHeight: true, 
			removeRows: false, 
			cssGoto: '.gotoPage' 
		});
});
</script>

<div class="content-header"></div>
	<div class="UI_Header_Title">
		<h1><?=$this->avatar;?> Daftar Forum Mentoring</h1>
		
</div>
<div class="clear"></div>
<br>

<? if (count($this->rows) > 0) { ?>
	<?=$this->pager;?>

	<table class="tablesorter">
		 <thead>
			 <tr>
			 	<th width="5px" align="center">No.</th>
				<th align="center">Pelatihan</th>
				<th align="center">Batch</th>
				<th align="center">Title</th>
				<th align="center">Aksi</th>
			</tr>
		</thead>
		<tbody>
			<?php
			$index = 1;
			foreach($this->rows as $row)
			{
				echo '<tr>';
				echo '<td align="center">'. $index++ .'.</td>';
				foreach($this->batch as $y){
					if($y->id == $row->id_batch){
						foreach($this->pelatihan as $z){
							if($z->id == $y->id_pelatihan){
								echo '<td align="center">'. $z->nama_pelatihan .'</td>';
								break;
							}
						}
						break;
					}
				}

				foreach($this->batch as $y){
					if($y->id == $row->id_batch){
						echo '<td align="center">'. $y->judul_batch .'</td>';
						break;
					}
				}
				echo '<td align="center">'. $row->title .'</td>';
				echo '<td align="center"><a href="/mentor/forum-mentoring/reply/id/'. $row->id .'">VIEW</a>';
				echo '</td>';
				echo '</tr>';
			}
			?>
		</tbody>
	</table>
<? } else {
	echo 'Data tidak ditemukan.';
}
?>