<?php 
    $riwayat = [];
    
    foreach($this->batch as $val) { 
        foreach($this->riwayat as $riw) {
            if($val->id == $riw->id_batch) {

                $riwayat[] = array(
                    'id_batch' => $val->id,
                    'id_peserta' => $riw->id_peserta,
                    'status_riwayat' => $riw->status_riwayat,
                    'status_progress' => $riw->status_progress,
                );
                
                break;
            }
        }
    }
?>

<link rel="stylesheet" href="https://berkas.dpr.go.id/mooc/assets/css/pelatihan.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.6/dist/sweetalert2.min.css" />
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.6/dist/sweetalert2.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

<!-- sidebar -->
<div class="area"></div>
<nav class="main-menu background-content">
    <ul class="background-content">
        <li id="toggle-menu" class="has-subnav mb-4 d-flex justify-content-center align-items-center" style="width: 60px; cursor: pointer;">
            <i class="bi bi-list fs-3 fw-bold" style="color: black !important;"></i>
        </li>

        <li class="has-subnav">
            <a href="/peserta/index/">
                <img src="https://berkas.dpr.go.id/mooc/assets/images/dashboardblack.png" alt="" class="icon" style="width: 20px; height: 20px;">
                <span class="nav-text">Dashboard</span>
            </a>
        </li>

        <li class="has-subnav ">
            <a href="/peserta/pelatihan">
                <img src="https://berkas.dpr.go.id/mooc/assets/images/pelatihan-black.png" alt="" class="icon" style="width: 20px; height: 20px;">
                <span class="nav-text">Pelatihan</span>
            </a>    
        </li>

        <li class="has-subnav">
            <a href="/peserta/forum">
                <img src="https://berkas.dpr.go.id/mooc/assets/images/forum-black.png" alt="" class="icon" style="width: 20px; height: 20px;">
                <span class="nav-text">Forum</span>
            </a>
        </li>

        <li class="has-subnav active">
            <a href="/peserta/riwayat">
                <img src="https://berkas.dpr.go.id/mooc/assets/images/hourglass-split.svg" alt="" class="icon" style="width: 20px; height: 20px; filter: brightness(0) invert(1);">
                <span class="nav-text">Riwayat</span>
            </a>
        </li>
        
    </ul>
</nav>
<!-- end sidebar -->
<br><br> <br><br>

<!-- riwayat -->
<section class="container-pelatihan d-flex flex-column rounded-4" style="max-width: 80vw; margin-left: 10%; padding-top: 50px;">
    <div class="mb-2">
        <p class="fs-3 fw-bold">Riwayat Pelatihan</p>
    </div> 

    <div class="content-pelatihan d-flex flex-column justify-content-start rounded-4" style="width: 100%;">
        <div class="row content-seacrh-filter m-0 mb-3 d-flex flex-row justify-content-between pe-3" style="width: 100%;">
            <!-- filter -->
            <div class="col-md-6 content-filter p-0 d-flex flex-row">
                <div class="dropdown me-4 p-0">
                    <button class="dropdown-toggle background-content m-0 btn border-0" style="background-color: #E5E7E9; box-shadow: 2.0px 4.0px 4.0px hsl(0deg 0% 0% / 0.38);" type="button" data-bs-toggle="dropdown" aria-expanded="false">Status</button>
                    <ul class="dropdown-menu background-content">
                        <li><button id="btn-selesai" class="dropdown-item rounded-0" onclick="filterData('Selesai')">Selesai</button></li>
                        <li><button id="btn-menyerah" class="dropdown-item rounded-0" onclick="filterData('Menyerah')">Menyerah</button></li>
                    </ul>
                </div>
            </div>
    
            <div class="col-md-6 content-search pe-2">
                <form class="nav-item d-flex search-form m-0" style="height: 100%" role="search">
                    <div class="box-pelatihan">
                        <form name="search">
                            <input type="text" id="search-input" class="input-pelatihan background-content text-secondary" style="width: 70%; background-color: #E5E7E9;"  name="txt" placeholder="Cari disini...">
                            <img src="https://berkas.dpr.go.id/mooc/assets/images/search.png" alt="" style="width: 25px; height: 25px;">
                        </form>
                    </div>
                </form>
            </div>
        </div>

        <div class="content-card rounded-4 pe-3" style="width: 100%;">
            <div id="card-riwayat-container" class="row m-0 d-flex flex-row flex-wrap gap-3" style="width: 100%">
                <!-- content card riwayat -->
            </div>
        </div>
    </div>
</section>
<!-- end riwayat -->

<script>
    // search data
    document.addEventListener('DOMContentLoaded', function() {
        let batch = <?php echo json_encode($this->batch); ?>;
        let riwayat = <?php echo json_encode($riwayat); ?>;
        let cardRiwayatContainer = document.getElementById('card-riwayat-container');

        // Function generate card pelatihan
        function generateCardPelatihanContainer(data) {
            cardRiwayatContainer.innerHTML = '';

            data.forEach(function(item) {
                let card = document.createElement('div');
                card.classList.add('col-md-4', 'sub-content-card', 'background-content', 'rounded-4', 'p-2');
                card.style.width = '32%';
                card.style.height = '450px';
                card.style.backgroundColor = '#E5E7E9';
                card.style.boxShadow = '2.0px 4.0px 4.0px hsl(0deg 0% 0% / 0.38)';


                let mentorName = item.nama_mentor !== null ? item.nama_mentor : "";
                let cardPelatihanContent = '<img src="https://berkas.dpr.go.id/mooc/thumbkelas/' + item.sampul_pelatihan + '" alt="" class="rounded-4 overflow-hidden mb-2" style="width: 100%; height: 250px; object-fit: cover;">' +
                    '<p class="text-start text-secondary m-1" style="font-size: 14px;">' + mentorName + '</p>';

                    let lanjut = '';
                    let progressStatus = "";

                    riwayat.forEach(function(riw) {
                        if (item.id == riw.id_batch) {
                            progressStatus = riw.status_riwayat.split("-");
                            if (progressStatus[0] === 'Menyerah') {
                                lanjut = '#';
                            } else if (progressStatus[0] === 'Selesai') {
                                lanjut = '/peserta/pelatihan-saya/sertifikat/id/' + item.id;
                            }
                        }
                    });

                    if (progressStatus[0] == "Menyerah") {
                        cardPelatihanContent += '<button type="button" id="latihan-disable" class="title-pelatihan m-1 text-dark text-start fs-4 fw-bold border-0 bg-transparent" style="width: 100%; z-index: 1; cursor: pointer;">' + (item.nama_pelatihan.length > 12 ? item.nama_pelatihan.substr(0, 20) + '...' : item.nama_pelatihan) + '<i class="bi bi-lock-fill text-secondary"></i></button>';

                    } else if(progressStatus[0] == "Selesai") {
                        cardPelatihanContent += '<a href="'+ lanjut +'" class="m-0 text-dark text-start fs-4 fw-bold text-decoration-none" style="width: 100%; z-index: 1">' + (item.nama_pelatihan.length > 12 ? item.nama_pelatihan.substr(0, 20) + '...' : item.nama_pelatihan) + '</a>';
                    }

                    cardPelatihanContent += '<div class="d-flex flex-row align-items-center my-2">' +
                        '<img src="https://berkas.dpr.go.id/mooc/assets/images/book-variant-grey.png" alt="" class="me-2" style="width: 20px; height: 20px;">' +
                        '<p style="font-size: 14px;" class="m-0 text-secondary text-start">' + item.nama_pelatihan.length + ' Kelas</p>' +
                        '<img src="https://berkas.dpr.go.id/mooc/assets/images/account-multiple-black.png" alt="" class="me-2" style="width: 20px; height: 20px; margin-left: 27px;">' +
                        '<p style="font-size: 14px" class="m-0 text-secondary text-start">' + (item.kuota_peserta ? item.kuota_peserta : '0') + ' Peserta</p>' +
                    '</div>' +
                    '<div class="d-flex flex-row align-items-center mb-4">' +
                        '<img src="https://berkas.dpr.go.id/mooc/assets/images/equalizer.png" alt="" class="me-2" style="width: 20px; height: 20px;">' +
                        '<p style="font-size: 14px" class="m-0 text-secondary text-start me-3">Beginner</p>' +
                        '<img src="https://berkas.dpr.go.id/mooc/assets/images/clock.png" alt="" class="me-2" style="width: 20px; height: 20px;">' +
                        '<p style="font-size: 14px" class="m-0 text-secondary text-start"> 20 Jam </p>' +
                    '</div>';

                card.innerHTML = cardPelatihanContent;
                cardRiwayatContainer.appendChild(card);
            });

            // alert menyerah
            let btnLatihanDisable = document.querySelectorAll('#latihan-disable');
            if(btnLatihanDisable) {
                btnLatihanDisable.forEach(function(element) {
                    element.addEventListener('click', function() {
                        Swal.fire({
                            title: 'Sayang Sekali',
                            text: 'Anda Telah Menyerah Pada Pelatihan Ini',
                            icon: 'error',
                            confirmButtonText: 'OK',
                            confirmButtonColor: '#4CAF50'
                        });
                    });
                });
            }
            // end alert menyerah
        }
        generateCardPelatihanContainer(batch);

        // function filter data 
        let searchInput = document.getElementById('search-input');
        searchInput.addEventListener('input', filterCardPelatihanContainer);

        function filterCardPelatihanContainer() {
            let inputValue = searchInput.value.toLowerCase().trim();

            // filter dan ambil nama pelatihan
            let filteredBatch = batch.filter(function(item) {
                return item.nama_pelatihan.toLowerCase().includes(inputValue);
            });

            if (filteredBatch.length === 0) {
                cardRiwayatContainer.innerHTML = '<p class="mt-5 fs-4 text-center text-danger fst-italic">Riwayat pelatihan tidak ditemukan</p>';
            } else {
                generateCardPelatihanContainer(filteredBatch);
            }
        }        
    });
    // end search data

    // filter data
    function filterData(dataFilter) {
        let batch = <?php echo json_encode($this->batch); ?>;
        let riwayat = <?php echo json_encode($riwayat); ?>;
        let cardRiwayatContainer = document.getElementById('card-riwayat-container');

        // Menghapus kartu sebelumnya
        while (cardRiwayatContainer.firstChild) {
            cardRiwayatContainer.removeChild(cardRiwayatContainer.firstChild);
        }

        // kondisi ketika filter kosong
        let emptyData = riwayat.filter(function(item) {
            console.log("Data", item)
            return item.status_riwayat === dataFilter;
        });

        if (emptyData.length === 0) {
            let textEmptyData = document.createElement('p');
            textEmptyData.classList.add('mt-5', 'fs-4', 'text-center', 'text-danger', 'fst-italic');
            textEmptyData.textContent = 'Riwayat pelatihan tidak ditemukan';
            cardRiwayatContainer.appendChild(textEmptyData);
            return;
        }

        batch.forEach(function(item) {
            let progressStatus = "";
            riwayat.forEach(function(riw) {
                if (item.id == riw.id_batch) {
                    progressStatus = riw.status_riwayat.split("-");
                    if (dataFilter === "Menyerah" && progressStatus[0] === 'Menyerah') {
                        let card = cardRiwayatFilter(item, riw);
                        cardRiwayatContainer.appendChild(card);
                    } else if (dataFilter === "Selesai" && progressStatus[0] === 'Selesai') {
                        let card = cardRiwayatFilter(item, riw);
                        cardRiwayatContainer.appendChild(card);
                    }
                }
            });
        });

        // alert waiting class
        let btnLatihanDisable = document.querySelectorAll('#latihan-disable');
        if(btnLatihanDisable) {
            btnLatihanDisable.forEach(function(element) {
                element.addEventListener('click', function() {
                    Swal.fire({
                        title: 'Maaf',
                        text: 'Pelatihan anda sedang dalam proses persetujuan admin dan coach.',
                        icon: 'error',
                        confirmButtonText: 'OK',
                        confirmButtonColor: '#4CAF50'
                    });
                });
            });
        }
        // end alert waiting class
    }

    function cardRiwayatFilter(item, riw) { // create card riwayat setelah data di filter
        let card = document.createElement('div');
        card.classList.add('col-md-4', 'sub-content-card', 'background-content', 'rounded-4', 'p-2');
        card.style.width = '32%';
        card.style.height = '450px';
        card.style.backgroundColor = '#E5E7E9';
        card.style.boxShadow = '2.0px 4.0px 4.0px hsl(0deg 0% 0% / 0.38)';

        let mentorName = item.nama_mentor !== null ? item.nama_mentor : "";
        let cardPelatihanContent = '<img src="https://berkas.dpr.go.id/mooc/thumbkelas/' + item.sampul_pelatihan + '" alt="" class="rounded-4 overflow-hidden mb-2" style="width: 100%; height: 250px; object-fit: cover;">' +
            '<p class="text-start text-secondary m-1" style="font-size: 14px;">' + mentorName + '</p>';

        let lanjut = '';

        if (riw.status_riwayat === 'Menyerah') {
            lanjut = '#';
            cardPelatihanContent += '<button type="button" id="latihan-disable" class="title-pelatihan m-1 text-dark text-start fs-4 fw-bold border-0 bg-transparent" style="width: 100%; z-index: 1; cursor: pointer;">' + (item.nama_pelatihan.length > 12 ? item.nama_pelatihan.substr(0, 20) + '...' : item.nama_pelatihan) + '<i class="bi bi-lock-fill text-secondary"></i></button>';
        } else if (riw.status_riwayat === 'Selesai') {
            lanjut = '/peserta/pelatihan-saya/sertifikat/id/' + item.id;
            cardPelatihanContent += '<a href="' + lanjut + '" class="m-0 text-dark text-start fs-4 fw-bold text-decoration-none" style="width: 100%; z-index: 1">' + (item.nama_pelatihan.length > 12 ? item.nama_pelatihan.substr(0, 20) + '...' : item.nama_pelatihan) + '</a>';
        }

        cardPelatihanContent += '<div class="d-flex flex-row align-items-center my-2">' +
            '<img src="https://berkas.dpr.go.id/mooc/assets/images/book-variant-grey.png" alt="" class="me-2" style="width: 20px; height: 20px;">' +
            '<p style="font-size: 14px;" class="m-0 text-secondary text-start">' + item.nama_pelatihan.length + ' Kelas</p>' +
            '<img src="https://berkas.dpr.go.id/mooc/assets/images/account-multiple-black.png" alt="" class="me-2" style="width: 20px; height: 20px; margin-left: 27px;">' +
            '<p style="font-size: 14px" class="m-0 text-secondary text-start">' + (item.kuota_peserta ? item.kuota_peserta : '0') + ' Peserta</p>' +
            '</div>' +
            '<div class="d-flex flex-row align-items-center mb-4">' +
            '<img src="https://berkas.dpr.go.id/mooc/assets/images/equalizer.png" alt="" class="me-2" style="width: 20px; height: 20px;">' +
            '<p style="font-size: 14px" class="m-0 text-secondary text-start me-3">Beginner</p>' +
            '<img src="https://berkas.dpr.go.id/mooc/assets/images/clock.png" alt="" class="me-2" style="width: 20px; height: 20px;">' +
            '<p style="font-size: 14px" class="m-0 text-secondary text-start"> 20 Jam </p>' +
            '</div>';

        card.innerHTML = cardPelatihanContent;
        return card;
    }

    let btnSelesai = document.getElementById('btn-selesai');
    let btnMenyerah = document.getElementById('btn-menyerah');
    let searchValue = document.getElementById('search-input');

    btnSelesai.addEventListener('click', function() {
        filterData('Selesai');
        searchValue.value = "";
    });

    btnMenyerah.addEventListener('click', function() {
        filterData('Menyerah');
        searchValue.value = "";
    });
    // end filter data

    // progress bar
    let processing = document.querySelectorAll('.processing-bar');    
    setTimeout(() => {
        processing.forEach(el => {
            el.style.opacity = 1;
            el.style.width = el.getAttribute('data-bar') + '%';
        })
    }, 500);
    // end progress bar

    // sidebar animation
    document.getElementById('toggle-menu').addEventListener('click', function() {
        var mainMenu = document.querySelector('.main-menu');
        var currentWidth = mainMenu.offsetWidth;
        var targetWidth = (currentWidth === 250) ? 60 : 250;
        mainMenu.style.width = targetWidth + 'px';

        let elementsToMove = [
            document.querySelector('.container-pelatihan'),
        ];

        elementsToMove.forEach(element => {
            if(element) {
                if (targetWidth === 250) {
                    element.style.marginLeft = '20%';
                } else {
                    element.style.marginLeft = '10%';
                }
            }
        });
    });
    // end sidebar animation
</script>
