<link rel="stylesheet" href="https://berkas.dpr.go.id/mooc/assets/css/belajar-pelatihan-saya.css">
<link rel="stylesheet" href="https://berkas.dpr.go.id/mooc/assets/css/mentoring.css">

<script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.6/dist/sweetalert2.min.css" />
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.6/dist/sweetalert2.min.js"></script>


<div class="area"></div>
    <nav class="main-menu " style="max-width: 100vw; margin-top: 85px;">
        <div id="mySidebar" class="sidebar background-content" style=" z-index: 999; margin-top: 85px; overflow-y: auto; max-height: calc(100vh - 85px); background-color: #E5E7E9;">
            <a style="color: #D4A216;" href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
            <div class="p-3">
            <p class="fs-5">Table of Contents</p>
            
            <hr>
            <?php
                $progress = explode("-", $this->progress->status_progress);
             ?>
            <a <?= ($progress[0] == 'Pretest' ? ' style="pointer-events: none; cursor: default;" ' : '') ?> href="/pesertanonasn/pelatihan-saya/pretest/id/<?= $this->batch->id ?>">Pretest<br><i class="bi bi-check-circle-fill text-success"></i> Selesai
            </a>
            
            <hr>
            <div>
                <?php
                $materi_idx = 'x';
                foreach ($this->silabus as $id => $silabus) {
                    echo '<ul style="margin-left: -35px; ">';
                    echo ' <a class=" collapsed dropdown-toggle" type="button" data-bs-toggle="collapse"
                                data-bs-target="#a' . $silabus->id . '" aria-expanded="false" aria-controls="collapseExample">' . $silabus->nama_silabus . ' </a>';
                    echo '</ul>';

                    echo ' <div class="collapse" id="a' . $silabus->id . '" >';
                    echo '<ul >';

                    $i = 1;
                    foreach ($this->materi as $idx => $materi) {
                        if ($materi->id_silabus == $silabus->id) {
                            echo '<li> 
                                        <a '.($this->progress->status_progress == 'none' ? ' style="pointer-events: none; cursor: default;" ' : '').' style="margin-left: -42px;" href="/pesertanonasn/pelatihan-saya/belajar/id/' . $this->batch->id . '/silabus/' . ($id + 1) . '/materi/' . $i++ . '">' . $materi->nama_materi . '
                                        '.($progress[0] == 'Mentoring' || $progress[0] == 'Postest' ? '<br><i class="bi bi-check-circle-fill text-success"></i> Selesai ' : '').'
                                        </a>
                                  </li>';
                                  
                        }
                    }
                    echo '</ul>';
                    echo '</div>';
                }

                ?>

            </div>

            <hr>
                <a <?= ($progress[0] == 'Pretest' || $progress[0] == 'Materi' ? 'disabled="disabled" class="disabled"' : '') ?> href="/pesertanonasn/pelatihan-saya/postest/id/<?= $this->batch->id; ?>">
                
                Postest
                
                <?= ($progress[0] == 'Pretest' || $progress[0] == 'Materi' ? '<i class="bi bi-lock-fill text-secondary"></i>' : '') ?>
                <?=  ($progress[0] == 'Mentoring' || $progress[0] == 'Penugasan' || $progress[0] == 'Penilaian' || $progress[0] == 'Sertifikat' ? '<br><i class="bi bi-check-circle-fill text-success"></i> Selesai' : '') ?>
                </a>
                
                <hr>
                <a <?= ($progress[0] == 'Materi' || $progress[0] == 'Pretest'  || $progress[0] == 'Postest'  ? 'disabled="disabled" class="disabled"' : '') ?> href="/pesertanonasn/pelatihan-saya/mentoring/id/<?= $this->batch->id; ?>"> 
                
                Mentoring
                
                <?= ($progress[0] == 'Materi' || $progress[0] == 'Pretest' || $progress[0] == 'Postest' ? '<i class="bi bi-lock-fill text-secondary"></i>' : '') ?>
                <?=  ($progress[0] == 'Penugasan' || $progress[0] == 'Penilaian' || $progress[0] == 'Sertifikat' ? '<br><i class="bi bi-check-circle-fill text-success"></i> Selesai' : '') ?>
                </a>
               
                <hr>
                <a <?= ($progress[0] == 'Materi' || $progress[0] == 'Pretest' || $progress[0] == 'Postest' || $progress[0] == 'Mentoring' ? 'disabled="disabled" class="disabled"' : '') ?> href="/pesertanonasn/pelatihan-saya/penugasan/id/<?= $this->batch->id ?>">
                
                Tugas Akhir
                
                <?= ($progress[0] == 'Materi'  || $progress[0] == 'Postest' || $progress[0] == 'Mentoring' || $progress[0] == 'Pretest' ? '<i class="bi bi-lock-fill text-secondary"></i>' : '') ?>
                <?=  ($progress[0] == 'Penilaian' || $progress[0] == 'Sertifikat' ? '<br><i class="bi bi-check-circle-fill text-success"></i> Selesai' : '') ?>
                </a>
                
                <hr>
                <a <?= ($progress[0] !== 'Sertifikat' ? 'disabled="disabled" class="disabled"' : '') ?> href="/pesertanonasn/pelatihan-saya/sertifikat/id/<?= $this->batch->id ?>">Sertifikat
                <?= ($progress[0] !== 'Sertifikat' ? '<i class="bi bi-lock-fill text-secondary"></i>' : '') ?>
                <?=  ($progress[0] == 'Sertifikat' ? '<br><i class="bi bi-check-circle-fill text-success"></i> Selesai' : '') ?>
                </a>
            <hr>
            <div style="text-align: center;">
                    <button class=" btn btn-outline-danger" onclick="menyerahClicked()"><i class="bi bi-x-circle"></i> Menyerah</button>
                </div>
            <hr>
            </div>
            </div>

            <div id="main">
            <button class="openbtn background-content" id="nav-icon" onclick="toggleNav()" style="z-index: 2; position: fixed; margin-left: -23px; display: flex; justify-content: center;align-items: center; color: #D4A216; background-color: #E5E7E9; font-size: 41px; padding: 10px 0px 15px 0;">&#8250;</button>


<div class="row content-header mb-3">
    <div class=" col-1"></div>
        <div class="sub-content-header col-10">
            <div class="card rounded-4 background-content" style="border:none; background-color: #E5E7E9; box-shadow: 2.0px 4.0px 4.0px hsl(0deg 0% 0% / 0.38);">
                <div class="card-body" style=" color: #808080;">
                    <a style=" color: #808080;" class="text-decoration-none" href="/pesertanonasn">Belajar Saya</a>&nbsp &nbsp|&nbsp &nbsp
                    <a style=" color: #808080;" class="text-decoration-none" href="/pesertanonasn/pelatihan">Pelatihan</a>&nbsp &nbsp|&nbsp &nbsp
                    <a style=" color: #808080;" class="text-decoration-none" href="/pesertanonasn/pelatihan-saya/belajar/id/<?= $this->batch->id ?>/silabus/1/materi/1"><?= $this->pelatihan->nama_pelatihan ?></a>&nbsp &nbsp|&nbsp &nbsp
                    <a class="text-dark text-decoration-none" href="" >Mentoring</a>
                </div>
            </div>
        </div>
    <div class=" col-1"></div>
</div>

<!-- mentoring -->
<section class="container-mentoring m-auto rounded-4" style="max-width: 80vw; margin-top: 20px;">
    <div class="d-flex flex-column" style="width: 100%;">
        <div class="content-diskusi d-flex flex-row mb-4">
            <button class="d-flex justify-content-center align-items-center m-0 text-light p-1 px-3 rounded-4 me-3 text-decoration-none border-0 cursor-pointer" style="height: 100%; font-size: 14px; background-color: #D4A216;">Semua</button>
            <button class="background-content d-flex justify-content-center align-items-center m-0 p-1 px-3 rounded-4 me-3 text-decoration-none cursor-pointer" style="height: 100%; font-size: 14px; color: #D4A216; border: 1px solid #D4A216;">Terjawab</button>
            <button class="background-content d-flex justify-content-center align-items-center m-0 p-1 px-3 rounded-4 me-3 text-decoration-none cursor-pointer" style="height: 100%; font-size: 14px; color: #D4A216; border: 1px solid #D4A216;">Belum Terjawab</button>
        </div>
    </div>
    <?php
        if($this->skor_mentoring->skor_akhir != "") {
            echo'<section>
                    <div class="background-content d-flex flex-column justify-content-center rounded-4 p-3 mb-5" style="background-color: #E5E7E9; border: 1px solid #D4A216;">
                        <p class="m-0 mb-1 text-center fs-3">Sesi Mentoring Telah Berakhir</p>
                        <p class="m-0 text-center fs-3">Anda dapat melanjutkan ke tahap selanjutnya</p>
                    </div>
            </section>';
        } else {
            foreach($this->mentorings as $mentoring) {
                $total_chat= 0;
                $nama_coach = "-";
                $nama_pelatihan = "-";
                $foto_coach = "-";
    
                foreach($this->batchs as $batch) {
                    if($batch->id == $mentoring->id_batch) {
                            foreach($this->pelatihans as $pelatihan) {
                                if($pelatihan->id == $batch->id_pelatihan) {
                                    $nama_pelatihan = $pelatihan->nama_pelatihan;
                                    break;
                                }
                            }
                        break;
                    }
                }
    
                foreach($this->batchs as $batch) {
                    if($batch->id == $mentoring->id_batch) {
                        foreach($this->pelatihans as $pelatihan) {
                            if($pelatihan->id == $batch->id_pelatihan) {
                                foreach($this->coachs as $coach) {
                                    if($coach->id == $batch->id_coach) {
                                        $nama_coach = $coach->nama_coach;
                                        $foto_coach = $coach->fotocoach_uri;
                                        break;
                                    }
                                }
                                break;
                            }
                        }
                    }
                }
    
                foreach($this->batchs as $batch) {
                    if($batch->id == $mentoring->id_batch) {
                        foreach($this->pelatihans as $pelatihan) {
                            if($pelatihan->id == $batch->id_pelatihan) {
                                foreach($this->chat_mentorings as $chat) {
                                    if($chat->id_mentoring == $mentoring->id) {
                                        $total_chat++;
                                    }
                                }
                                break;
                            }
                        }
                    }
                }
    
                foreach($this->batchs as $batch) {
                    if($batch->id == $mentoring->id_batch) {
                        if($this->batch->id == $mentoring->id_batch) {
                            echo'
                                <p class="m-1 fs-5 fw-bold">'. $nama_pelatihan .'</p>
                                <div class="background-content d-flex flex-column justify-content-center rounded-4 p-3 mb-5" style="background-color: #E5E7E9; border: 1px solid #D4A216;">
                                    <div class="d-flex flex-row mb-3">
                                        <div class="d-flex flex-column justify-content-center align-items-center text-center bg-light border border-light rounded-circle mb-3 me-3" style="width: 50px; height: 50px; box-shadow: 4.0px 8.0px 8.0px hsl(0deg 0% 0% / 0.38);">
                                            <img src="https://berkas.dpr.go.id/mooc/fotocoach/'. $foto_coach .'" alt="" style="width: 25px; height: 25px;">
                                        </div>
                                        <div class="d-flex flex-column justify-content-start" style="width: 100%;">
                                            <p class="m-0 fw-bold">'. $nama_coach .'</p>
                                            <p class="m-0 text-secondary">'. $mentoring->tanggal_input .'</p>
                                        </div>
                                        <div>
                                            <button type="button" class="copy1 border-0">
                                                <i class="bi bi-clipboard fs-5 background-content"></i>
                                            </button>
                                        </div>
                                    </div>
                                    <div class="content-message d-flex flex-row justify-content-between align-items-center">
                                        <input class="background-content input1 m-0 fs-6 border-0 div-text" style="width: 80%; background-color: #E5E7E9; outline: white;" value="'. $mentoring->title .'">
                                        <div class="d-flex flex-row justify-content-end align-items-center" style="width: 10%";>
                                            <p class="m-0 pe-1">'. $total_chat .'</p>
                                            <a href="/pesertanonasn/pelatihan-saya/reply-mentoring/batch/'.$mentoring->id_batch.'/id/'. $mentoring->id .'" class="p-0 fs-7 text-decoration-none" style="color: #D4A216">
                                                <img src="https://berkas.dpr.go.id/mooc/assets/images/message-black.png" alt="" style="width: 25px; height: 25px;">
                                            </a>
                                        </div>
                                    </div>
                                </div>';
                        }
                    }
                }  
            }
        }
    ?>
</section>
<!-- end mentoring -->
</div>
</nav>

<script>
    function menyerahClicked() {
        Swal.fire({
            title: 'Konfirmasi',
            text: 'Ketik "MENYERAH" (dengan huruf besar) untuk menyerah',
            input: 'text',
            showCancelButton: true,
            confirmButtonText: 'Submit',
            cancelButtonText: 'Batal',
            inputValidator: (value) => {
                if (value !== 'MENYERAH') {
                    return 'Tulisan tidak cocok';
                }
            }
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    url: '/pesertanonasn/pelatihan-saya/menyerah',
                    type: 'POST',
                    data: {
                        id: '<?=$this->progress->id?>',
                        id_peserta: '<?=$this->progress->id_peserta?>',
                        id_batch: '<?=$this->progress->id_batch?>',
                        status_progress: '<?=$this->progress->status_progress?>',
                        status_riwayat: 'Menyerah',
                    },
                    success: function (response) {
                        window.location.href = '/pesertanonasn/riwayat';
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        console.log('Failed: ' + textStatus);
                        console.log(errorThrown);
                    }
                });
            }
        });
    }

    window.onscroll = function() {
        scrollFunction() 
    };

    function scrollFunction() {
        let button = document.getElementById("nav-icon");
        if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
            button.style.display = "flex";
        } else {
            button.style.display = "flex";
        }
    }

    function toggleNav() {
        let sidebar = document.getElementById("mySidebar");
        let navIcon = document.getElementById("nav-icon");

        if (window.innerWidth < 768) {
            if (sidebar.style.width == "100%") {
                sidebar.style.width = "0";
                navIcon.innerHTML = "&#8250;";
            } else {
                sidebar.style.width = "100%";
                navIcon.innerHTML = "&#8249;";
            }
        } else {
            if (sidebar.style.width == "250px") {
                sidebar.style.width = "0";
                document.getElementById("main").style.marginLeft = "0";
                navIcon.innerHTML = "&#8250;";
            } else {
                sidebar.style.width = "250px";
                document.getElementById("main").style.marginLeft = "250px";
                navIcon.innerHTML = "&#8249;";
            }
        }
    }
       
    function closeNav() {
        document.getElementById("mySidebar").style.width = "0";
        document.getElementById("main").style.marginLeft = "0";
    }

    // copy
    const copy1 = document.querySelectorAll(".copy1");
    const input1 = document.querySelectorAll(".input1");

    copy1.forEach((element, index) => {
        element.addEventListener("click", () => {
            input1[index].select();
            document.execCommand("copy");
            element.innerText = "Copied";
            element.style.backgroundColor = "transparent";

            setTimeout(() => {
                element.innerText = "Copy";
            }, 3000);
        });
    });
</script>
