<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pelatihan Saya</title>
    <!-- <link rel="stylesheet" href="https://berkas.dpr.go.id/mooc/assets/css/pre-test2.css"> -->
    <style>
        /* The sidebar menu */
        .sidebar {
            height: 100%;
            /* 100% Full-height */
            width: 0;
            /* 0 width - change this with JavaScript */
            position: fixed;
            /* Stay in place */
            z-index: 1;
            /* Stay on top */
            top: 0;
            left: 0;
            background-color: #FFF;
            /* Black*/
            overflow-x: hidden;
            /* Disable horizontal scroll */
            padding-top: 60px;
            /* Place content 60px from the top */
            transition: 0.5s;
            /* 0.5 second transition effect to slide in the sidebar */
            border-right: 1px solid #e5e5e5;
            box-shadow: 4px 8px 8px hsl(0deg 0% 0% / 0.38);
        }

        /* The sidebar links */
        .sidebar a {
            padding: 0px 6px 0px 45px;
            text-decoration: none;
            font-size: 18px;
            color: #818181;
            display: block;
            transition: 0.3s;
        }

        /* When you mouse over the navigation links, change their color */
        .sidebar a:hover {
            color: #f1f1f1;
        }

        .sidebar li {
            margin-left: 33px;
            color: #818181;
        }

        .sidebar p {
            padding: 8px 8px 8px 32px;
            text-decoration: none;
            font-size: 25px;
            color: #000;
            display: block;
            transition: 0.3s;
        }


        /* Position and style the close button (top right corner) */
        .sidebar .closebtn {
            position: absolute;
            top: 0;
            right: 25px;
            font-size: 36px;
            margin-left: 50px;
        }

        /* The button used to open the sidebar */
        .openbtn {
            font-size: 6x;
            cursor: pointer;
            background-color: transparent;
            color: white;
            height: 15;
            padding: 10px 15px;
            border: none;
        }

        .openbtn:hover {
            background-color: #444;
        }

        /* Style page content - use this if you want to push the page content to the right when you open the side navigation */
        #main {
            transition: margin-left .5s;
            /* If you want a transition effect */
            padding: 20px;
        }



        /* Mengatur animasi */
        @keyframes move {
            0% {
                transform: translateX(0);
            }

            50% {
                transform: translateX(20px);
            }

            100% {
                transform: translateX(0);
            }
        }

        /* Mengatur posisi dan animasi ikon tanya */
        i {
            font-size: 100px;
            display: block;
            margin: 0 auto;
            text-align: center;
            animation: move 2s infinite;
            margin-bottom: 30px;

            /* Menambahkan bayangan */
            //box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.5);

        }

        
        .card {
box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);

}



        /* On smaller screens, where height is less than 450px, change the style of the sidenav (less padding and a smaller font size) */
        @media screen and (max-height: 450px) {
            .sidebar {
                padding-top: 15px;
            }

            .sidebar a {
                font-size: 18px;
            }
        }
    </style>


    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous"> -->

    <!-- bootstrap icon -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

</head>

<body>
    <!-- sidebar -->
    <div class="area"></div>
    <!-- <nav class="main-menu "  style="max-width: 100vw; margin-top: 85px; ">
        <ul>
            <li class="has-subnav">
                <div style="margin: 10px;">
                    <span class="nav-text">Table of Contents</span>
                </div>
                <hr>
            </li>
            <li class="has-subnav">
                <div style="margin: 20px;">
                    <a href="/peserta/pelatihan-saya/index/pretest" style="color: #212529; text-decoration: none;">
                        <span class="nav-text">Pretest</span>
                    </a>
                </div>
                <hr>
            </li>
            <li class="has-subnav">
                <div style="margin: 5px;">
                    <p>
                        <button class="accordion-button shadow-none bg-transparent text-muted px-3 collapsed dropdown-toggle" type="button" data-bs-toggle="collapse"
                            data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                            Pendahuluan
                        </button>
                    </p>
                </div>
                <div class="collapse" id="collapseExample" style="margin: 15px;">
                    <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapseExample" role="button"
                        aria-expanded="false" aria-controls="collapseExample">
                        contoh 1 
                    </a>
                </div>
                <hr>
            </li>
            <li class="has-subnav">
                <div style="margin: 20px;">
                <a href="" style="color: #212529; text-decoration: none;">
                        <p class="nav-text">Tugas Akhir</p>
                    </a>
                </div>

                <hr>
            </li>
            <li class="has-subnav">
                <div style="margin: 20px;">
                    <a href="" style="color: #212529; text-decoration: none;">
                        <p class="nav-text">Quiz</p>
                    </a>
                </div>
                <hr>
            </li>
            <li class="has-subnav">
                <div style="margin: 20px;">
                    <a href="" style="color: #212529; text-decoration: none;">
                        <p class="nav-text">Klaim Sertifikat</p>
                    </a>
                </div>
                <hr>
            </li>
            <li class="has-subnav">
                <a href="/default/index/quiz">
                        <img src="https://berkas.dpr.go.id/mooc/assets/images/quiz-black.png" alt="" class="icon" style="width: 20px; height: 20px;">
                        <span class="nav-text">Tugas Akhir</span>
                    </a>
                </li>

                <li class="has-subnav">
                    <a href="/default/index/sertifikat">
                        <img src="https://berkas.dpr.go.id/mooc/assets/images/tugas-akhir-black.png" alt="" class="icon" style="width: 20px; height: 20px;">
                        <span class="nav-text">Sertifikat</span>
                    </a>
                </li>
        </ul>
    </nav>
     -->

    <!-- end sidebar -->
    <nav class="main-menu " style="max-width: 100vw; margin-top: 85px; ">
        <div id="mySidebar" class="sidebar" style=" margin-top: 85px; ">
            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
            <p class="fs-5">Table of Contents</p>
            <hr>
            <a href="/peserta/pretest/index">Pretest</a>
            <hr>
            <div style="margin-left: -30px;">
                <?php

                foreach ($this->rows as $id => $silabus) {
                    //  var_dump($silabus);
                    if ($silabus != 0) {
                        // var_dump($materi->nama_materi);
                        foreach ($this->rows3 as $id => $materi1) {
                            if ($materi1->id_silabus == $silabus->id) {

                                echo '<div>';
                                echo '<ul>';
                                echo ' <a class=" collapsed dropdown-toggle" type="button" data-bs-toggle="collapse"
                                            data-bs-target="#a' . $silabus->id . '" aria-expanded="false" aria-controls="collapseExample">' . $silabus->nama_silabus . ' </a>';
                                echo '</ul>';
                                echo '</div>';
                                echo ' <div class="collapse" id="a' . $silabus->id . '" >';
                                echo '<ul >';

                                foreach ($this->rows3 as $id => $materi) {
                                    if ($materi->id_silabus == $silabus->id) 
                                    {
                                        echo '<li>
                                                    <a style="margin-left: 0px;" href="/peserta/pelatihan-saya/materi/id/49/silabus/' . $materi->id_silabus . '/konten/' . $materi->id . '">' . $materi->nama_materi . '</a>
                                                </li>';
                                    }
                                }
                                echo '</ul>';
                                echo '</div>';
                            }
                        }
                    }
                }

                ?>

            </div>

            <hr>
            <a href="#">Quiz</a>
            <hr>
            <a href="#">Mentoring</a>
            <hr>
            <a href="#">Tugas Akhir</a>
            <hr>
            <a href="#">Sertifikat</a>
            <hr>
        </div>

        <div id="main">
            <button class="openbtn d-flex p-0" onclick="openNav()" style="width: 50px; margin-left: -21px;">
                <span class="d-flex justify-content-center "
                    style="width: 100%;  padding: 7px; font-size: 50px; color: #D4A216; border-top-right-radius: 20px; border-bottom-right-radius: 20px; border:1px solid #D4A216;">
                    &#8250;
                </span>
            </button>
            <!-- <p>Content...
            </p> -->

<!-- <div class="container" style="border:1px solid red;">
<h1>tes</h1>
</div> -->

            <div class="row " style="margin-top:10px;   margin-left: 120px; margin-right: 120px;">
                <div class="col-12">
                    <div class="card" style="border-radius: 10px;">
                        <div class="card-body" style="font-size:25px; color: #808080; ">
                            <a href="/peserta/index/" style="color: #808080;">Belajar Saya</a> | <a href="/peserta/pelatihan"  style="color: #808080;">Pelatihan</a> | <a style="color: #000;"><?= $this->rows2['nama_pelatihan'];?></a>
                        </div>
                    </div>
                </div>
            </div>



        </div>

        </div>

        <!-- Modal -->
        <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog"
            aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle"></h5>
                    </div>
                    <div class="modal-body">
                        <i class="bi bi-question-circle"></i>
                        <h1 style=" text-align:center;">
                            Mulai Latihan
                        </h1>
                        <h4 style=" text-align:center; color: #808080;">
                            Sebelum memulai pelajaran, silahkan membaca panduan terlebih dahulu
                        </h4>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary mx-auto">Lihat Panduan</button>
                        <button type="button" class="btn btn-success mx-auto" id="myBtn">Mulai Belajar</button>
                    </div>
                </div>
            </div>
        </div>


        <!-- Script untuk memunculkan modal -->
        <script>
            $(document).ready(function () {
                $('#exampleModalCenter').modal('show');
                $("#myBtn").click(function () {
                    $("#exampleModalCenter").modal("hide");
                });

            });
        </script>


        <script>
            /* Set the width of the sidebar to 250px and the left margin of the page content to 250px */
            function openNav() {
                document.getElementById("mySidebar").style.width = "250px";
                document.getElementById("main").style.marginLeft = "250px";
            }

            /* Set the width of the sidebar to 0 and the left margin of the page content to 0 */
            function closeNav() {
                document.getElementById("mySidebar").style.width = "0";
                document.getElementById("main").style.marginLeft = "0";
            }
        </script>
</body>

</html>