<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pelatihan Saya</title>
    <!-- <link rel="stylesheet" href="https://berkas.dpr.go.id/mooc/assets/css/pre-test2.css"> -->
    <style>
        /* The sidebar menu */
        .sidebar {
            height: 100%;
            /* 100% Full-height */
            width: 0;
            /* 0 width - change this with JavaScript */
            position: fixed;
            /* Stay in place */
            z-index: 1;
            /* Stay on top */
            top: 0;
            left: 0;
            background-color: #FFF;
            /* Black*/
            overflow-x: hidden;
            /* Disable horizontal scroll */
            padding-top: 60px;
            /* Place content 60px from the top */
            transition: 0.5s;
            /* 0.5 second transition effect to slide in the sidebar */
            border-right: 1px solid #e5e5e5;
            box-shadow: 4px 8px 8px hsl(0deg 0% 0% / 0.38);
        }

        /* The sidebar links */
        .sidebar a {
            padding: 0px 6px 0px 45px;
            text-decoration: none;
            font-size: 18px;
            color: #818181;
            display: block;
            transition: 0.3s;
        }

        /* When you mouse over the navigation links, change their color */
        .sidebar a:hover {
            color: #f1f1f1;
        }

        .sidebar li {
            margin-left: 33px;
            color: #818181;
        }

        .sidebar ul {

            color: #818181;
        }

        .sidebar hr {
            border: none;
            border-top: 1px solid black;
            margin: 1em 0;
        }


        .sidebar p {
            padding: 8px 8px 8px 32px;
            text-decoration: none;
            font-size: 25px;
            color: #000;
            display: block;
            transition: 0.3s;
        }

        a.collapsed {
            display: inline-block;
            text-overflow: ellipsis;
            overflow: hidden;
            white-space: nowrap;
            max-width: 220px;
            /* Atur lebar maksimal link */
        }

        a.collapsed[aria-expanded="true"] {
            white-space: normal;
        }


        /* Position and style the close button (top right corner) */
        .sidebar .closebtn {
            position: absolute;
            top: 0;
            right: 25px;
            font-size: 36px;
            margin-left: 50px;
        }


        /* The button used to open the sidebar */
        .openbtn {
            font-size: 6x;
            cursor: pointer;
            background-color: transparent;
            color: white;
            height: 15;
            padding: 10px 15px;
            border: none;
        }

        .checkmark {
            position: relative;
            width: 50px;
            height: 50px;
            border-radius: 50%;
            border: 3px solid #43A047;
            margin: 20px auto;
            animation: drawCircle 0.5s ease-in-out 0.5s forwards;
        }

        .checkmark:after {
            content: "";
            position: absolute;
            top: 50%;
            left: 25%;
            width: 12px;
            height: 25px;
            border: solid #FFFFFF;
            border-width: 0 4px 4px 0;
            transform: translateY(-50%) rotate(45deg);
            opacity: 0;
            animation: drawCheck 0.5s ease-in-out 1s forwards;
        }

        @keyframes drawCircle {
            to {
                stroke-dashoffset: 0;
            }
        }

        @keyframes drawCheck {
            to {
                opacity: 1;
                transform: translateY(-50%) rotate(45deg);
            }
        }

        /* .openbtn:hover {
            background-color: #444;
        } */

        /* Style page content - use this if you want to push the page content to the right when you open the side navigation */
        #main {
            transition: margin-left .5s;
            /* If you want a transition effect */
            padding: 20px;
        }

        .card {
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);

        }

        /* On smaller screens, where height is less than 450px, change the style of the sidenav (less padding and a smaller font size) */
        @media screen and (max-height: 450px) {
            .sidebar {
                padding-top: 15px;
            }

            .sidebar a {
                font-size: 18px;
            }
        }

        @media only screen and (max-width: 600px) {
            .card-body {
                font-size: 15px;
            }

            h3 {
                font-size: 20px !important;
            }

        }
    </style>


    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous"> -->

    <!-- bootstrap icon -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">



    <!-- CSS SweetAlert 2 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.6/dist/sweetalert2.min.css" />

    <!-- JavaScript SweetAlert 2 -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.6/dist/sweetalert2.min.js"></script>

</head>

<body>
    <!-- sidebar -->
    <div class="area"></div>

    <nav class="main-menu " style="max-width: 100vw; margin-top: 85px; ">
        <div id="mySidebar" class="sidebar"
            style=" margin-top: 85px; overflow-y: auto; max-height: calc(100vh - 85px); ">
            <a style="color: #D4A216;" href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
            <p class="fs-5">Table of Contents</p>
            <hr>
            <a href="/peserta/pelatihan-saya/pretest">Pretest</a>
            <hr>
            <div>

                <?php

                foreach ($this->rows as $id => $silabus) {
                    //  var_dump($silabus);
                    if ($silabus != 0) {


                        // var_dump($materi->nama_materi);
                        foreach ($this->rows3 as $id => $materi1) {
                            if ($materi1->id_silabus == $silabus->id) {

                                // echo '<div >';
                                echo '<ul style="margin-left: -35px; ">';
                                echo ' <a class=" collapsed dropdown-toggle" type="button" data-bs-toggle="collapse"
                                            data-bs-target="#a' . $silabus->id . '" aria-expanded="false" aria-controls="collapseExample">' . $silabus->nama_silabus . '</a>';
                                echo '</ul>';
                                // echo '</div>';
                                echo ' <div class="collapse" id="a' . $silabus->id . '" >';
                                echo '<ul >';

                                foreach ($this->rows3 as $id => $materi) {
                                    if ($materi->id_silabus == $silabus->id) {

                                        echo '<li>
                                                    <a style="margin-left: -42px;" href="/peserta/pelatihan-saya/materi/id/' . $materi->id_pelatihan . '/silabus/' . $materi->id_silabus . '/konten/' . $materi->id . '">' . $materi->nama_materi . ' <br><i class="bi bi-check-circle-fill"></i> Selesai</a>
                                                    
                                                </li>';

                                        // var_dump($materi);
                                    }
                                }
                                echo '</ul>';
                                echo '</div>';



                            }
                        }
                    }
                }

                ?>

            </div>


            <hr>
            <a href="#">Quiz</a>
            <hr>
            <a href="#">Mentoring</a>
            <hr>
            <a href="#">Tugas Akhir</a>
            <hr>

            <a href="/peserta/sertifikat/index/id/<?= $this->batch->id ?>">Sertifikat</a>


            <hr>
        </div>

        <div id="main">
            <button class="openbtn d-flex p-0" onclick="openNav()" style="width: 50px;     margin-left: -18px;">
                <span class="d-flex justify-content-center " style="width: 65%;
    height: 100px;
    margin-top: -33px;
    font-size: 50px;
    color: #D4A216;
   ">
                    &#8250;
                </span>
            </button>
            <!-- <p>Content...
            </p> -->
            <div class="row" style=" margin-top: -58px;  ">

                <div class=" col-1">
                </div>
                <div class=" col-10">
                    <div class="card" style="border-radius: 10px; ">
                        <div class="card-body" style=" color: #808080; ">
                            <a href="/peserta/index/" style="color: #808080;">Belajar Saya</a> | <a
                                href="/peserta/pelatihan" style="color: #808080;">Pelatihan</a> |
                            <a style="color: #808080;"
                                href="/peserta/pelatihan-saya/pretest/id/<?= $this->rows5['id']; ?>"> <?= $this->rows5['nama_pelatihan']; ?>
                            </a> | <a style="color: #808080;">
                                <?= $this->rows6['nama_silabus']; ?>
                            </a>
                        </div>
                    </div>

                </div>
                <div class=" col-1">
                </div>
            </div>
            <div class="row" style="margin-top:10px;">
                <div class="col-1">
                </div>
                <div class="col-10">
                    <div class="card">
                        <div class="card-body">

                            <?php

                            echo '<h3>' . $this->rows4['nama_materi'] . '</h3>';
                            //echo '<p>' . $this->rows4['deskripsi_materi'] . '</p>';
                            //echo '<h4>Jumlah JP = ' . $this->rows4['jumlah_jp'] . '</h4>';
                            //echo '<br>';
                            ?>
                        </div>
                    </div>

                </div>
                <div class="col-1">
                </div>
            </div>

            <div class="row" style="margin-top:10px;">
                <div class="col-1">
                </div>
                <div class="col-10">
                    <div class="card">
                        <div class="card-body">

                            <?php

                            if ($this->rows4['gambar_materi_uri'] == "") {
                                echo '';

                            } else {
                                echo '<div  style="margin:5px; text-align:center;"><img style="position: relative; display: inline; max-width: 100%;" src="https://berkas.dpr.go.id/mooc/gambarmateri/' . $this->rows4['gambar_materi_uri'] . '"  /></div>';

                            }

                            if ($this->rows4['document_materi_uri'] == "") {
                                echo '';

                            } else {
                                echo '<div style=" margin:5px; text-align:center;"><a href="https://berkas.dpr.go.id/mooc/filemateri/' . $this->rows4['document_materi_uri'] . '" target="_blank" download>
                   <button class="btn btn-danger ">Download File</button></a></div>';

                            }


                            if ($this->rows4['audio_materi_uri'] == "") {
                                echo '';

                            } else {
                                echo '<div style="margin:5px; text-align:center;"><audio style="position: relative;
                                display: inline;
                            max-width: 100%;" src="https://berkas.dpr.go.id/mooc/filemateri/' . $this->rows4['audio_materi_uri'] . '" controls></audio></div>';

                            }

                            if ($this->rows4['video_materi_uri'] == "") {
                                echo '';

                            } else {
                                echo '<div style="margin:5px; "><video controls style=" border-radius: 13px; position:relative; width: 100%;">
                   <source src="https://berkas.dpr.go.id/mooc/filemateri/' . $this->rows4['video_materi_uri'] . '" type="video/mp4">
                   Your browser does not support the video tag.
               </video> </div>';

                            }

                            if ($this->rows4['isi_materi'] == "") {
                                echo '';

                            } else {
                                echo '<div style="margin:5px;">';
                                echo $this->rows4['isi_materi'];
                                echo '</div>';
                            }



                            // <embed type="application/pdf" src="https://berkas.dpr.go.id/mooc/filemateri/'.$this->rows4['document_materi_uri'].'" width="600"></embed>
                            // <iframe src="https://berkas.dpr.go.id/mooc/filemateri/'.$this->rows4['document_materi_uri'].'" width="100%" height="600px"></iframe>
                            
                            ?>
                        </div>
                    </div>

                </div>

                <div class="col-1">
                </div>
            </div>


            <div class="row" style="margin-top:10px;">
                <div class="col-1">
                </div>
                <div class="col-10">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-12 col-sm-7" style="text-align: center;">
                                    <h3 style="color: #808080;">Apakah Anda Sudah Memahami?</h3>
                                </div>
                                <div class="col-12 col-sm-1">

                                </div>

                                <div class="col-12 col-sm-3" style="text-align: center;">
                                    <input type="hidden" value="3" id="tes">
                                    <button type="button" class="btn " id="myBtn"
                                        style=" color:#fff;background-color: #D4A216;">
                                        <i class="bi bi-check-circle-fill"></i>
                                        Saya Sudah Paham
                                    </button>


                                </div>
                            </div>




                        </div>
                    </div>

                </div>
                <div class="col-1">
                </div>
            </div>


        </div>
    </nav>



    <script>
        document.getElementById('myBtn').addEventListener('click', function () {
            Swal.fire({
                title: 'Mantap!',
                text: 'Pelatihan ini berhasil kamu selesaikan. Lanjut ke materi selanjutnya ya.',
                icon: 'success',
                showCancelButton: false,
                confirmButtonClass: 'btn btn-primary',
                confirmButtonText: 'Oke!',
            })
                .then(function (result) {
                    if (result.isConfirmed) {
                        // extract the current lesson id from the URL
                        var currentLessonId = parseInt(window.location.href.split('/').pop());
                        // get the last lesson id from the silabus URL
                        var lastLessonId = 158; // replace with the actual last lesson id
                        // check if there is a next lesson available
                        if (currentLessonId < lastLessonId) {
                            // increment the current lesson id by one to get the next lesson id
                            var nextLessonId = currentLessonId + 1;
                            // construct the URL of the next lesson's silabus
                            var nextLessonSilabusUrl = + nextLessonId;
                            // redirect to the next lesson's silabus
                            window.location.href = nextLessonSilabusUrl;
                        } else {
                            // display a message to the user that there is no next lesson available
                            Swal.fire({
                                title: 'Maaf!',
                                text: 'Pelajaran ini adalah pelajaran terakhir dari silabus ini. Tunggu pelajaran selanjutnya ya!',
                                icon: 'warning',
                                showCancelButton: false,
                                confirmButtonClass: 'btn btn-primary',
                                confirmButtonText: 'Oke!',
                            });
                        }
                    }
                });
        });



        $('#myBtn').click(function () {
            var id = $('#tes').val();
            var selectedId = $('#id').val();
            console.log(id);
            $.ajax({
                url: "peserta/progresbelajar",
                data: { 'id': id },
                type: "post",
                cache: false,

                error: function (xhr, ajaxOptions, thrownError) {
                    $('#lblCommentsNotification').text("Error encountered while saving the comments.");
                }
            });
        });
    </script>



    <script>
        /* Set the width of the sidebar to 250px and the left margin of the page content to 250px */
        function openNav() {
            if (window.innerWidth < 768) {
                document.getElementById("mySidebar").style.width = "100%";
            } else {
                document.getElementById("mySidebar").style.width = "250px";
                document.getElementById("main").style.marginLeft = "250px";
            }
        }

        /* Set the width of the sidebar to 0 and the left margin of the page content to 0 */
        function closeNav() {
            document.getElementById("mySidebar").style.width = "0";
            document.getElementById("main").style.marginLeft = "0";
        }
    </script>
</body>

</html>