<script type="text/javascript">
	$(document).ready(function() {
		$("#compose").validate();
	})
</script>

<div class="content-header"></div>
<div class="UI_Header_Title">
	<h1><?=$this->avatar;?>Edit Nilai Mentoring</h1>
	<div class="header_nav_links"><a href="/mentor/nilai-mentoring/index">Back to Daftar Nilai Mentoring</a></div>
</div>
<div class="clear"></div>
<form id="compose" name="compose" method="post" action="" enctype="multipart/form-data">
	<div class="tabular">
		<p>
			<label>Batch</label>
			<input readonly type="text" id="judul_batch" autocomplete="disable" name="judul_batch" style="height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;" value="<?= $this->batch->judul_batch ?>" />
			<input type="hidden" id="id_batch" autocomplete="disable" name="id_batch" value="<?= $this->batch->id ?>" />
		</p>
		<p id="daftar-peserta" class="daftar-user">
			<label>Nama Peserta</label>
			<input readonly type="text" id="nama_peserta" autocomplete="disable" name="nama_peserta" style="height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;" value="<?= $this->peserta->nama ?>" />
			<input type="hidden" id="id_peserta" autocomplete="disable" name="id_peserta" value="<?= $this->peserta->id ?>" />
		</p>

		<p>
			<label class="left" for="skor_keaktifan">Skor Keaktifan</label>
			<input type="text" id="skor_keaktifan" class="event-message" wrap="soft" name="skor_keaktifan"  style="height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;" value="<?= $this->row->skor_keaktifan ?>">
		</p>

        <p>
			<label class="left" for="skor_pemahaman">Skor Pemahaman</label>
			<input type="text" id="skor_pemahaman" class="event-message" wrap="soft" name="skor_pemahaman"  style="height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;" value="<?= $this->row->skor_pemahaman ?>">
		</p>

		<p>
			<label class="left" for="skor_forum">Skor Forum</label>
			<input type="text" id="skor_forum" class="event-message" wrap="soft" name="skor_forum"  style="height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;" value="<?= $this->row->skor_forum ?>">
		</p>

        <p>
			<label class="left" for="skor_tugas">Skor Tugas</label>
			<input type="text" id="skor_tugas" class="event-message" wrap="soft" name="skor_tugas"  style="height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;" value="<?= $this->row->skor_tugas ?>">
		</p>
		
		<p class="savecancel"><label class="UIbutton-small"><input type="submit" value="Simpan" class=""/></label><a href="/mentor/nilai-mentoring/index" class="UIbutton-small">Batal</a></p>
	</div>
</form>
<div style="clear:both"></div>