<?
setlocale(LC_ALL, 'id_ID.UTF8', 'id_ID.UTF-8', 'id_ID.8859-1', 'id_ID', 'IND.UTF8', 'IND.UTF-8', 'IND.8859-1', 'IND', 'Indonesian.UTF8', 'Indonesian.UTF-8', 'Indonesian.8859-1', 'Indonesian', 'Indonesia', 'id', 'ID', 'en_US.UTF8', 'en_US.UTF-8', 'en_US.8859-1', 'en_US', 'American', 'ENG', 'English'); 

$content = '<page backimg="https://berkas.dpr.go.id/mooc/assets/images/bgsertif2.jpg" orientation="l" style="font-family: Arial; font-size: 12px; line-height: 1.5;" backtop="20mm" backbottom="20mm" backleft="20mm" backright="20mm">
<table style="width: 100%;">
	<col style="width: 100%">
	<tr><td align="center" style="font-size: 70px;">SERTIFIKAT</td></tr>
	<tr><td align="center">Dengan bangga diberikan kepada</td></tr>
</table>
<br>
<br>
<br>
<table style="width: 100%;">
	<col style="width: 100%">
	<tr><td align="center" style="font-size: 30px;"><b><u>NAMA PESERTA</u></b></td></tr>
</table>
<br>
<br>


<table style="width: 100%;">
<col style="width: 100%">
	<tr>
		<td align="center">Telah Menyelesaikan:</td>
	</tr>
	<tr>
		<td align="center" style="font-size: 20px;"><b><u>PELATIHAN LARAVEL DASAR</u></b></td>
	</tr>
	<tr>
		<td>
			<br><br>
		</td>
	</tr>
	<tr>
		<td align="center">Pada Tanggal (x bulan - x bulan 202x)</td>
	</tr>
</table>
<br>
<br>
<br>
<table style="width: 100%">
	<col style="width: 50%">
	<col style="width: 50%">
	<tr>
		<td align="center">
			<table style="width:100%;">
				<col style="width: 100%">
				<tr><td align="center">Kepala Pusat Pendidikan dan Pelatihan</td></tr>
				<tr><td align="center"><br><br></td></tr>
				<tr><td align="center"><br><br></td></tr>
				<tr><td align="center"><u>Nama KAPUSDIKLAT</u></td></tr>
				<tr><td align="center">NIP. ______</td></tr>
			</table>
		</td>
		<td align="center">
			<table style="width:100%;">
				<col style="width: 100%">
				<tr><td align="center">Jakarta, _______</td></tr>
				<tr><td align="center">Pengajar,</td></tr>
				<tr><td align="center"><br><br></td></tr>
				<tr><td align="center"><br><br><br></td></tr>
				<tr><td align="center"><u>NAMA PENGAJAR</u></td></tr>
				<tr><td align="center">NIP/NIK. ____ </td></tr>
			</table>
		</td>
	</tr>
</table>

</page>

<page orientation="l" style="font-family: Arial; font-size: 12px; line-height: 1.5;" backtop="20mm" backbottom="20mm" backleft="20mm" backright="20mm">
<table style="width: 100%;">
	<col style="width: 100%">
	<tr><td align="center" style="font-size: 40px;"><b>MATERI</b></td></tr>
	<tr><td align="center" style="font-size: 20px;"><b><u>PELATIHAN LARAVEL DASAR</u></b></td></tr>
</table>
<br>
<br>

<br>
<table style="border: 1px solid black; border-collapse: collapse;">
	<col style="width: 5%">
	<col style="width: 50%">
	<col style="width: 20%">
	<col style="width: 25%">
	<col style="width: 5%">
<thead>
	<tr>
		<th style="border: 1px solid black; padding: 10px; text-align: center;">No</th>
		<th style="border: 1px solid black; padding: 10px; text-align: center;">Materi</th>
		<th style="border: 1px solid black; padding: 10px; text-align: center;">Nilai</th>
		<th style="border: 1px solid black; padding: 10px; text-align: center;">Jam Pelajaran (JP)</th>
	</tr>
</thead>
<tbody>
	<tr>
		<td style="border: 1px solid black; padding: 10px; text-align: center;">1</td>
		<td style="border: 1px solid black; padding: 10px; text-align: center;">Matematika</td>
		<td style="border: 1px solid black; padding: 10px; text-align: center;">90</td>
		<td style="border: 1px solid black; padding: 10px; text-align: center;">2JP</td>
	</tr>
</tbody>
</table>
<br>
<br>
<br>
<table cellspacing="0" style="width:50%;">
	<col style="width: 5%">
	<col style="width: 50%">
	<col style="width: 5%">
	<col style="width: 15%">
	<col style="width: 5%">
	<tr>
		<td align="center">1.</td>
		<td><b>Nilai Akhir</b></td>
		<td align="center">:</td>
		<td align="right">' . $this->FormatNumber($this->row->potongan1) . '</td>
		<td></td>
	</tr>
	<tr>
		<td align="center">2.</td>
		<td><b>Total Jam Pelajaran (JP)</b></td>
		<td align="center">:</td>
		<td align="right">' . $this->FormatNumber($this->row->potongan1) . '</td>
		<td></td>
	</tr>
</table>
</page>';



$html2pdf = new HTML2PDF('L','A4','en');
$html2pdf->WriteHTML($content);
$html2pdf->Output('TEST.pdf');
?>
