<script type="text/javascript">
	$(document).ready(function() {
		$("#compose").validate();
	})
	function selectFields1(id, id, username) {
		$('#id_user').val(id);
		$('#username').val(username);
		$.facebox.close();
	}

	function ClearFields1() {
		document.getElementById("id_user").value = "";
		document.getElementById("username").value = "";
	}
</script>

<div class="content-header"></div>
<div class="UI_Header_Title">
	<h1><?=$this->avatar;?>Tambah Mentor</h1>
	<div class="header_nav_links"><a href="/admin/mentor/index">Back to Daftar Mentor</a></div>
</div>
<div class="clear"></div>
<form id="compose" name="compose" method="post" action="" enctype="multipart/form-data">
	<div class="tabular">

		<p><label>User</label>
			<input readonly type="text" id="username" autocomplete="disable" name="username" style="height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;" />
			<input type="hidden" id="id_user" autocomplete="disable" name="id_user"/>
			<input type="button" value="..." id="btnuser" style="height:30px;" onclick="jQuery.facebox({ ajax: '/admin/mentor/search-user'});">
			<input type="button" style="height:30px;" onclick="ClearFields1();" value="Clear">
			<font color="red">*</font>
		</p>
		<p>
			<label class="left" for="nama_mentor">Nama Mentor</label>
			<input type="text" id="nama_mentor" class="event-message" wrap="soft" name="nama_mentor" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;"> 
		</p>
		<p>
			<label class="left" for="identitas_mentor">NIP/NIK</label>
			<input type="number" id="identitas_mentor" class="event-message" wrap="soft" name="identitas_mentor" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;">
		</p>
		<p>
			<label class="left" for="instansi">Asal Instansi</label>
			<input type="text" id="instansi" class="event-message" wrap="soft" name="instansi" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;">
		</p>
		<p>
			<label class="left" for="email">Email</label>
			<input type="email" id="email" class="event-message" wrap="soft" name="email" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;">
		</p>
		<p>
			<label class="left" for="no_telp">No Telp</label>
			<input type="number" id="no_telp" class="event-message" wrap="soft" name="no_telp" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;">
		</p>
		<p>
			<label class="left" for="fotomentor_uri">Foto Mentor</label> 
			<input type="file" accept="image/*" id="file_name" name="file_name">
		</P>
		
		<p class="savecancel"><label class="UIbutton-small"><input type="submit" value="Simpan" class=""/></label><a href="/admin/mentor/index" class="UIbutton-small">Batal</a></p>
	</div>
</form>
<div style="clear:both"></div>