<?php
    $id_batch = "-";
    $nama_pelatihan = "-";
    $sampul_pelatihan = "-";
    $lanjut = '';
    $persen = 0;
    $jp = 0;

    if(count($this->batch) > 0){
        $id_batch = $this->progress->id_batch;
        foreach($this->batch as $val){
            $nama_pelatihan = $val->nama_pelatihan;
            $sampul_pelatihan = $val->sampul_pelatihan;
        }
        $progress = explode("-", $this->progress->status_progress);

        if($progress[0] == 'Terdaftar'){
            $lanjut = '#';
            $persen = 0;
        }

        if($progress[0] == 'Peserta'){
            $lanjut = '/peserta/pelatihan-saya/pretest/id/'.$id_batch;
            $persen = 1;
        } else if($progress[0] == 'Pretest'){
            $lanjut = '/peserta/pelatihan-saya/pretest/id/'.$id_batch;
            $persen = 5;
        } else if ($progress[0] == 'Materi'){
            $lanjut = '/peserta/pelatihan-saya/belajar/id/'.$id_batch.'/silabus/'.$progress[1].'/materi/'.$progress[2];
            $persen = 20;
        } else if ($progress[0] == 'Quiz'){
            $lanjut = '/peserta/pelatihan-saya/quiz/id/'.$id_batch;
            $persen = 25;
        } else if ($progress[0] == 'Mentoring'){
            $lanjut = '/peserta/pelatihan-saya/mentoring/id/'.$id_batch;
            $persen = 30;
            $jp = 10;
        } else if ($progress[0] == 'Penugasan'){
            $lanjut = '/peserta/pelatihan-saya/penugasan/id/'.$id_batch;
            $persen = 60;
            $jp = 30;
        } else if ($progress[0] == 'Penilaian'){
            $lanjut = '/peserta/pelatihan-saya/penugasan/id/'.$id_batch;
            $persen = 95;
            $jp = 100;
        }  else if ($progress[0] == 'Sertifikat'){
            $lanjut = '/peserta/pelatihan-saya/sertifikat/id/'.$id_batch;
            $persen = 100;
        }
    }
?>

<script src="https://code.jquery.com/jquery-3.6.1.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.6/dist/sweetalert2.min.css" />
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.6/dist/sweetalert2.min.js"></script>
<link rel="stylesheet" href="https://berkas.dpr.go.id/mooc/assets/css/dashboard.css">

<!-- sidebar -->
<div class="area"></div>
<nav class="main-menu background-content" style="max-width: 100vw;" onmouseover="changeMarginLeft(20)" onmouseout="changeMarginLeft(0)">
    <ul class="background-content">
        <li class="has-subnav active">
            <a href="/pesertanonasn/index">
                <img src="https://berkas.dpr.go.id/mooc/assets/images/dashboard-white.png" alt="" class="icon" style="width: 20px; height: 20px;">
                <span class="nav-text">Dashboard</span>
            </a>
        </li>

        <li class="has-subnav">
            <a href="/pesertanonasn/pelatihan">
                <img src="https://berkas.dpr.go.id/mooc/assets/images/pelatihan-black.png" alt="" class="icon" style="width: 20px; height: 20px;">
                <span class="nav-text">Pelatihan</span>
            </a>    
        </li>

        <li class="has-subnav">
            <a href="/pesertanonasn/forum">
                <img src="https://berkas.dpr.go.id/mooc/assets/images/forum-black.png" alt="" class="icon" style="width: 20px; height: 20px;">
                <span class="nav-text">Forum</span>
            </a>    
        </li>

        <li class="has-subnav">
            <a href="/pesertanonasn/riwayat">
                <img src="https://berkas.dpr.go.id/mooc/assets/images/hourglass-split.svg" alt="" class="icon" style="width: 20px; height: 20px;">
                <span class="nav-text">Riwayat</span>
            </a>
        </li>
    </ul>
</nav>
<!-- end sidebar -->

<!-- content pembelajaran saya -->
<section class="container-pembelajaran-saya d-flex flex-column rounded-4 mb-5" style="max-width: 80vw; margin-left: 10%; padding-top: 150px;">
    <div class="mb-2">
        <p class="fs-3 fw-bold">Pembelajaran saya</p>
    </div>
    <div class="row content-pembelajaran-saya d-flex flex-row justify-content-between rounded-4" style="width: 100%;">
        <div class="col-md-3 background-content d-flex flex-column justify-content-center rounded-4 p-3" style="width: 32%; background-color: #E5E7E9; box-shadow: 2.0px 4.0px 4.0px hsl(0deg 0% 0% / 0.38);">
            <p class="fs-6 m-0">Pelatihan yang sedang diikuti</p>
            <p class="fs-7 m-0" style="color: #D4A216;"><?= count($this->batch) ?></p>
        </div>
        <div class="col-md-3 background-content d-flex flex-column justify-content-center rounded-4 p-3" style="width: 32%; background-color: #E5E7E9; box-shadow: 2.0px 4.0px 4.0px hsl(0deg 0% 0% / 0.38);">
            <p class="fs-6 m-0">Quiz yang dikerjakan</p>
            <p class="fs-7 m-0" style="color: #D4A216;">0</p>
        </div>
        <div class="col-md-3 background-content d-flex flex-column justify-content-center rounded-4 p-3" style="width: 32%; background-color: #E5E7E9; box-shadow: 2.0px 4.0px 4.0px hsl(0deg 0% 0% / 0.38);">
            <p class="fs-6 m-0">Sertifikat saya</p>
            <p class="fs-7 m-0" style="color: #D4A216;"><?= count($this->sertifikat) ?></p>
        </div>
    </div>
</section>
<!-- end content pembelajaran saya -->

<!-- content mulai belajar -->
<section class="container-mulai-belajar d-flex flex-column rounded-4 mb-5" style="max-width: 80vw; margin-left: 10%;">
    <div class="mb-2">
        <p class="fs-3 fw-bold">Mulai belajar</p>
    </div>

    <div class="row content-mulai-belajar d-flex flex-row justify-content-between rounded-4" style="width: 100%;">
        <div class="col-md-3 background-content d-flex flex-column justify-content-center align-items-center rounded-4 p-3" style="width: 24%; background-color: #E5E7E9; box-shadow: 2.0px 4.0px 4.0px hsl(0deg 0% 0% / 0.38);">
            <span class="d-flex justify-content-center align-items-center fs-4 fw-bold text-light rounded-circle mb-2" style="width: 60px; height: 60px; background-color: #D4A216">1</span>
            <p class="m-0 text-center fs-5 fw-bold">Pilih Kelas Online</p>
            <p class="text-center" style="font-size: 14px">Pilih pelatihan yang ingin kamu pelajari</p>
        </div>

        <div class="col-md-3 background-content d-flex flex-column justify-content-center align-items-center rounded-4 p-3" style="width: 24%; background-color: #E5E7E9; box-shadow: 2.0px 4.0px 4.0px hsl(0deg 0% 0% / 0.38);">
            <span class="d-flex justify-content-center align-items-center fs-4 fw-bold text-light rounded-circle mb-2" style="width: 60px; height: 60px; background-color: #D4A216">2</span>
            <p class="m-0 text-center fs-5 fw-bold">Ikuti Materi</p>
            <p class="text-center" style="font-size: 14px">Simak dan praktekan, ikuti materi secara berurutan</p>
        </div>

        <div class="col-md-3 background-content d-flex flex-column justify-content-center align-items-center rounded-4 p-3" style="width: 24%; background-color: #E5E7E9; box-shadow: 2.0px 4.0px 4.0px hsl(0deg 0% 0% / 0.38);">
            <span class="d-flex justify-content-center align-items-center fs-4 fw-bold text-light rounded-circle mb-2" style="width: 60px; height: 60px; background-color: #D4A216">3</span>
            <p class="m-0 text-center fs-5 fw-bold">Praktek</p>
            <p class="text-center" style="font-size: 14px">Praktekan materi, jika ada kebingungan tanyakan di forum</p>
        </div>

        <div class="col-md-3 background-content d-flex flex-column justify-content-center align-items-center rounded-4 p-3" style="width: 24%; box-shadow: 2.0px 4.0px 4.0px hsl(0deg 0% 0% / 0.38);">
            <span class="d-flex justify-content-center align-items-center fs-4 fw-bold text-light rounded-circle mb-2" style="width: 60px; height: 60px; background-color: #D4A216">4</span>
            <p class="m-0 text-center fs-5 fw-bold">Klaim Sertifikat</p>
            <p class="text-center" style="font-size: 14px">Dapatkan sertifikat dan lanjutkan belajar ke kelas lain</p>
        </div>
    </div>
</section>
<!-- end content mulai belajar -->

<!-- pembelajaran terbaru -->
<section class="container-pembelajaran-terbaru d-flex flex-column rounded-4 mb-5" style="max-width: 80vw; margin-left: 10%;">
    <div class="mb-2">
        <p class="fs-3 fw-bold">Pembelajaran terbaru</p>
    </div>

    <div class="content-pembelajaran-terbaru background-content d-flex flex-row justify-content-between rounded-4 p-5" style="width: 100%; background-color: #E5E7E9; box-shadow: 2.0px 4.0px 4.0px hsl(0deg 0% 0% / 0.38);">
        <img class="me-3 rounded-4" src="https://berkas.dpr.go.id/mooc/thumbkelas/<?= $sampul_pelatihan ?>" alt="" style="height: 150px; box-shadow: 2.0px 4.0px 4.0px hsl(0deg 0% 0% / 0.38);">
        <div class="sub-content-pembelajaran-terbaru d-flex flex-column justify-content-evenly" style="width: 100%;">
            <p class="mb-0 fw-bold"><?= $nama_pelatihan ?></p>
            <div class="mb-2 d-flex flex-row align-items-center">
                <div class="processing d-flex sub-background-content flex-row align-items-center me-3 rounded-5" style="width: 95%; height: 15px; border: 1px solid #D4A216">
                  <div class="processing-bar d-flex justify-content-center align-items-center rounded-5" data-bar="<?= $persen ?>" style="width:<?= $persen ?>%; height: 100%; background-color: #D4A216;"></div>
                </div>
                <p class="fs-6 m-0 d-flex align-items-center"><?= $persen ?>%</p>
            </div>

            <?php if ($progress[0] != 'Terdaftar'): ?>
            <button class="rounded-4 fw-bold text-light" style="width: 20%; height: 35px; background-color: #D4A216; border: 1px solid #D4A216;">
                <a href="<?= $lanjut ?>" class="text-decoration-none text-light">Lanjut Belajar</a>
            </button>
            <?php endif; ?>
            
            <?php if ($progress[0] == 'Terdaftar'): ?>
            <button type="button" class="rounded-3 fw-bold text-light" style="width: 20%; height: 35px; background-color: #D4A216; border: 1px solid #D4A216;" id="lanjut-btn">
            <a  class="text-decoration-none text-light">Lanjut Belajar<i class="bi bi-lock-fill text-secondary"></i></a>
            </button>
            <?php endif; ?>
        </div>
    </div>
</section>
<!-- end pembelajaran terbaru -->

<!-- jam pembelajaran -->
<section class="container-jam-pembelajaran d-flex flex-column rounded-4 mb-5" style="max-width: 80vw; margin-left: 10%;">
    <div class="mb-2">
        <p class="fs-3 fw-bold">Jam pelajaran</p>
    </div>

    <div class="content-jam-pembelajaran background-content d-flex flex-row rounded-4 p-3" style="width: 100%; background-color: #E5E7E9; box-shadow: 2.0px 4.0px 4.0px hsl(0deg 0% 0% / 0.38);">
        <section class="row progress-circle m-0 pe-3" style="width: 20%">
            <svg class="radial-progress" data-percentage="<?= $jp ?>" viewBox="0 0 80 80">
                <circle class="incomplete" cx="40" cy="40" r="35"></circle>
                <circle class="complete " cx="40" cy="40" r="35" style="stroke-dashoffset: 39.58406743523136;"></circle>
                <text class="percentage div-text" x="50%" y="57%" transform="matrix(0, 1, -1, 0, 80, 0)"><?= $jp ?>%</text>
            </svg>
            <p class="m-0 fw-bold text-center">Total JP Pelatihan Terakhir</p>
        </section>
        <div class="d-flex flex-column justify-content-center">
            <p class="fw-bold">10% Belajar Mandiri</p>
            <p class="fw-bold">20% Mentoring</p>
            <p class="fw-bold">70% Tugas Akhir</p>
        </div>
    </div>
</section>
<!-- end jam pembelajaran -->
    
<script>
    // progress bar
    let processing = document.querySelectorAll('.processing-bar');    
    setTimeout(() => {
        processing.forEach(el => {
            el.style.opacity = 1;
            el.style.width = el.getAttribute('data-bar') + '%';
        })
    }, 500);
    // end progress bar
    
    // pie chart progress
    $(function(){
        // Remove inline styling from svg.radial-progress .complete
        $('svg.radial-progress').each(function(index, value) { 
            $(this).find('.complete').removeAttr('style');
        });

        // Activate progress animation on scroll
        $(window).scroll(function(){
            $('svg.radial-progress').each(function(index, value) { 
                // If svg.radial-progress is approximately 25% vertically into the window when scrolling from the top or the bottom
                if ( 
                    $(window).scrollTop() > $(this).offset().top - ($(window).height() * 0.75) &&
                    $(window).scrollTop() < $(this).offset().top + $(this).height() - ($(window).height() * 0.25)
                ) {
                    // Get percentage of progress
                    percent = $(this).data('percentage');

                    // Get radius of the svg's circle.complete
                    radius = $(this).find('.complete').attr('r');

                    // Get circumference (2πr)
                    circumference = 2 * Math.PI * radius;

                    // Get stroke-dashoffset value based on the percentage of the circumference
                    strokeDashOffset = circumference - ((percent * circumference) / 100);

                    // Transition progress for 1.25 seconds
                    $(this).find('.complete').animate({'stroke-dashoffset': strokeDashOffset}, 1250);
                }
            });
        }).trigger('scroll');
    });
    // end pie chart progress

    const btnLanjut = document.getElementById('lanjut-btn');
    if(btnLanjut) {
        btnLanjut.addEventListener('click', function () {
            Swal.fire({
                title: 'Maaf',
                text: 'Pelatihan anda sedang dalam proses persetujuan admin dan coach.',
                icon: 'error',
                confirmButtonText: 'OK',
                confirmButtonColor: '#4CAF50',
            });
        });
    }

    function changeMarginLeft(margin) {
        let containerPembelajaranSaya = document.querySelector('.container-pembelajaran-saya');
        let containerMulaiBelajar = document.querySelector('.container-mulai-belajar');
        let containerPembelajaranTerbaru = document.querySelector('.container-pembelajaran-terbaru');
        let containerJamPembelajaran = document.querySelector('.container-jam-pembelajaran');
        if (margin === 0) {
            containerPembelajaranSaya.classList.remove('margin-left-20');
            containerMulaiBelajar.classList.remove('margin-left-20');
            containerPembelajaranTerbaru.classList.remove('margin-left-20');
            containerJamPembelajaran.classList.remove('margin-left-20');
        } else {
            containerPembelajaranSaya.classList.add('margin-left-20');
            containerMulaiBelajar.classList.add('margin-left-20');
            containerPembelajaranTerbaru.classList.add('margin-left-20');
            containerJamPembelajaran.classList.add('margin-left-20');
        }
    }
</script>