<script type="text/javascript">
	
	$(document).ready(function() {

		$('.tambah_soal').click(function() {
			var soal = $(".sub_container_soal").length + 1;

			let idx = soal;
			$('.container_soal').append(
			`<div class="content_soal" id="content_soal_${soal}" data-soal="${soal}">
				<p class="sub_container_soal" id="soalx_${soal}" style="display:flex; flex-direction:row; margin-top:50px;">
				<label class="judul_soal" for="soal_${soal}">Soal ${soal}</label>
				<input id="input_soal_${soal}" class="input_soal" wrap="soft" name="soal[]" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;">
				<button type="button" id="hapus_soal_${soal}" class="hapus_soal" style="margin-left:10px; width:20px; font-weight: bold;"> x </button>
			</p>
			<div class="container_jawaban" id="container_jawaban_${soal}" style="display:flex; flex-direction:column">
				<p class="sub_container_jawaban_${soal} sub_container_jawaban" id="jawaban_${soal}_1" style="display:flex; flex-direction:row">
					<label class="input_jawabanx_1" for="input_jawaban_${soal}_1">Jawaban 1</label>
					<input id="input_jawaban_${soal}_1" name="jawaban[${soal-1}][]" class="event-message input_jawaban input_jawaban_${soal}" wrap="soft"style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;">
				</p>

				<p class="sub_container_jawaban_${soal} sub_container_jawaban" id="jawaban_${soal}_2" style="display:flex; flex-direction:row">
					<label class="input_jawabanx_2" for="input_jawaban_${soal}_2">Jawaban 2</label>
					<input id="input_jawaban_${soal}_2" name="jawaban[${soal-1}][]" class="event-message input_jawaban input_jawaban_${soal}" wrap="soft"style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;">
				</p>

				<p class="sub_container_jawaban_${soal} sub_container_jawaban" id="jawaban_${soal}_3" style="display:flex; flex-direction:row">
					<label class="input_jawabanx_3" for="input_jawaban_${soal}_3">Jawaban 3</label>
					<input id="input_jawaban_${soal}_3" name="jawaban[${soal-1}][]" class="event-message input_jawaban input_jawaban_${soal}" wrap="soft"style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;">
				</p>

				<p class="sub_container_jawaban_${soal} sub_container_jawaban" id="jawaban_${soal}_4" style="display:flex; flex-direction:row">
					<label class="input_jawabanx_4" for="input_jawaban_${soal}_4">Jawaban 4</label>
					<input id="input_jawaban_${soal}_4" name="jawaban[${soal-1}][]" class="event-message input_jawaban input_jawaban_${soal}" wrap="soft"style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;">
				</p>

				<p class="sub_container_jawaban_${soal} sub_container_jawaban" id="jawaban_${soal}_5" style="display:flex; flex-direction:row">
					<label class="input_jawabanx_5" for="input_jawaban_${soal}_5">Jawaban 5</label>
					<input id="input_jawaban_${soal}_5" name="jawaban[${soal-1}][]" class="event-message input_jawaban input_jawaban_${soal}" wrap="soft"style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;">
				</p>
			</div>
			<p class="container_kunci_jawaban" id="container_kunci_jawaban_${soal}">
				<label class="kunci_jawaban" for="kunci_jawaban_${soal}">Kunci Jawaban Soal ${soal}</label>
				<input style="margin-left:10px;" type="radio" class="kunci_jawaban" name="kunci_jawaban_${soal}" value="1" required checked="check"> <b>Jawaban 1</b>
				<input style="margin-left:10px;" type="radio" class="kunci_jawaban" name="kunci_jawaban_${soal}" value="2" required> <b>Jawaban 2</b>
				<input style="margin-left:10px;" type="radio" class="kunci_jawaban" name="kunci_jawaban_${soal}" value="3" required> <b>Jawaban 3</b>
				<input style="margin-left:10px;" type="radio" class="kunci_jawaban" name="kunci_jawaban_${soal}" value="4" required> <b>Jawaban 4</b>
				<input style="margin-left:10px;" type="radio" class="kunci_jawaban" name="kunci_jawaban_${soal}" value="5" required> <b>Jawaban 5</b>
			</p> </div>`);

			$('.hapus_soal').click(function() {
				var x = $(this).parent().parent().attr('data-soal');

				$(this).parent().parent().remove();

				$(".content_soal").each(function(key, item) {
					$(this).attr('id', 'content_soal_'+ (key + 1));
					$(this).attr('data-soal', 'content_soal_'+ (key + 1));
					$(this).find("p.sub_container_soal").attr('id', 'soalx_'+ (key + 1));
					$(this).find("label.judul_soal").text("Soal " + (key + 1));
					$(this).find("label.judul_soal").attr('for', 'input_soal_'+ (key + 1));
					$(this).find("input.input_soal").attr('id', 'input_soal_'+ (key + 1));
					$(this).find("button.hapus_soal").attr('id', 'hapus_soal_'+ (key + 1));
					$(this).find("div.container_jawaban").attr('id', 'container_jawaban_'+ (key + 1));
					$(this).find("input.input_jawaban").attr('name', 'jawaban['+ (key) +'][]');
					$(this).find("input.kunci_jawaban").attr('name', 'kunci_jawaban_'+ (key + 1));
					$(this).find("label.kunci_jawaban").text("Kunci Jawaban Soal " + (key + 1));
				});			
			});
		});
	});
</script>
<div class="content-header"></div>
<div class="UI_Header_Title">
	<h1><?= $this->avatar; ?> <?= $this->pelatihan->nama_pelatihan ?> > Tambah Soal Quiz</h1>
	<div class="header_nav_links"><a href="/pengajarnonasn/pelatihan/edit/id/<?= $this->pelatihan->id ?>">Kembali ke Pelatihan <?= $this->pelatihan->nama_pelatihan ?></a></div>
</div>
<div class="clear"></div>
<form id="compose" name="compose" method="post" action="" enctype="multipart/form-data">

	<div class="tabular">
		<input type="hidden" id="id_pelatihan" name="id_pelatihan" value="<?= $this->pelatihan->id; ?>" />

		<p>
			<label class="left" for="batas_waktu">Batas Waktu</label>
			<input type="number" id="batas_waktu" class="event-message required" wrap="soft" name="batas_waktu"  style="height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px; width:350px;"> menit
		</p>
		
		<div class="container_soal" id="container_soal_1" style="display:flex; flex-direction:column">
			<div class="content_soal" id="content_soal_1">
			<p class="sub_container_soal" id="soalx_1" style="display:flex; flex-direction:row">
				<label class="left" for="soal_1">Soal 1</label>
				<input id="input_soal_1" class="input_soal" wrap="soft" name="soal[]" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;">
				<button type="button" class="tambah_soal" style="margin-left:10px; width:20px; font-weight:bold;"> + </button>
			</p>

			<div class="container_jawaban" id="container_jawaban_1" style="display:flex; flex-direction:column">
				<p class="sub_container_jawaban_1" id="jawaban_1_1" style="display:flex; flex-direction:row;">
					<label class="input_jawaban" for="input_jawaban_1_1">Jawaban 1</label>
					<input id="input_jawaban_1_1" name="jawaban[0][]" class="event-message input_jawaban_1" wrap="soft" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;">
				</p>
				<p class="sub_container_jawaban_2" id="jawaban_2_2" style="display:flex; flex-direction:row">
					<label class="input_jawaban" for="input_jawaban_2_2">Jawaban 2</label>
					<input id="input_jawaban_2_2" name="jawaban[0][]" class="event-message input_jawaban_2" wrap="soft" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;">
				</p>
				<p class="sub_container_jawaban_3" id="jawaban_3_3" style="display:flex; flex-direction:row">
					<label class="input_jawaban" for="input_jawaban_3_3">Jawaban 3</label>
					<input id="input_jawaban_3_3" name="jawaban[0][]" class="event-message input_jawaban_3" wrap="soft" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;">
				</p>
				<p class="sub_container_jawaban_4" id="jawaban_4_4" style="display:flex; flex-direction:row">
					<label class="input_jawaban" for="input_jawaban_4_4">Jawaban 4</label>
					<input id="input_jawaban_4_4" name="jawaban[0][]" class="event-message input_jawaban_4" wrap="soft" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;">
				</p>
				<p class="sub_container_jawaban_5" id="jawaban_5_5" style="display:flex; flex-direction:row">
					<label class="input_jawaban" for="input_jawaban_5_5">Jawaban 5</label>
					<input id="input_jawaban_5_5" name="jawaban[0][]" class="event-message input_jawaban_5" wrap="soft" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;">
				</p>
			</div>

			<p class="container_kunci_jawaban" id="container_kunci_jawaban_1">
				<label class="kunci_jawabanx" for="kunci_jawaban_1_1">Kunci Jawaban Soal 1</label>
				<input style="margin-left:10px;" name="kunci_jawaban_1" type="radio" id="kunci_jawaban_1_1" class="kunci_jawaban_1" value="1" required checked="check"> 
				<b id="kunci_jawabanx_1_1">Jawaban 1</b>
				<input style="margin-left:10px;" name="kunci_jawaban_1" type="radio" id="kunci_jawaban_2_2" class="kunci_jawaban_2" value="2" required> 
				<b id="kunci_jawabanx_2_2">Jawaban 2</b>
				<input style="margin-left:10px;" name="kunci_jawaban_1" type="radio" id="kunci_jawaban_3_3" class="kunci_jawaban_3" value="3" required> 
				<b id="kunci_jawabanx_3_3">Jawaban 3</b>
				<input style="margin-left:10px;" name="kunci_jawaban_1" type="radio" id="kunci_jawaban_4_4" class="kunci_jawaban_4" value="4" required> 
				<b id="kunci_jawabanx_4_4">Jawaban 4</b>
				<input style="margin-left:10px;" name="kunci_jawaban_1" type="radio" id="kunci_jawaban_5_5" class="kunci_jawaban_5" value="5" required> 
				<b id="kunci_jawabanx_5_5">Jawaban 5</b>
			</p>
			</div>
		</div>
		<p class="savecancel"><label class="UIbutton-small"><input type="submit" value="Simpan" class="" /></label><a href="/pengajarnonasn/pelatihan/edit/id/<?= $this->pelatihan->id ?>" class="UIbutton-small">Batal</a></p>
	</div>
</form>
<div style="clear:both"></div>