<script type="text/javascript">
	$(document).ready(function() {
		$("#compose").validate();
	})

	function selectFields1(id, id, judul_batch) {
		$('#id_batch').val(id);
		$('#judul_batch').val(judul_batch);
		$.facebox.close();
	}

	function ClearFields1() {
		document.getElementById("id_batch").value = "";
		document.getElementById("judul_batch").value = "";
	}

	function selectFields2(id, id, nama) {
		$('#id_peserta').val(id);
		$('#nama_peserta').val(nama);
		$.facebox.close();
	}

	function ClearFields2() {
		document.getElementById("id_peserta").value = "";
		document.getElementById("nama").value = "";
	}

	
	$(function() {
		$("#deadline_tugas").datepicker({
			yearRange: "-1:+5",
			changeYear: "true",
			changeMonth: "true",
			dateFormat: "dd-mm-yy"
		});
	});	
</script>

<div class="content-header"></div>
<div class="UI_Header_Title">
	<h1><?=$this->avatar;?>Edit Penugasan</h1>
	<div class="header_nav_links"><a href="/mentor/penugasan/index">Back to Daftar Penugasan</a></div>
</div>
<div class="clear"></div>
<form id="compose" name="compose" method="post" action="" enctype="multipart/form-data">
	<div class="tabular">
		<p><label>Batch</label>
			<input readonly type="text" id="judul_batch" autocomplete="disable" name="judul_batch" style="height:30px;  width: 400px;padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;" value="<?= $this->judul_batch ?>" />
			<input type="hidden" id="id_batch" autocomplete="disable" name="id_batch" value="<?= $this->row->id_batch ?>"/>
			<input type="button" value="..." id="btnbatch" style="height:30px;" onclick="jQuery.facebox({ ajax: '/mentor/penugasan/search-batch'});">
			<input type="button" style="height:30px;" onclick="ClearFields1();" value="Clear">
			<font color="red">*</font>
		</p>
		<p id="daftar-peserta" class="daftar-user">
			<label>Nama Peserta</label>
			<input readonly type="text" id="nama_peserta" autocomplete="disable" name="nama" style="height:30px; padding: 0px; padding-left: 10px; width: 400px; border: 1px solid grey; border-radius: 2px;" value="<?= $this->nama_peserta ?>" />
			<input type="button" value="..." id="btnpeserta" style="height:30px;" onclick="jQuery.facebox({ ajax: '/mentor/penugasan/search-peserta/'});">
			<input type="hidden" id="id_peserta" autocomplete="disable" name="id_peserta" value="<?= $this->row->id_peserta ?>" />
			<input type="button" style="height:30px;" onclick="ClearFields2();" value="Clear">
			<font color="red">*</font>
		</p>
		<p>
			<label class="left" for="title">Isi Tugas</label>
			<input type="text" id="title" class="event-message" wrap="soft" name="title"  style="width: 450px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;" value="<?= $this->row->title ?>">
			<font color="red">*</font>
		</p>
		<br>
		<p>
			<label class="left" for="file_name">Contoh Tugas</label>
			<?
			if ($this->row->file_title == "" || $this->row->file_title == NULL) {
				echo '<input type="file" id="file_name" name="file_name">';
				echo '<input type="hidden" value="2" id="cek_file" name="cek_file">';
			} else {
				echo '<input type="hidden" value="1" id="cek_file" name="cek_file">';
				echo '| &nbsp; &nbsp; &nbsp; <a style="color: blue; cursor: pointer; font-size:14px;" href="https://berkas.dpr.go.id/mooc/penugasan/' . $this->row->file_title . '" > Download </a>';
				echo '&nbsp; &nbsp; &nbsp; | &nbsp; &nbsp; &nbsp; <a style="color: red; cursor: pointer; font-size:14px;" href="/mentor/penugasan/delete-files/id/' . $this->row->id . '  ">Hapus</a> &nbsp; &nbsp; &nbsp; |';
			}
			?>
		</p>
		<br>
		<p id="tanggal_awal">
		<? $deadline_tugas =  explode(" ",$this->row->deadline_tugas) ?>
  		<label>Deadline Tugas</label>
		<input type="text" id="deadline_tanggal" autocomplete="off" name="deadline_tanggal" value="<?= date('d-m-Y', strtotime($deadline_tugas[0])); ?>" style="width: 150px; height: 30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px; background-color: white;" />
		
		<input type="text" id="deadline_waktu" autocomplete="off" name="deadline_waktu" value="<?= date('H:i:s', strtotime($deadline_tugas[1])); ?>" style="width: 80px; height: 30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px; background-color: white;" />
  		<font color="red">*</font>
		</p>
		
	    <p class="savecancel"><label class="UIbutton-small"><input type="submit" value="Simpan" class="" /></label><a href="/mentor/penugasan/index" class="UIbutton-small">Batal</a></p>
	</div>
</form>
<div style="clear:both"></div>

<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>

<script>
  $(function() {
    $("#deadline_tanggal").datepicker({
      yearRange: "-1:+5",
      changeYear: true,
      changeMonth: true,
      dateFormat: "yy-mm-dd",
    });

	$('#deadline_waktu').timepicker({
      timeFormat: 'HH:mm:ss', // Format waktu yang akan ditampilkan
      interval: 30, // Interval dalam menit
      dynamic: false,
    //   dropdown: true,
    //   scrollbar: true
    });
  });

</script>