<script type="text/javascript">
    $(function() {
        $("#table_facebox")
            .tablesorter({
                theme: 'blue',
                widthFixed: true,
                widgets: ['zebra', 'filter']
            })
            .tablesorterPager({
                container: $(".pager2"),
                output: '{startRow} - {endRow} / {filteredRows} ({totalRows})',
                fixedHeight: true,
                removeRows: false,
                cssGoto: '.gotoPage'
            });
    });
</script>

<div class="content-header"></div>
<div class="UI_Header_Title">
    <h1><?= $this->avatar; ?> Pilih Nama Batch </h1>
</div>
<div class="clear"></div>
<br>

<? if (count($this->rows) > 0) { ?>
    <?= $this->pager2; ?>

    <table cellspacing="1" cellpadding="6" width="100%" class="tablesorter" id="table_facebox">
        <thead>
            <tr>
                <th align="center">Pelatihan</th>
                <th align="center">Nama Batch</th>
                <th align="center">Aksi</th>
            </tr>
        </thead>
        <tbody>
            <?
            $i = 1;
            foreach ($this->rows as $row) {
                echo '<tr>';
                foreach($this->pelatihan as $z){
                    if($z->id == $row->id_pelatihan){
                        echo '<td align="center">'. $z->nama_pelatihan .'</td>';
                        break;
                    }
                }
                echo '<td align="center">'. $row->judul_batch .'</td>';
                echo '<td align="center"><a href="javascript:selectFields1(\'' . $row->id . '\', \'' . $row->id . '\', \'' . $row->judul_batch . '\')">PILIH</a></td>';
                echo '</tr>';

                $i++;
            }
            ?>
        </tbody>
    </table>
<? } else {
    echo 'Data tidak ditemukan.';
}
?>