<section class="container-tentang mb-5 d-flex flex-column justify-content-evenly p-3" style="padding-top: 150px !important; max-width: 100vw;">
    <p class="fs-2 fw-bold text-center">Login Selain ASN</p>
    
    <form action="/loginselainasn/login" method="post">
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required>
        
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required>
        
        <input type="submit" value="Login">
    </form>
</section>
