
<script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
	integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
	crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
	integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
	integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
	crossorigin="anonymous"></script>

<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

<div class="content-header"></div>
<div class="UI_Header_Title">


	<h4><?= $this->avatar; ?>Tambah Mata Pelatihan</h4>
	<!-- <div class="header_nav_links"><a href="/admin/materi-silabus/index">Back to Daftar Mata Pelatihan</a></div> -->
	<div class="header_nav_links"><a href="javascript:history.back()">Back to Daftar Mata Pelatihan</a></div>

	<!-- <div class="header_nav_links"><a href="/admin/silabus/edit/id/<? //= $this->rows[0]['id_silabus']; ?>">Back to Daftar Mata Pelatihan</a></div> -->

	<?php
	//echo $this->rows[0]['id_silabus'];
	?>


	<? //echo var_dump($this->rows); die(); ?>
	<? //echo var_dump($this->rows); die(); ?>
</div>

<div class="clear"></div>
<form id="compose" name="compose" method="post" action="" enctype="multipart/form-data">
	<div class="row">
		<div class="col-md-6">
			<div class="form-group">
				<label for="nama_materi">Nama Mata Pelatihan</label>
				<input type="text" class="form-control" id="nama_materi" name="nama_materi" value=""
					placeholder="Masukkan Nama Mata Pelatihan" style="height: 40px; width: 450px;" required>
			</div>
			<div class="form-group">
				<label for="deskripsi_materi">Deskripsi Mata Pelatihan</label>
				<textarea class="form-control" id="deskripsi_materi" name="deskripsi_materi" rows="3"
					placeholder="Masukkan Deskripsi Mata Pelatihan"><?= $this->deskripsi_materi ?></textarea>
			</div>
			<div class="form-group">
				<label for="jumlah_jp">Jumlah JP</label>
				<input type="number" class="form-control" id="jumlah_jp" name="jumlah_jp" value="0"
					placeholder="Masukkan Jumlah JP" required min="0" max="20">
				<small class="form-text text-muted">(Min 0 JP - Max 20 JP)</small>
			</div>
			<div class="form-group">
				<label for="batas_waktu">Batas Waktu Belajar</label>
				<input type="number" class="form-control" id="batas_waktu" name="batas_waktu" value="0"
					placeholder="Menit" required min="0" max="60">
				<small class="form-text text-muted">(Min 0 menit - Max 60 menit)</small>
			</div>
			<div class="form-group">
			<label for="file_image"><i class="bi bi-file-image-fill"></i> Gambar Mata Pelatihan</label>
				<div class="custom-file">
					<input type="file" class="custom-file-input" id="file_image" name="file_image" accept="image/*">
					<label class="custom-file-label" for="file_image">Pilih Gambar</label>
				</div>
				<small class="form-text text-muted">JPG, PNG (Max. 128 MB)</small>
			</div>
			<div class="form-group">
				<label for="file_pdf"><i class="bi bi-file-pdf-fill"></i> File Mata Pelatihan</label>
				<div class="custom-file">
					<input type="file" class="custom-file-input" id="file_pdf" name="file_pdf"
						accept=".pdf,.doc,.docx,.ppt,.pptx">
					<label class="custom-file-label" for="file_pdf">Pilih File</label>
				</div>
				<small class="form-text text-muted">PDF, DOC, PPT (Max. 128 MB)</small>
			</div>
			<div class="form-group">
				<label for="file_audio"><i class="bi bi-music-note"></i> Audio Mata Pelatihan</label>
				<div class="custom-file">
					<input type="file" class="custom-file-input" id="file_audio" name="file_audio" accept="audio/*">
					<label class="custom-file-label" for="file_audio">Pilih Audio</label>
				</div>
				<small class="form-text text-muted">MP3 (Max. 128 MB)</small>
			</div>
			<div class="form-group">
				<label for="file_video"><i class="bi bi-file-play-fill"></i> Video Mata Pelatihan</label>
				<div class="custom-file">
					<input type="file" class="custom-file-input" id="file_video" name="file_video" accept="video/*">
					<label class="custom-file-label" for="file_video">Pilih Video</label>
				</div>
				<small class="form-text text-muted">MP4 (Max. 128 MB)</small>
			</div>
		</div>
		<div class="col-md-6">
			<div class="form-group">
				<label for="isi_materi">Isi Mata Pelatihan</label>
				<textarea class="form-control" id="isi_materi" name="isi_materi" rows="10"
					placeholder="Masukkan Isi Mata Pelatihan"><?= $this->isi_materi ?></textarea>
			</div>
		</div>
	</div>
	<div class="form-group">
		<button type="submit" class="btn btn-primary">Simpan</button>
		<button onclick="window.history.back();" class="btn btn-danger">Batal</button>
	</div>
</form>
<div style="clear:both"></div>


<script>
	$('#isi_materi').summernote({
		placeholder: 'Tulis Isi Mata Pelatihan Disini & Masukan Ukuran Gambar Maximal 100KB',
		tabsize: 2,
		height: 700             // set focus to editable area after initializing summernote
	});

	document.querySelectorAll('input[type="file"]').forEach(function(input) {
	input.addEventListener('change', function() {
		var fileName = this.files[0].name;
		var label = this.nextElementSibling;
		label.innerHTML = fileName;
	});
	});

</script>