<!-- <script src="<?=$this->url_statik;?>/tinymce/tinymce.min.js"></script> -->


<script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

	<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.min.js" integrity="sha512-3dZ9wIrMMij8rOH7X3kLfXAzwtcHpuYpEgQg1OA4QAob1e81H8ntUQmQm3pBudqIoySO5j0tHN4ENzA6+n2r4w==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css" integrity="sha512-t4GWSVZO1eC8BM339Xd7Uphw5s17a86tIZIj8qRxhnKub6WoyhnrxeCIMeAqBPgdZGlCcG2PrZjMc+Wr78+5Xg==" crossorigin="anonymous" referrerpolicy="no-referrer" /> -->

    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>

<!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
	integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous"> -->

<!-- bootstrap icon -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

<!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
	integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
	crossorigin="anonymous"></script> -->

<div class="content-header"></div>
<div class="UI_Header_Title">

	<h6><?=$this->avatar;?>Edit Mata Pelatihan</h6>
	<div class="header_nav_links"><a href="/admin/silabus/edit/id/<?= $this->row->id_silabus ?>"> Back to Daftar Mata Pelatihan
			</a></div>
	<? //echo var_dump($this->row->id_silabus); die(); ?>
</div>



<div class="clear"></div>
<form id="compose" name="compose" method="post" action="" enctype="multipart/form-data">
	<div class="row">
		<div class="col-md-6">
			<div class="form-group">
				<label for="nama_materi">Nama Mata Pelatihan</label>
				<input type="text" class="form-control" id="nama_materi" name="nama_materi" value="<?= $this->row->nama_materi; ?>"
					placeholder="Masukkan Nama Mata Pelatihan" style="height: 40px; width: 450px;" required>
			</div>
			<div class="form-group">
				<label for="deskripsi_materi">Deskripsi Mata Pelatihan</label>
				<textarea class="form-control" id="deskripsi_materi" name="deskripsi_materi" rows="3"
					placeholder="Masukkan Deskripsi Mata Pelatihan"><?= $this->row->deskripsi_materi ?></textarea>
			</div>
			<div class="form-group">
				<label for="jumlah_jp">Jumlah JP</label>
				<input type="number" class="form-control" id="jumlah_jp" name="jumlah_jp" value="<?= $this->row->jumlah_jp; ?>"
					placeholder="Masukkan Jumlah JP" required min="0" max="20">
				<small class="form-text text-muted">(Min 0 JP - Max 20 JP)</small>
			</div>
			<div class="form-group">
				<label for="batas_waktu">Waktu Belajar</label>
				<input type="number" class="form-control" id="batas_waktu" name="batas_waktu" value="<?= $this->row->batas_waktu; ?>"
					placeholder="Menit" required min="0" max="60">
			<small class="form-text text-muted">(Min 0 menit - Max 60 menit)</small>
			</div>
			<div class="form-group">
			<label for="file_image"><i class="bi bi-file-image-fill"></i> Gambar Mata Pelatihan</label>
			<?php 
					if ($this->row->gambar_materi_uri == '') {
						echo '<div class="custom-file">
						<input type="file" class="custom-file-input" id="file_image" name="file_image" accept="image/*">

						<label class="custom-file-label" for="file_image" id="file_image_label">Pilih Gambar</label>

					</div>
					<small class="form-text text-muted">JPG, PNG (Max. 128 MB)</small>';
					} else {
						echo '<br><img src="https://berkas.dpr.go.id/mooc/gambarmateri/' . $this->row->gambar_materi_uri . '" height="100" />';
						echo '<a href="/admin/materi-silabus/hapusfile/jenis_file/gambar/id/' . $this->row->id . '" class=" right btn btn-light"> <i class="bi bi-trash"></i> Hapus </a>';
						echo '<input type="hidden" accept="image/*" id="file_image" autocomplete="disable" name="file_image" value="'. $this->row->gambar_materi_uri .'"/>';
					}
				?>

			</div>
			<div class="form-group">
				<label for="file_pdf"><i class="bi bi-file-pdf-fill"></i> File Mata Pelatihan</label>
				<?php 
					if ($this->row->document_materi_uri == '') {
						echo '<div class="custom-file">
						<input type="file" class="custom-file" id="file_pdf" name="file_pdf"
							accept=".pdf,.doc,.docx,.ppt,.pptx">
						<label class="custom-file-label" for="file_pdf">Pilih File</label>
					</div>
					<small class="form-text text-muted">PDF, DOC, PPT (Max. 128 MB)</small>';
					} else {
						echo '<br><a href="https://berkas.dpr.go.id/mooc/filemateri/'.$this->row->document_materi_uri.'" target="_blank"> '.$this->row->document_materi_uri.'
					</a>';
						echo '<a href="/admin/materi-silabus/hapusfile/jenis_file/document/id/' . $this->row->id . '" class=" right btn btn-light"> <i class="bi bi-trash"></i> Hapus </a>';
						echo '<input type="hidden" id="file_pdf" autocomplete="disable" name="file_pdf" value="'.$this->row->document_materi_uri.'"/>';
					}
				?>
				
			</div>
			<div class="form-group">
				<label for="file_audio"><i class="bi bi-music-note"></i> Audio Mata Pelatihan</label>
				<?php 
					if ($this->row->audio_materi_uri == '') {
						echo '<div class="custom-file">
						<input type="file" class="custom-file-input" id="file_audio" name="file_audio" accept="audio/*">
						<label class="custom-file-label" for="file_audio">Pilih Audio</label>
					</div>
					<small class="form-text text-muted">MP3 (Max. 128 MB)</small>';
					} else {
						echo '<br><audio src="https://berkas.dpr.go.id/mooc/filemateri/' . $this->row->audio_materi_uri . '" controls></audio>';
						echo '<a href="/admin/materi-silabus/hapusfile/jenis_file/audio/id/' . $this->row->id . '" class=" right btn btn-light"> <i class="bi bi-trash"></i> Hapus </a>';
						echo '<input type="hidden" accept="audio/*" id="file_audio" autocomplete="disable" name="file_audio" value="'.$this->row->audio_materi_uri.'"/>';
					}
				?>
				

			</div>
			<div class="form-group">
				<label for="file_video"><i class="bi bi-file-play-fill"></i> Video Mata Pelatihan</label>
				<?php 
					if ($this->row->video_materi_uri == '') {
						echo '				<div class="custom-file">
						<input type="file" class="custom-file-input" id="file_video" name="file_video" accept="video/*">
						<label class="custom-file-label" for="file_video">Pilih Video</label>
					</div>
					<small class="form-text text-muted">MP4 (Max. 128 MB)</small>';
					} else {
						echo '<br><video  height="100" controls>
						<source src="https://berkas.dpr.go.id/mooc/filemateri/'. $this->row->video_materi_uri .'" type="video/mp4">
						Your browser does not support the video tag.
					</video>';
						echo '<a href="/admin/materi-silabus/hapusfile/jenis_file/video/id/' . $this->row->id . ' " class=" right btn btn-light"> <i class="bi bi-trash"></i> Hapus </a>';
						echo '<input type="hidden" accept="video/*" id="file_video" autocomplete="disable" name="file_video" value="'.$this->row->video_materi_uri.'"/>';
					}
				?>

			</div>
		</div>
		<div class="col-md-6">
			<div class="form-group">
				<label for="isi_materi">Isi Mata Pelatihan</label>
				<textarea class="form-control" id="isi_materi" name="isi_materi" rows="10"
					placeholder="Masukkan Isi Mata Pelatihan"><?= $this->row->isi_materi ?></textarea>
			</div>
		</div>
	</div>
	<div class="form-group">
		<button type="submit" class="btn btn-primary">Simpan</button>
		<button onclick="window.history.back();" class="btn btn-danger">Batal</button>
	</div>
</form>

<div style="clear:both"></div>
	<script>
      $('#isi_materi').summernote({
        placeholder: 'Tulis Isi Mata Pelatihan Disini & Masukan Ukuran Gambar Maximal 100KB',
        tabsize: 2,
        height: 700
      });


	document.querySelectorAll('input[type="file"]').forEach(function(input) {
	input.addEventListener('change', function() {
		var fileName = this.files[0].name;
		var label = this.nextElementSibling;
		label.innerHTML = fileName;
	});
	});



    </script>