<script type="text/javascript">
	$(document).ready(function() {
		$("#compose").validate();
	})

	function selectFields1(id, id, username) {
		$('#id_user').val(id);
		$('#username').val(username);
		$.facebox.close();
	}

	function ClearFields1() {
		document.getElementById("id_user").value = "";
		document.getElementById("username").value = "";
	}

    $(function() {
		$("#tanggal_lahir").datepicker({
			yearRange: "-100:+0",
			changeYear: "true",
			changeMonth: "true",
			dateFormat: "dd-mm-yy"
		});
	});
</script>

<div class="content-header"></div>
<div class="UI_Header_Title">
	<h1><?= $this->avatar; ?>Biodata Mentor</h1>
</div>
<div class="clear"></div>
<form id="compose" name="compose" method="post" action="" enctype="multipart/form-data">
	<div class="tabular">
		<p>
			<label class="left" for="nama_mentor">Nama Mentor</label>
			<input type="text" id="nama_mentor" class="event-message" wrap="soft" name="nama_mentor" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;" value="<?= $this->row->nama_mentor; ?>">
		</p>
		<p>
			<label class="left" for="identitas_mentor">NIP/NIK</label>
			<input type="number" id="identitas_mentor" class="event-message" wrap="soft" name="identitas_mentor" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;" value="<?= $this->row->identitas_mentor ?>">
		</p>
		<p>
			<label class="left" for="instansi">Asal Instansi</label>
			<input type="text" id="instansi" class="event-message" wrap="soft" name="instansi" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;" value="<?= $this->row->instansi; ?>">
		</p>
		<p>
			<label class="left" for="email">Email</label>
			<input type="email" id="email" class="event-message" wrap="soft" name="email" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;" value="<?= $this->row->email; ?>">
		</p>
		<p>
			<label class="left" for="no_telp">No. Telepon</label>
			<input type="number" id="no_telp" class="event-message" wrap="soft" name="no_telp" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;" value="<?= $this->row->no_telp ?>">
		</p>
		<p>
			<label class="left" for="fotomentor_uri">Foto Mentor</label> 
			<?
			if ($this->row->fotomentor_uri != '') {
				echo '<img src="https://berkas.dpr.go.id/mooc/fotomentor/' . $this->row->fotomentor_uri . '" height="100" />';
				echo '<a href="/mentor/profile/delete-files/id/' . $this->row->id . '  ">Hapus</a>';
				echo '<input type="hidden" id="file_name" autocomplete="disable" name="file_name" value="'.$this->row->fotomentor_uri.'"/>';
			} else {
				echo '<input type="file" accept="image/*" id="file_name" autocomplete="disable" name="file_name"/>';
			}
			?>
		</p>

		<p class="savecancel"><label class="UIbutton-small"><input type="submit" value="Simpan" class="" /></label><a href="/mentor" class="UIbutton-small">Batal</a></p>
	</div>
</form>
<div style="clear:both"></div>