<style>
.column { float: left; padding-bottom: 100px; }
.portlet { margin: 0 1em 1em 0; }
.portlet-header { margin: 0.3em; padding-bottom: 4px; padding-left: 0.2em; }
.portlet-header .ui-icon { float: right; }
.portlet-content { padding: 0.4em; }
.ui-sortable-placeholder { border: 1px dotted black; visibility: visible !important; height: 50px !important; }
.ui-sortable-placeholder * { visibility: hidden; }
</style>

<div class="column" style="width: 60%;">
	
	<div class="portlet">
		<div class="portlet-header">User Manual</div>
		<div class="portlet-content">
			<table width="100%">
				<tr>
					<td align="center"><a href="<?=$this->url_berkas;?>/files/User_Manual_MOOC.pdf" target="_blank"><img src="<?=$this->url_statik;?>/images/admin/mantel/pdf_icon.png"><br>Panduan Penggunaan Aplikasi Prasmanan Learning MOOC</a></td>
				</tr>
			</table>
		</div>
	</div>

</div>

<div class="column" style="width: 40%;">
	
	<div class="portlet">
		<div class="portlet-header">Notifikasi</div>
		<div class="portlet-content">
			
		</div>
	</div>

</div>

<script type="text/javascript">
	$(function() {
		$( ".column" ).sortable({
			connectWith: ".column"
		});

		$( ".portlet" ).addClass( "ui-widget ui-widget-content ui-helper-clearfix ui-corner-all" )
			.find( ".portlet-header" )
				.addClass( "ui-widget-header ui-corner-all" )
				.prepend( "<span class='ui-icon ui-icon-minusthick'></span>")
				.end()
			.find( ".portlet-content" );

		$( ".portlet-header .ui-icon" ).click(function() {
			$( this ).toggleClass( "ui-icon-minusthick" ).toggleClass( "ui-icon-plusthick" );
			$( this ).parents( ".portlet:first" ).find( ".portlet-content" ).toggle();
		});

		$( ".column" ).disableSelection();
	});
</script>