<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Prasmanan Learning</title>
  <!-- bootstrap -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

  <!-- bootstrap icon -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

  <!-- CSS -->
  <link rel="stylesheet" href="https://berkas.dpr.go.id/mooc/assets/css/darkmode.css">
  <link rel="stylesheet" href="https://berkas.dpr.go.id/mooc/assets/css/layout-default.css">
</head>

<?php
  $auth = Zend_Auth::getInstance()->getIdentity();
  $peran = $auth->peran;
  $username = $auth->nama;
?>

<body>
  <!-- navbar -->
  <?
  if (!($auth->id)) {
    // navbar auth
    echo'<nav class="navbar navbar-expand-lg background-content fixed-top" style="max-width: 100vw; background-color: #E5E7E9; box-shadow: 2.0px 4.0px 4.0px hsl(0deg 0% 0% / 0.38); z-index: 100">
            <div class="container-fluid background-content" style="background-color: #E5E7E9">
              <a href="/default/index/" class="mooc navbar-brand text-center mx-3" style="width: 200px;" href="/home/home/index">
                <img src="https://berkas.dpr.go.id/mooc/assets/images/mooc.png" alt="MOOC">
              </a>
              <br><br><br>
                
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
                
              <div class="collapse navbar-collapse" style="max-width: 100vw" id="navbarSupportedContent">
                      <ul class="navbar-nav mb-lg-0 d-flex justify-content-between me-5 my-navbar">
                        <form class="nav-item d-flex search-form ms-3" style="min-width: 20vw; height: 100%" role="search">
                          <div class="box" style="width: 3em;">
                            <form name="search">
                              <input type="text" class="input" name="txt" placeholder="Cari disini...">
                              <i class="bi bi-search" style="font-size: 25px; left: 0.7em;"></i>
                            </form>
                          </div>
                        </form>

                        <div class="dropdown-animation"> 
                          <a href="/peserta/index" class="btnHaveLogin text-decoration-none text-black">COURSES</a>
                        </div>

                        <div class="dropdown-animation div-text"> EXPLORE
                          <ul class="background-content dropdown-animation-menu">
                            <li><a href="#">action 1</a></li>
                            <li><a href="#">action 2</a></li>
                            <li><a href="#">action 3</a></li>
                            <li><a href="#">action 4</a></li>
                          </ul>
                        </div>
                
                        <div class="dropdown-animation div-text"> PROGRAM
                          <ul class="background-content dropdown-animation-menu">
                            <li><a href="#">action 1</a></li>
                            <li><a href="#">action 2</a></li>
                            <li><a href="#">action 3</a></li>
                            <li><a href="#">action 4</a></li>
                          </ul>
                        </div>
                
                        <div class="dropdown-animation div-text"> PARTNERSHIP
                          <ul class="background-content dropdown-animation-menu">
                            <li><a href="#">action 1</a></li>
                            <li><a href="#">action 2</a></li>
                            <li><a href="#">action 3</a></li>
                            <li><a href="#">action 4</a></li>
                          </ul>
                        </div>
                      </ul>
                      <br> 
            
                      <div class="nav-item d-flex flex-column container-logreg" style="width: 100%;">
                        <li class="nav-item text-end mb-2 list-unstyled" style="width: 100%;">
                          <a href="https://belajar.dpr.go.id/admin" class="btn fw-bold" style="width: 7em; border: 2px solid #D4A216; color: #D4A216;">Login</a>
                        </li>
                
                        <li class="nav-item text-end list-unstyled" style="width: 100%;">
                          <button type="button" class="btn text-light fw-bold" style="width: 7em; background-color: #D4A216" type="submit" data-bs-toggle="modal" data-bs-target="#register">Register</button>
                        </li>
                      </div>
                
              </div>
            </div>
        </nav>';
    // end navbar auth
  } else {
    // navbar profile
  
    $this->PesertaService = new PesertaService();
    $peserta = $this->PesertaService->getData($auth->id_peserta);

    echo'<nav class="navbar navbar-expand-lg background-content fixed-top" style="max-width: 100vw; background-color: #E5E7E9; box-shadow: 2.0px 4.0px 4.0px hsl(0deg 0% 0% / 0.38); z-index: 100">
          <div class="container-fluid background-content" style="background-color: #E5E7E9">
            <a href="/default/index/" class="mooc navbar-brand text-center mx-3" style="width: 200px;">
              <img src="https://berkas.dpr.go.id/mooc/assets/images/mooc.png" alt="MOOC">
            </a>
            <br><br><br>
              
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
              
            <div class="collapse navbar-collapse" style="max-width: 100vw" id="navbarSupportedContent">
              <ul class="navbar-nav mb-lg-0 d-flex justify-content-between me-5 my-navbar">
                <form class="nav-item d-flex search-form ms-3" style="min-width: 20vw; height: 100%" role="search">
                  <div class="box" style="width: 3em;">
                    <form name="search">
                      <input type="text" class="input" name="txt" placeholder="Cari disini...">
                      <i class="bi bi-search" style="font-size: 25px; left: 0.7em;"></i>
                    </form>
                  </div>
                </form>

                <div class="dropdown-animation"> 
                  <a href="/peserta/index" class="text-decoration-none text-black">COURSES</a>
                </div>
                       
                <div class="dropdown-animation div-text"> EXPLORE
                  <ul class="background-content dropdown-animation-menu">
                    <li><a href="#">action 1</a></li>
                    <li><a href="#">action 2</a></li>
                    <li><a href="#">action 3</a></li>
                    <li><a href="#">action 4</a></li>
                  </ul>
                </div>
              
                <div class="dropdown-animation div-text"> PROGRAM
                  <ul class="background-content dropdown-animation-menu">
                    <li><a href="#">action 1</a></li>
                    <li><a href="#">action 2</a></li>
                    <li><a href="#">action 3</a></li>
                    <li><a href="#">action 4</a></li>
                  </ul>
                </div>
              
                <div class="dropdown-animation div-text"> PARTNERSHIP
                  <ul class="background-content dropdown-animation-menu">
                    <li><a href="#">action 1</a></li>
                    <li><a href="#">action 2</a></li>
                    <li><a href="#">action 3</a></li>
                    <li><a href="#">action 4</a></li>
                  </ul>
                </div>
              </ul>

              <div class="nav-item d-flex flex-row align-items-center justify-content-end pe-5" style="width: 100%; height: 100%"> 
                <li class="btn-group list-unstyled d-flex justify-content-center align-items-center position-relative">
                  <button type="button" class="background-content btn d-flex justify-content-center align-items-center rounded-circle" style="width: 40px; height: 40px; background-color: #E5E7E9; box-shadow: 2.0px 4.0px 4.0px hsl(0deg 0% 0% / 0.38);" data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="https://berkas.dpr.go.id/mooc/assets/images/username-orange.png" alt="" class="rounded-circle" style="width: 30px; height: 30px;">
                  </button>
                          
                  <ul class="dropdown-menu position-absolute background-content" style="left: -170px !important; z-index: 99999999999; margin-top: 14px; padding: 10px; min-width: 300px;">
                    <li class="text-center"> <p class="fs-4">' . $peserta->nama . '</p></li>
                    <li class="text-center"><a class="dropdown-item btn border" href="/peserta/profile/index/id/' . $auth->id_peserta . '">View Profile</a></li>
                    <div class="dropdown-divider"></div>
                    <!-- <li><a class="dropdown-item" href="#"><i class="bi bi-gear"></i> Setting</a></li> -->
                    <div class="dropdown-divider"></div>
                    <li><a class="dropdown-item" href="/login/logout"><i class="bi bi-box-arrow-right"></i> Logout</a></li>
                  </ul>
                </li>
                    
                <li class="list-unstyled d-flex justify-content-center align-items-center" style="width: 50px;">
                  <button type="button" class="background-content btn position-relative d-flex justify-content-center align-items-center rounded-circle" style="width: 40px; height: 40px; background-color: #E5E7E9;">
                    <img src="https://berkas.dpr.go.id/mooc/assets/images/bell.png" alt="" class="rounded-circle position-absolute" style="width: 25px; height: 25px;">
                    <span class="position-absolute m-0 bg-danger rounded-circle" style="width: 10px; height: 10px; right: 3px; top: 3px;"></span>
                  </button>
                </li>
              </div>

            </div>
          </div>
        </nav>';
  }
  // end profile
  ?>
  <!-- end navbar -->

  <!-- dark & light mode -->
  <div class="container-dark-mode position-fixed" style="top: 100px; right: 20px; z-index: 99999999;">
    <div class="sun sun-logo" style="fill: #D4A216;">
      <svg viewBox="0 0 512 512" width="40" title="sun">
        <path d="M256 160c-52.9 0-96 43.1-96 96s43.1 96 96 96 96-43.1 96-96-43.1-96-96-96zm246.4 80.5l-94.7-47.3 33.5-100.4c4.5-13.6-8.4-26.5-21.9-21.9l-100.4 33.5-47.4-94.8c-6.4-12.8-24.6-12.8-31 0l-47.3 94.7L92.7 70.8c-13.6-4.5-26.5 8.4-21.9 21.9l33.5 100.4-94.7 47.4c-12.8 6.4-12.8 24.6 0 31l94.7 47.3-33.5 100.5c-4.5 13.6 8.4 26.5 21.9 21.9l100.4-33.5 47.3 94.7c6.4 12.8 24.6 12.8 31 0l47.3-94.7 100.4 33.5c13.6 4.5 26.5-8.4 21.9-21.9l-33.5-100.4 94.7-47.3c13-6.5 13-24.7.2-31.1zm-155.9 106c-49.9 49.9-131.1 49.9-181 0-49.9-49.9-49.9-131.1 0-181 49.9-49.9 131.1-49.9 181 0 49.9 49.9 49.9 131.1 0 181z" />
      </svg>
    </div>
    <div class="moon moon-logo">
      <svg viewBox="0 0 512 512" width="40" title="moon">
        <path d="M283.211 512c78.962 0 151.079-35.925 198.857-94.792 7.068-8.708-.639-21.43-11.562-19.35-124.203 23.654-238.262-71.576-238.262-196.954 0-72.222 38.662-138.635 101.498-174.394 9.686-5.512 7.25-20.197-3.756-22.23A258.156 258.156 0 0 0 283.211 0c-141.309 0-256 114.511-256 256 0 141.309 114.511 256 256 256z" />
      </svg>
    </div>
  </div>
  <!-- end dark & light mode -->

  <!-- modal login -->
  <div class="modal fade" id="login" tabindex="-1" aria-labelledby="loginLabel" aria-hidden="true">
    <div class="modal-dialog rounded-3 border border-0">
      <div class="modal-content p-5">
        <div class="m-auto">
          <h3 class="modal-title fs-4 fw-bold text-center" id="loginLabel">Daftar menggunakan akun Portal</h3>
        </div>
        <div class="modal-body">
          
	        <form id="compose" name="compose" method="post" action="" enctype="multipart/form-data">
            <div class="mb-3 position-relative d-flex align-items-center">
              <img class="position-absolute me-3" src="https://berkas.dpr.go.id/mooc/assets/images/username.png" alt=""
                style="width: 20px; height: 20px; left: 10px;">
              <input type="text" class="form-control px-5 input100" name="pengguna" placeholder="Pengguna"
                id="pengguna">
            </div>
            <div class="mb-3 position-relative d-flex align-items-center justify-content-between">
              <img class="position-absolute me-3" src="https://berkas.dpr.go.id/mooc/assets/images/password.png" alt=""
                style="width: 20px; height: 20px; left: 10px;">
              <input type="password" class="form-control px-5 input100" name="sandi" placeholder="Password" id="sandi">
              <img class="position-absolute me-3" src="https://berkas.dpr.go.id/mooc/assets/images/hide-password.png"
                alt="" style="width: 20px; height: 15px; right: 5px; cursor: pointer;"
                onclick="hideShowPasswordLogin()">
            </div>
            <div class="mb-1 p-1 text-center rounded-3 mt-3" style="max-width: 100vw; background-color: #D4A216">
              <button type="submit" class="btn text-white fw-bold" style="background-color: #D4A216;">Daftar</button>
            </div>
            <!-- <p class="text-secondary text-center fw-bold" style="letter-spacing: 0.8px">Lupa password? <a
                class="fw-bold" style="letter-spacing: 0.8px; color: #D4A216;" href=""> Ubah password</a></p> -->
          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- end modal login -->

  <!-- modal register -->
  <div class="modal fade" id="register" tabindex="-1" aria-labelledby="registerLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content p-5">
        <div class="m-auto">
          <h3 class="modal-title fs-4 fw-bold text-center" id="registerLabel">Register</h3>
        </div>
        <div class="modal-body">
          <form>
            <div class="mb-3 position-relative d-flex align-items-center">
              <img class="position-absolute me-3" src="https://berkas.dpr.go.id/mooc/assets/images/username.png" alt=""
                style="width: 20px; height: 20px; left: 10px;">
              <input type="text" class="form-control px-5" id="username" name="username" placeholder="Pengguna">
            </div>
            <div class="mb-3 position-relative d-flex align-items-center">
              <img class="position-absolute me-3" src="https://berkas.dpr.go.id/mooc/assets/images/email.png" alt=""
                style="width: 20pxx; height: 20px; left: 10px;">
              <input type="email" class="form-control px-5" id="email" name="email" placeholder="Email">
            </div>
            <div class="mb-3 position-relative d-flex align-items-center">
              <img class="position-absolute me-3" src="https://berkas.dpr.go.id/mooc/assets/images/phone.png" alt=""
                style="width: 20px; height: 20px; left: 10px;">
              <input type="text" class="form-control px-5" id="telepon" name="telepon" placeholder="Telepon">
            </div>
            <div class="mb-3 position-relative d-flex align-items-center justify-content-between">
              <img class="position-absolute me-3" src="https://berkas.dpr.go.id/mooc/assets/images/password.png" alt=""
                style="width: 20px; height: 20px; left: 10px;">
              <input type="password" class="form-control px-5" id="register_password" name="password"
                placeholder="Password">
              <img class="position-absolute me-3" src="https://berkas.dpr.go.id/mooc/assets/images/hide-password.png"
                alt="" style="width: 20px; height: 15px; right: 5px; cursor: pointer;"
                onclick="hideShowPasswordRegister()">
            </div>
            <div class="mb-3 position-relative d-flex align-items-center justify-content-between">
              <img class="position-absolute me-3" src="https://berkas.dpr.go.id/mooc/assets/images/password.png" alt=""
                style="width: 20px; height: 20px; left: 10px;">
              <input type="password" class="form-control px-5" id="confirm_password" name="cpassword"
                placeholder="Ketik ulang password">
              <img class="position-absolute me-3" src="https://berkas.dpr.go.id/mooc/assets/images/hide-password.png"
                alt="" style="width: 20px; height: 15px; right: 5px; cursor: pointer;"
                onclick="hideShowPasswordRegisterConfirm()">
            </div>
            <div class="mb-1 p-1 text-center rounded-3" style="max-width: 100vw; background-color: #D4A216;">
              <button class="btn text-white fw-bold" style="background-color: #D4A216;">Register</button>
            </div>
            <p class="text-secondary text-center fw-bold" style="letter-spacing: 0.8px">Punya akun Portal? <a
                class="fw-bold" style="letter-spacing: 0.8px; color: #D4A216;" href="" data-bs-toggle="modal"
                data-bs-target="#login"> Daftar disini</a></p>
          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- end modal register -->

  <!-- -------------------------------------------------------------------------------------------------------------------- -->
  <?= $this->layout()->content; ?>

  <!-- </footer> -->
  <footer class=" px-3 py-4" style="background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(240,152,25,1) 0%, rgba(226,211,88,1) 100%);">
    <div class="container">
      <div class="row">
        <div class="col-md-4 text-center">
          <img src="https://berkas.dpr.go.id/mooc/assets/images/logo_setjendpr.png" alt="" class="m-0"
            style="height: 15vh;">
          <h5 class="m-10" style="font-size: 1em;">Sekretariat Jenderal DPR RI</h5>
        </div>
        <div class="col-md-4">
          <h5 class="fs-5">Prasmanan Learning Center</h5>
          <ul class="list-unstyled">
            <li><a href="#" class="text-decoration-none text-dark" style="font-size: 0.8em;">Tentang Kami</a></li>
            <li><a href="#" class="text-decoration-none text-dark" style="font-size: 0.8em;">Cara Belajar</a></li>
            <li><a href="#" class="text-decoration-none text-dark" style="font-size: 0.8em;">Pertanyaan</a></li>
          </ul>
        </div>
        <div class="col-md-4">
          <h5 class="fs-5">Kontak</h5>
          <div class="social-feed">
            <div class="feed-line">
              <i class="bi bi-phone" style="font-size: 0.8em;"></i> Telp: (021) 571 56100, (021) 571 56069
            </div>
            <div class="feed-line">
              <i class="bi bi-envelope" style="font-size: 0.8em;"></i> pusdiklat@dpr.go.id
            </div>
            <div class="feed-line">
              <i class="bi bi-geo-alt-fill" style="font-size: 0.8em;"></i> Jalan Jenderal Gatot Subroto, Senayan,<br>
              &nbsp &nbsp  Jakarta 10270
            </div>
            
          </div>
        </div>
      </div>
      <hr class="my-4" style="border-color: black;">
      <div class="text-center">
        <p class="m-0">&copy; Made with <i class="bi bi-heart-fill text-danger"></i> by Pusat Teknologi Informasi. All
          Rights Reserved</p>
      </div>
    </div>
  </footer>
  <!-- end footer -->

  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

  <script>
    // dark mode
    // Mengecek apakah terdapat nilai modeGelap di local storage saat halaman dimuat
    document.addEventListener("DOMContentLoaded", function() {
      let darkMode = localStorage.getItem("darkMode");
      if (darkMode === "true") {
        // Jika darkMode bernilai "true", terapkan dark mode pada elemen yang diperlukan
        document.querySelector(".sun-logo").classList.add("animate-sun");
        document.querySelector(".moon-logo").classList.add("animate-moon");
        document.querySelector("body").classList.add("dark");
        toggleTextColor();
      }
    });

    document.querySelector(".container-dark-mode").addEventListener("click", function() {
      // Toggle class animate-sun, animate-moon, dan dark pada elemen yang diperlukan
      document.querySelector(".sun-logo").classList.toggle("animate-sun");
      document.querySelector(".moon-logo").classList.toggle("animate-moon");
      document.querySelector("body").classList.toggle("dark");
      toggleTextColor();
      // Mengecek apakah elemen body memiliki class dark setelah perubahan
      let isDarkMode = document.querySelector("body").classList.contains("dark");
      // Menyimpan status mode gelap ke dalam local storage
      localStorage.setItem("darkMode", isDarkMode);
    });

    function toggleTextColor() {
      let tagP = document.getElementsByTagName("p");
      for (let i = 0; i < tagP.length; i++) {
        tagP[i].classList.toggle("white-text");
      }

      let tagA = document.getElementsByTagName("a");
      for (let i = 0; i < tagA.length; i++) {
        tagA[i].classList.toggle("white-text");
      }

      let textDiv = document.querySelectorAll(".div-text");
      for (let i = 0; i < textDiv.length; i++) {
        textDiv[i].classList.toggle("white-text");
      }

      let backgroundContent = document.querySelectorAll(".background-content");
      for (let i = 0; i < backgroundContent.length; i++) {
        backgroundContent[i].classList.toggle("background-dark");
      }
    }
    // end dark mode

    // sweet alert
    let btnHaveLogin = document.querySelector(".btnHaveLogin")
    btnHaveLogin.addEventListener("click", () => {
      Swal.fire({
        icon: 'warning',
        title: 'Warning',
        html: 'Anda belum login, silahkan login terlebih dahulu',
        confirmButtonColor: '#4CAF50',
        customClass: {
          popup: 'my-custom-popup-class',
          title: 'my-custom-title-class',
          content: 'my-custom-content-class',
          confirmButton: 'confirm-button-class'
        }
      });
    })
    // end sweet alert
  </script>
</body>
</html>