<script id="js">
$(function(){
	$("table")
		.tablesorter({theme: 'blue', widthFixed: true, widgets: ['zebra', 'filter']})
		.tablesorterPager({container: $(".pager"), 
							output: '{startRow} - {endRow} / {filteredRows} ({totalRows})', 
							fixedHeight: true, 
							removeRows: false, 
							cssGoto: '.gotoPage' });
});
</script>

<div class="content-header">

</div>
	<!-- <div class="UI_Header_Title">
		<h1><?=$this->avatar;?> Daftar Pelatihan</h1>
		<div class="header_nav_links"><span class="right context_menu"><a href="/pengajar/pelatihan/add" class="UIlink-button small right">Tambah pelatihan</a></span>
		</div>
	</div> -->
<div class="clear">

</div>
<br>
<!-- <?php  $user = Zend_Auth::getInstance()->getIdentity(); var_dump($user->id_pengajar); ?> -->


<? if (count($this->rows) > 0) { ?>
	<?=$this->pager;?>

	<table class="tablesorter">
		 <thead>
			 <tr>
				<th>No.</th>
				<th>Nama pelatihan</th>
				<th>Deskripsi</th>
				<th>Tipe</th>
				<th>Sampul</th>
				<th>Aksi</th>
			</tr>
		</thead>
		<tbody>
			<?php
			$index = 1;
			
			foreach($this->rows as $row) {

				echo '<tr>';
				echo '<td align="center">'. $index++ .'.</td>';
				echo '<td>'. $row->nama_pelatihan .'</td>';
				echo '<td>'. $row->deskripsi .'</td>';
				echo '<td>'. $row->tipe_pelatihan .'</td>';
				echo '<td align="center">'. ($row->sampul_pelatihan == '' ? '-' : '<img src="https://berkas.dpr.go.id/mooc/thumbkelas/'.$row->sampul_pelatihan.'" width="150px">') .' </td>';
				echo '<td align="center"><a href="/pengajar/pelatihan/edit/id/'. $row->id .'">EDIT</a>';
				// if ($this->getRole() == 'admin' || $this->getRole() == 'super') {
				// 	echo '&nbsp;|&nbsp;<a href="/pengajar/pelatihan/delete/id/'. $row->id .'" onclick="return confirmDelete();">DELETE</a>';
				// }
				echo '</td>';
				echo '</tr>';
			}
			?>
		</tbody>
	</table>
<? } else {
	echo 'Data tidak ditemukan.';
}
?>