<section class="container-tentang mb-5 d-flex flex-column justify-content-evenly p-3"
    style="padding-top: 150px !important; max-width: 100vw;">
    <p class="fs-2 fw-bold text-center">FAQ</p>
    <p class="fs-5 fw-bold " style="margin-left: 50px;">Apa itu belajar.dpr.go.id?</p>

    <p class="px-5" style="text-align: justify;">Merupakan aplikasi yang digunakan PUSBANGKOM dalam menunjang proses
        pelatihan ASN di
        lingkungan DPR RI sebagai platform kolaboratif antara pengajar dan pembelajar. Aplikasi ini
        menyediakan konsep dimana pembelajar dapat mengikuti pelatihan kapan saja selama jangka
        waktu yang telah ditentukan. Dengan konsep (prasmanan), pembelajar menjadi lebih mudah
        dalam mengikuti pelatihan untuk mencapai 20 JP dalam kurun waktu 1 tahun.</p>
    <p class="fs-5 fw-bold " style="margin-left: 50px;">Siapa yang dapat menggunakan aplikasi ini?</p>
    <p class="px-5" style="text-align: justify;">Aplikasi ini dapat digunakan oleh ASN di lingkungan DPR RI dan selain
        ASN di lingkungan DPR RI</p>
    <p class="fs-5 fw-bold " style="margin-left: 50px;">Bagaimana persyaratan pengajuan pembuatan akun?</p>
    <p class="px-5" style="text-align: justify;">Terdapat 2 jenis akun untuk menggunakan aplikasi. Jika anda ASN di
        lingkungan DPR RI, anda
        dapat masuk menggunakan akun SSO DPR RI. Namun semisal anda bukan ASN di lingkungan DPR
        RI, anda dapat mendaftar di halaman <a href="https://belajar.dpr.go.id/"
            target="_blank">https://belajar.dpr.go.id/</a> lalu pilih menu daftar dan
        masukkan identitas pribadi anda.</p>
    <p class="fs-5 fw-bold " style="margin-left: 50px;">Bagaimana jika mengalami kendala dalam menggunakan aplikasi?</p>
    <p class="px-5" style="text-align: justify;">Jika anda mengalami kendala dalam penggunaan aplikasi, anda dapat
        membaca buku panduan
        yang berada di bagian menu panduan. Namun jika anda mengalami kendala atau bantuan lainnya
        pada aplikasi, anda dapat mengajukan pengaduan ke bagian helpdesk yang berada pada website
        <a href="https://stela.dpr.go.id/" target="_blank">https://stela.dpr.go.id/</a>
    </p>
</section>