<script type="text/javascript">
	$(document).ready(function() {
		$("#compose").validate();
	});
	$(function() {
		$("#tgl_awal").datepicker({
			yearRange: "-1:+0",
			changeYear: "true",
			changeMonth: "true",
			dateFormat: "dd-mm-yy"
		});
		$("#tgl_akhir").datepicker({
			yearRange: "-1:+0",
			changeYear: "true",
			changeMonth: "true",
			dateFormat: "dd-mm-yy"
		});
	});
</script>
<?php
	
	// var_dump($this->id_mentor[3]);
	// exit;
?>
<script id="js">
$(function(){
	$("table")
		.tablesorter({theme: 'blue', widthFixed: true, widgets: ['zebra', 'filter']})
		.tablesorterPager({container: $(".pager"), 
			output: '{startRow} - {endRow} / {filteredRows} ({totalRows})', 
			fixedHeight: true, 
			removeRows: false, 
			cssGoto: '.gotoPage' });
});
</script>

<script>
	function formatDate(date) {
		var day = date.getDate();
		var month = date.getMonth() + 1;
		var year = date.getFullYear();
		return (day < 10 ? '0' : '') + day + '-' + (month < 10 ? '0' : '') + month + '-' + year;
	}

	function selectFields1(id, id, nama_pelatihan, tipe_pelatihan) {
		$('#id_pelatihan').val(id);
		$('#nama_pelatihan').val(nama_pelatihan);
		$('#tipe_pelatihan').val(tipe_pelatihan);
		
		var today = new Date();
		var nextYear = new Date();
		nextYear.setFullYear(nextYear.getFullYear() + 1);

		var formattedToday = formatDate(today);
		var formattedNextYear = formatDate(nextYear);

		if(tipe_pelatihan == 'nonclassical'){
			$('#kuota_peserta').attr('disabled', true).attr('readonly', true).val('');
			$('#tgl_awal').attr('disabled', true).attr('readonly', true).val(formattedToday);
			$('#tgl_akhir').attr('disabled', true).attr('readonly', true).val(formattedNextYear);
		} else {
			$('#kuota_peserta').attr('disabled', false).attr('readonly', false);
			$('#tgl_awal').attr('disabled', false).attr('readonly', false);
			$('#tgl_akhir').attr('disabled', false).attr('readonly', false);
	    }
	
		$.facebox.close();
	}

	function ClearFields1() {
		document.getElementById("id_pelatihan").value = "";
		// document.getElementById("nit_tsp").value = "";
		document.getElementById("nama_pelatihan").value = "";
	}

	function selectFields2(id, id, nama_coach) {
		$('#id_coach').val(id);
		// $('#nit_tsp').val(id);
		$('#nama_coach').val(nama_coach);
		$.facebox.close();
	}

	function ClearFields2() {
		document.getElementById("id_coach").value = "";
		// document.getElementById("nit_tsp").value = "";
		document.getElementById("nama_coach").value = "";
	}
	
</script>

<script src="<?= $this->url_statik; ?>/js/tinymce/tinymce.min.js"></script>


<div class="content-header"></div>
<div class="UI_Header_Title">
	<h1><?=$this->avatar;?>Edit Batch</h1>
	<div class="header_nav_links"><a href="/admin/batch/index">Back to Daftar Batch</a></div>
</div>
<div class="clear"></div>
<form id="compose" name="compose" method="post" action="" enctype="multipart/form-data">
	<div class="tabular">
		<p>
			<label class="left" for="judul_batch">Judul Batch</label>
			<input id="judul_batch" class="event-message" wrap="soft" name="judul_batch" value="<?= $this->row->judul_batch ?>" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px;">
		</p>

		<p><label>Nama Pelatihan</label>
			<input readonly class="required" type="text" id="nama_pelatihan" autocomplete="disable" name="nama_pelatihan" style="height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px; background-color: white;" value="<?= $this->nama_pelatihan; ?>"/>
			<input type="hidden" id="tipe_pelatihan" readonly autocomplete="disable" name="tipe_pelatihan" />
			<input class="required" type="hidden" id="id_pelatihan" autocomplete="disable" name="id_pelatihan" value="<?= $this->id_pelatihan; ?>" />
			<input type="button" value="..." id="btnpelatihan" style="height:30px;" onclick="jQuery.facebox({ ajax: '/admin/batch/search-pelatihan'});">
			<input type="button" style="height:30px;" onclick="ClearFields1();" value="Clear">
			<font color="red">*</font>
		</p>

		<p><label>Nama Coach</label>
			<input readonly class="required" type="text" id="nama_coach" autocomplete="disable" name="nama_coach" style="height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px; background-color: white;" value="<?= $this->nama_coach; ?>" />
			<input class="required" type="hidden" id="id_coach" autocomplete="disable" name="id_coach" value="<?= $this->id_coach; ?>" />
			<input type="button" value="..." id="btncoach" style="height:30px;" onclick="jQuery.facebox({ ajax: '/admin/batch/search-coach'});">
			<input type="button" style="height:30px;" onclick="ClearFields2();" value="Clear">
			<font color="red">*</font>
		</p>
		
		<p>
			<label class="left" for="kuota_peserta">Kuota Peserta</label>
			<input type="text" class="required" id="kuota_peserta" name="kuota_peserta" style="overflow: hidden; display: block; width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px; background-color: white;" <?= ($this->tipe_pelatihan == 'nonclassical' ? 'disabled readonly' : '') ?> value="<?= $this->row->kuota_peserta; ?>"/> 
		</p>
	
		<p>
			<label>Tanggal Awal</label>
			<input class="required" type="text" id="tgl_awal" <?= ($this->tipe_pelatihan == 'nonclassical' ? ' readonly disabled' : '') ?> autocomplete="disable" name="tgl_awal" value="<?= date('d-m-Y', strtotime($this->row->tgl_awal)); ?>" style="width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px; background-color: white;" />
			<font color="red">*</font>
		</p>

		<p>
			<label>Tanggal Akhir</label>
			<input class="required" type="text" id="tgl_akhir" <?= ($this->tipe_pelatihan == 'nonclassical' ? ' readonly disabled' : '') ?> autocomplete="disable" name="tgl_akhir" value="<?= date('d-m-Y', strtotime($this->row->tgl_akhir)); ?>" style="width: 350px; height:30px; padding: 0px; padding-left: 10px; border: 1px solid grey; border-radius: 2px; background-color: white;" />
			<font color="red">*</font>
		</p>

		<br>
			<p id="peserta"> <label>Pilih Peserta dan Mentor</label>
			<!-- Tabel Peserta  -->
			<? if (count($this->peserta) > 0) { ?>
				<?=$this->pager;?>

				<table class="tablesorter">
					<thead>
						<tr>
							<th align="center">
								<script language="javascript">
									checked=false;
									function checkedAll(form) {
										if (checked == false){checked = true;}
										else{checked = false;}
										for (var i=0; i < form.elements.length; i++){
											var name = form.elements[i].name;
											if(name.indexOf("cbDelete",0) == 0)
												form.elements[i].checked = checked;
										}
									}
									</script> 

									<input type="checkbox" onclick="checkedAll(this.form);">
							</th>
							<th>ID</th>
							<th>Nama Peserta</th>
							<th>Mentor</th>
						</tr>
					</thead>
					<tbody>
						<?php
						$index = 0;

						foreach($this->peserta as $row)
						{
							$checked = '';
							$required = '';
							$mentor_id = '';
							$mentor_name = '';
							foreach($this->global as $x)
							{
								if($x->id_peserta == $row->id){
									$checked = 'checked';
									$required = ' class="required"';
									$mentor_id = $this->id_mentor[$x->id_peserta];
									break;
								}
							}
							foreach($this->mentor as $y)
							{
								if($y->id == $mentor_id){
									$checked = 'checked';
									$mentor_name = $y->nama_mentor ;
									break;
								}
							}

							echo '<script type="text/javascript">
									function selectFields4'. $row->id .'(id, id, nama_mentor, id_peserta) {
										$("#id_mentor_'. $row->id .'").val(id);
										$("#nama_mentor_'. $row->id .'").val(nama_mentor);
										$.facebox.close();
									}

									function ClearFields4_'. $row->id .'() {
										document.getElementById("id_mentor_'. $row->id .'").value = "";
										document.getElementById("nama_mentor_'. $row->id .'").value = "";
									}

									$(document).ready(function() {
										$("#cbDelete'. $row->id .'").change(function() {
										  if ($(this).is(":checked")) {
											$("#nama_mentor_'. $row->id .'").addClass("required");
										  } else {
											$("#nama_mentor_'. $row->id .'").removeClass("required");
										  }
										});
									  });
								</script>';

							echo '<tr>';
							echo '<td align="center"><input type="checkbox"'. $checked .' name="cbDelete[]" id="cbDelete' . $row->id  . '" value="' . $row->id . '"></td>';
							echo '<td align="center">'. $row->id .'.</td>';
							echo '<td>'. $row->nama .'</td>';
							echo '<td> 
									<input readonly type="text" '. $required .' id="nama_mentor_'. $row->id .'" placeholder="Pilih Mentor untuk Peserta" autocomplete="disable" name="nama_mentor_'. $row->id .'" value ="'.$mentor_name.'"/>
									<input type="hidden" id="id_mentor_'. $row->id .'" autocomplete="disable" name="id_mentor['. $row->id .']" value="'.$mentor_id .'" />
									<input type="button" value="..." id="btnmentor_'. $row->id .'" onclick="jQuery.facebox({ ajax: \' /admin/batch/search-mentor/'. $row->id .'\' });">
									<input type="button" onclick="ClearFields4_'. $row->id .'();" value="Clear">
									<font color="red">*</font>
								</td>';
							echo '</tr>';
						}
						?>
					</tbody>
				</table>
			<? } else {
				echo 'Data tidak ditemukan.';
			}
			?>
			<!-- End of Tabel Peserta  -->
		</p>

		<input type="hidden" name="id" value="<?= $this->row->id; ?>" />
	    
		<p class="savecancel">
			<?
			//if ($this->getRole() == "admin" || $this->getRole() == "super" || $this->getRole() == "user") {
				echo '<label class="UIbutton-small"><input type="submit" value="Simpan" class=""/></label>';
			//}
			?>
			<a href="/admin/batch/index" class="UIbutton-small">Batal</a>
		</p>
	</div>
</form>
<div style="clear:both"></div>