<script type="text/javascript">
	$(function() {
		$("#compose").validate({
			rules: {
				password: {
					minlength: 6
				},
				confirm_password: {
					minlength: 6,
					equalTo: "#password"
				}
			}
		});
	});
</script>

<div class="content-header"></div>
<div class="UI_Header_Title">
	<h1><?= $this->avatar; ?> Ubah Password</h1>
	<div class="header_nav_links"><a href="/admin/pengguna">Back to Daftar Pengguna</a></div>
</div>
<div class="clear"></div>
<form id="compose" name="compose" method="post" action="" enctype="multipart/form-data">
	<div class="tabular">
		<p><label>Pengguna</label><input readonly class="required" type="text" id="pengguna" autocomplete="disable" name="pengguna" value="<?=$this->row->pengguna;?>" />
			<font color="red">*</font>
		</p>
		<p><label>Email</label><input class="required" type="text" id="email" autocomplete="disable" name="email" value="<?=$this->row->email;?>" />
			<font color="red">*</font>
		</p>
		<hr style="border: 1px dashed gray;">
		<? if ($this->row->jenis == 0) { ?>
			<p><label>Password</label><input class="required" type="password" id="password" autocomplete="disable" name="password" value="" />
				<font color="red">*</font>
			</p>
			<p><label>Konfirmasi Password</label><input class="required" type="password" id="confirm_password" autocomplete="disable" name="confirm_password" value="" />
				<font color="red">*</font>
			</p>
		<? } ?>
	
		<p class="savecancel">
			<input type="hidden" id="id" name="id" value="<?=$this->id;?>" />
			<label class="UIbutton-small"><input type="submit" value="Simpan" class="" /></label>
			<a href="/admin/pengguna" class="UIbutton-small">Batal</a>
		</p>
	</div>
</form>
<div style="clear:both"></div>
<? unset($_SESSION['flash']['data']); ?>