<script type="text/javascript">
	$(function() {
		$("#compose").validate({
			rules: {
				password: {
					minlength: 6
				},
				confirm_password: {
					minlength: 6,
					equalTo: "#password"
				}
			}
		});
	});

	function selectFields(id, nama, param1, param2, param3, param4, param5) {
		$('#id_pengguna').val(id);
		$('#nama').val(nama);
		$('#nip').val(param1);
		$('#jabatan').val(param2);
		$('#unit_kerja').val(param3);
		$('#instansi').val('Sekretariat Jenderal DPR RI');
		$('#username').val(param4);
		$('#email').val(param5);
		$.facebox.close();
	}

	function ClearFields() {
		document.getElementById("id_pengguna").value = "";
		document.getElementById("nama").value = "";
		document.getElementById("nip").value = "";
		document.getElementById("jabatan").value = "";
		document.getElementById("unit_kerja").value = "";
		document.getElementById("instansi").value = "";
		document.getElementById("username").value = "";
		document.getElementById("email").value = "";
	}
</script>

<div class="content-header"></div>
<div class="UI_Header_Title">
	<h1><?= $this->avatar; ?> Edit Pengguna</h1>
	<div class="header_nav_links"><a href="/admin/pengguna">Back to Daftar Pengguna</a></div>
</div>
<div class="clear"></div>
<form id="compose" name="compose" method="post" action="" enctype="multipart/form-data">
	<div class="tabular">
		<? $readonly = ($this->row->jenis == 1) ? ' readonly' : ''; ?>
		<p><label>Jenis</label>
			<select disabled id="jenis2" name="jenis2">
				<option value="">-- Pilih data --</option>
				<?
				$arrJenis = array('0' => 'Eksternal', '1' => 'Internal');
				foreach ($arrJenis as $key => $value) {
					$selected = ($this->row->jenis == $key) ? ' selected' : '';
					echo '<option value="' . $key . '"' . $selected . '>' . $value . '</option>';
				}
				?>
			</select>
			<input class="required" type="hidden" id="jenis" autocomplete="disable" name="jenis" value="<?= $this->row->jenis; ?>" />
		</p>
		<p><label>Nama</label>
			<input<?= $readonly; ?> class="required" type="text" id="nama" autocomplete="disable" name="nama" value="<?= $this->row->nama ?>" />
			<input class="" type="hidden" id="id_pengguna" autocomplete="disable" name="id_pengguna" value="<?= $this->row->id_pengguna ?>" />
			<? if ($this->row->jenis == 1) { ?>
				<input type="button" value="..." id="btnPengguna" onclick="jQuery.facebox({ ajax: '/admin/pengguna/search'});"> <input type="button" onclick="ClearFields();" value="Clear">
			<? } ?> <font color="red">*</font>
		</p>
		<p><label>NIP</label>
			<input<?= $readonly; ?> class="required" type="text" id="nip" autocomplete="disable" name="nip" value="<?= $this->row->nip ?>" maxlength="18" />
			<font color="red">*</font>
		</p>
		<p><label>Jabatan</label>
			<input<?= $readonly; ?> class="required" type="text" id="jabatan" autocomplete="disable" name="jabatan" value="<?= $this->row->jabatan ?>" />
			<font color="red">*</font>
		</p>
		<p><label>Unit Kerja</label>
			<input<?= $readonly; ?> class="required" type="text" id="unit_kerja" autocomplete="disable" name="unit_kerja" value="<?= $this->row->unit_kerja ?>" />
			<font color="red">*</font>
		</p>
		<? if ($this->row->jenis == 0) { ?>
			<p><label>Instansi</label><select class="required" id="id_instansi" name="id_instansi" />
				<option value="">-- Pilih Instansi --</option>
				<?
				foreach ($this->InstansiRows as $row) {
					$selected = ($this->row->id_instansi == $row->id) ? " selected" : "";
					echo '<option value="' . $row->id . '|' . $row->instansi . '"' . $selected . '>' . $row->instansi . '</option>';
				}
				?>
				</select>
				<font color="red">*</font>
			</p>
		<? } else { ?>
			<p><label>Instansi</label><input readonly class="required" type="text" id="instansi" autocomplete="disable" name="instansi" value="Sekretariat Jenderal DPR RI" /> <input class="required" type="hidden" id="id_instansi" autocomplete="disable" name="id_instansi" value="0|Sekretariat Jenderal DPR RI" />
			</p>
		<? } ?>
		<p><label>Jenis Kelamin</label>
			<select id="jenis_kelamin" name="jenis_kelamin">
				<option value="">-- Pilih data --</option>
				<?
				$arrJenisKelamin = array('l' => 'Laki-laki', 'p' => 'Perempuan');
				foreach ($arrJenisKelamin as $key => $value) {
					$selected = ($this->row->jenis_kelamin == $key) ? ' selected' : '';
					echo '<option value="' . $key . '"' . $selected . '>' . $value . '</option>';
				}
				?>
			</select>
		</p>
		<p><label>Nomor Handphone Instansi</label><input type="text" id="handphone" autocomplete="disable" name="handphone" value="<?= $this->row->handphone ?>" />
		</p>
		<p><label>Nomor Telepon Instansi</label><input type="text" id="telepon" autocomplete="disable" name="telepon" value="<?= $this->row->telepon ?>" />
		</p>
		<p><label>Peran</label>
			<select id="peran" name="peran" class="required">
				<option value="">-- Pilih data --</option>
				<?
				$arrPeran = array('admin' => 'Admin', 'super' => 'Super Persipar', 'user' => 'User Persipar', 'guest' => 'User Unit Kerja');
				foreach ($arrPeran as $key => $value) {
					$selected = ($this->row->peran == $key) ? ' selected' : '';
					echo '<option value="' . $key . '"' . $selected . '>' . $value . '</option>';
				}
				?>
			</select>
			<font color="red">*</font>
		</p>
		<hr style="border: 1px dashed gray;">
		<p><label>Pengguna</label><input readonly class="required" type="text" id="pengguna" autocomplete="disable" name="pengguna" value="<?= $this->row->pengguna; ?>" />
			<font color="red">*</font>
		</p>
		<p><label>Email</label><input class="required" type="text" id="email" autocomplete="disable" name="email" value="<?= $this->row->email; ?>" />
			<font color="red">*</font>
		</p>
		<? if ($this->row->jenis == 0) { ?>
			<hr style="border: 1px dashed gray;">
			<p>
				<label>File Penugasan</label>
				<?
				if ($this->row->file_name == "") {
					echo '<input type="file" id="file" autocomplete="disable" name="file"/> <i>(.pdf, max 2 MB)</i>';
				} else {
					echo '<a href="' . $this->url_berkas . '/berkas/' . $this->row->file_name . '" target="_blank">' . $this->row->file_name . '</a> (' . $this->ByteFormat($this->row->file_size) . ')';
					if ($this->getRole() == "admin" || $this->getRole() == "super" || $this->getRole() == 'user') {
						echo ' [<a onclick="return confirmDelete();" href="/admin/pengguna/delete-file/id/' . $this->row->id . '">Delete</a>]';
					}
				}
				?>
			</p>
			<p>
				<label>Pas Foto</label>
				<?
				if ($this->row->image_name == "") {
					echo '<input type="file" id="image" autocomplete="disable" name="image"/> <i>(.pdf, max 2 MB)</i>';
				} else {
					echo '<a href="' . $this->url_berkas . '/foto/' . $this->row->image_name . '" target="_blank">' . $this->row->image_name . '</a> (' . $this->ByteFormat($this->row->image_size) . ')';
					if ($this->getRole() == "admin" || $this->getRole() == "super" || $this->getRole() == 'user') {
						echo ' [<a onclick="return confirmDelete();" href="/admin/pengguna/delete-image/id/' . $this->row->id . '">Delete</a>]';
					}
				}
				?>
			</p>
		<? } ?>

		<p class="savecancel">
			<input type="hidden" id="id" name="id" value="<?= $this->id; ?>" />
			<label class="UIbutton-small"><input type="submit" value="Simpan" class="" /></label>
			<a href="/admin/pengguna" class="UIbutton-small">Batal</a>
		</p>
	</div>
</form>
<div style="clear:both"></div>
<? unset($_SESSION['flash']['data']); ?>